### ISSUE TITLE
Streams mode

### ISSUE THREAD

**Issue by DavidDattner-nbcuni** [Jeffail/benthos#1014]
Is there any way to post not only the configuration of a stream through the streams rest api but also and environment file? 

Also when you use static files to set up streams mode I won’t see a why to pull in environment variable files unless you create resource files?

please help ! Thanks David

**Comment by Jeffail** [comment]
Hey @DavidDattner-nbcuni, there's no way to modify environment variables through the benthos HTTP API, when you load static files you can use an env file the same as any other mode with:

```
benthos -e ./env_vars.env streams ./prod/foo.yaml
```

**Comment by DavidDattner-nbcuni** [comment]
working thanks!
