### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by DavidDattner-nbcuni** [Jeffail/benthos#1017]
So i use a windows PC :) dont hate me. So I basically used your run benthos as a plugin tutorial to create a benthos.exe that runs on windows. It's working great except a few things.

1. when I set PROJECT_DIR=${PWD} in my environment file and then try to use this it doesn't work for example here in my config. I've tried setting to .  and it worksin my configs but when I try to use it in bloblang like: 

import "{PROJECT_DIR}/npimap.blobl" it isn't able to bring it in. Also on windows when I try to import a blobl file like this i can't have carriage returns (new lines) in the file im importing or it breaks? Says:

npimap.blobl: line 1 char 13: expected  or assignment
  |
1 | map npimap {
  |             ^---
Shutting down due to linter errors, to prevent shutdown run Benthos with --chilled

If I put everything on the same line it works.

2. when I try to set a file bloblang env it doesn't work either. 
 I'm doing :  root.fhirpractitionerrole = file(env("BENTHOS_TEST_BLOBLANG_FILE")).parse_json()
and in the env file doing: BENTHOS_TEST_BLOBLANG_FILE=d:/repos/opala/hugsetl/templates/c4bb/PractitionerRole-PBC.json

and when I run it, it complains:  open d:/repos/opala/hugsetl/templates/c4bb/PractitionerRole-PBC.json\r: The filename, directory name, or volume label syntax is incorrect."}

Any idea how to solve this stuff? really frustrating?

thanks again for all your help, really enjoy Benthos!

David.

**Comment by mihaitodor** [comment]
Hey @DavidDattner-nbcuni, thanks for trying out Benthos on Windows! I haven't tried that myself, but, from your comments I'm wondering if the following might help:

> when I set PROJECT_DIR=${PWD} in my environment file
Shouldn't that be something like `PROJECT_DIR=%CD%`?

> Also on windows when I try to import a blobl file like this i can't have carriage returns (new lines) in the file im importing or it breaks? any ideas?
According to [this issue](https://github.com/Jeffail/benthos/issues/946), both `\n` and `\r\n` are supported by bloblang, but it's not clear what is going wrong for you here. Would you be able to share the configs you're trying and the error you're seeing?

> and in the env file doing: BENTHOS_TEST_BLOBLANG_FILE=d:/repos/opala/hugsetl/templates/c4bb/PractitionerRole-PBC.json
Does it help if you change that to `BENTHOS_TEST_BLOBLANG_FILE=d:\repos\opala\hugsetl\templates\c4bb\PractitionerRole-PBC.json`?

If you test out the above and still have issues, I can try to mess around with it on a Windows box tomorrow, but it would help a lot if you can share some sample configs and detailed reproduction steps.

**Comment by DavidDattner-nbcuni** [comment]
still doesn't work. I can't include the env file due to security obviously. but here's the config that doesnt work plus the file im trying to import.

in the env file I did: BENTHOS_TEST_BLOBLANG_FILE=d:\repos\opala\hugsetl\templates\c4bb\PractitionerRole-PBC.json
and now get: 

ailed to create processor 'for_each': child processor [16]: cas
[help.zip](https://github.com/Jeffail/benthos/files/7742078/help.zip)
e [2] processor [4]: line 5 char 29: open d:\\repos\\opala\\hugsetl\\templates\\c4bb\\PractitionerRole-PBC.json\r: The filename, directory name, or volume label syntax is incorrect."}

other 2 files attached! thanks! David.

**Comment by DavidDattner-nbcuni** [comment]
also I tried %CD% never worked had to do .
so 2 issues with the import.
 1. I can't do               import "./npimap.blobl" or               import "./src/npimap.blobl" or import "{$PROJECT_DIR}/src/npimap.blobl" i can only get it from the root of the project.
 2. when I import it from the root the I get the errors with having new lines 

thanks for checking this out for me. Windows issues ! argh! thanks

**Comment by mihaitodor** [comment]
OK, I think you might be able to get away with using `\\` as the path separator. Would you mind giving the attached config a try: `benthos.exe -e benthos.env -c test.yaml`?
[test.zip](https://github.com/Jeffail/benthos/files/7742138/test.zip)
?

**Comment by DavidDattner-nbcuni** [comment]
Cool we're one step closer! I was able to put:

 import ".\\src\\npimap.blobl"

and now it's finding the file in my \src folder.

next any idea why:

.\src\npimap.blobl: line 1 char 13: expected  or assignment
  |
1 | map npimap {
  |             ^---
Shutting down due to linter errors, to prevent shutdown run Benthos with --chilled

and

also the other issue with the:
BENTHOS_TEST_BLOBLANG_FILE=d:\repos\opala\hugsetl\templates\c4bb\PractitionerRole-PBC.json

not working?

thanks!

**Comment by DavidDattner-nbcuni** [comment]
ok this also worked!

  root.fhirpractitionerrole = file(".\\templates\\c4bb\\PractitionerRole-PBC.json").parse_json()

so we're down to just the linting error on the import :) yay! any ideas why line breaks is hurting us in the file?

thanks

**Comment by DavidDattner-nbcuni** [comment]
.\src\npimap.blobl: line 1 char 14: expected  or assignment
  |
1 | map npimap {
  |              ^---
Shutting down due to linter errors, to prevent shutdown run Benthos with --chille
[npimap.zip](https://github.com/Jeffail/benthos/files/7742252/npimap.zip)
d

nothing weird with the file cos it works on linux no problem... maybe I need to put some char at the end of each line on windows?

thanks

**Comment by mihaitodor** [comment]
Thanks for working through this! It looks like the imported bloblang doesn't know about `\r\n`. It should work if you change the line endings in the `.blobl` file to `\n`. We should fix this issue, though. Nice find!

BTW, quite cool that you're working on FHIR. I'm attending some of the FHIR meetings from Optum. Would be curious to talk about this stuff in more detail and see if we can collaborate somehow.

**Comment by DavidDattner-nbcuni** [comment]
ah! def! Please stay in touch. I just started working in this space so learning a lot! Appreciate the quick assists! 
That makes sense and happy to see I helped you find a bug :) Love the product and appreciate the help.

Thanks, David.

**Comment by mihaitodor** [comment]
Awesome! Feel free to connect via todormihai [at] gmail [dot] com or https://www.linkedin.com/in/mtodor/

**Comment by DavidDattner-nbcuni** [comment]
Done! Thanks again, great to see I'm not alone when working with Benthos and have this great support with issues.

I'll close this issue, thanks David.
