### ISSUE TITLE
`NewlineAllowComment` combinator doesn't handle Windows-specific newlines

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#1018]
Looks like 3e486da missed a corner case. Imported bloblang mappings use the `NewlineAllowComment` combinator instead of the `Newline` one. I believe `NewlineAllowComment` should also handle `\r\n` gracefully. Changing it to support `\r\n` does allow the bloblang mapping to be imported successfully and tests still pass, but I'm quite new to this code, so not sure. WDYT?

This is a follow-up to #1017 reported by @DavidDattner-nbcuni.

**Comment by Jeffail** [comment]
Ahhhh, yep, fixed with this: https://github.com/Jeffail/benthos/commit/3032620454ea9846ed65e4f08e07797a5a14b642, well diagnosed!
