### ISSUE TITLE
Bloblang imports question

### ISSUE THREAD

**Issue by DavidDattner-nbcuni** [Jeffail/benthos#1020]
For bloblang imports

Import Maps#
It's possible to import maps defined in a file with an import statement:

import "./common_maps.blobl"

is there a way to substitute the file name with an environment variable?

Reason I need this is that windows needs /n and linux needs /r/n and so I want to be able to set the file I'm importing based on an env variable and switch it out as I go between systems?

thanks, David.

**Comment by DavidDattner-nbcuni** [comment]
Also I should note there is another bug in windows that when I do this:

root.fhirpractitionerrole = file(env("PractitionerRole_PBC")).parse_json()

I get a /n error
: open PractitionerRole-PBC.json\r: The filename, directory name, or volume label syntax is incorrect."

so maybe that can also get fixed as part of the /r/n dealeo

thanks, David.

**Comment by Jeffail** [comment]
Hey @DavidDattner-nbcuni so this is an interesting one, when running on windows the path itself needs to match windows path format, so `./common_maps.blobl` would need to be `.\common_maps.blobl` (I think, haven't used windows for a while). We _could_ do something clever and convert unix style paths to windows, but this would prevent you from being able to specify the drive properly.

I'm really not sure what the best route is for this, I don't do any development on windows so I'm not sure how big a deal this is or whether there are common work-arounds.

**Comment by DavidDattner-nbcuni** [comment]
I'll close since /r/n fix coming. thanks

**Comment by Jeffail** [comment]
We could possibly expand import statements to allow `if` and then if we also add an `os` function we'd be able to do:

```
import if os() == "windows" {
  "./foo/bar.blobl"
} else {
  ".\\foo\\bar.blobl"
}
```

It's a bother to have multiple paths when you have lots of imports, but if we instead tried to translate unix style paths into windows style opaquely then you'd lose the ability to import from specific drive letters.

**Comment by DavidDattner-nbcuni** [comment]
Thanks ! This would work great! 

🙏

**Comment by DavidDattner-nbcuni** [comment]
Btw I’m reaching out to my contacts at NBC Universal as well to see if they are open to evaluating Benthos. I think it’s a great tool that they could benefit from. Of course the ETL people are on vacation for holidays so let’s see when they are back.

**Comment by DavidDattner-nbcuni** [comment]
I figured out that this was related to the CRLF being in my file and as soon as I changed the file to LF only the import worked! So we can close this and it's not an issue after all thanks!
