### ISSUE TITLE
Windows issue with sql processor

### ISSUE THREAD

**Issue by DavidDattner-nbcuni** [Jeffail/benthos#1021]
Again sorry to bother you with windows issues. I've included my config attached. 

When I run this I get:

 failed to load config 'src\pdirzeomega.yaml': yaml: line 232: mapping values are not allowed in this context

when I remove these lines it's fine:
                  - sql:
                      driver: postgres
                      result_codec: json_array
                      data_source_name: "postgres://${DB_USER}:${DB_PASS}@${DB_IPADDRESS}:5432/etldb?sslmode=disable"
                      query: "SELECT internal_id FROM etl.resource_tracker WHERE datasource=''zeomega''and resource_type=''Practitioner'' and external_id=$1;"
                      args_mapping: "[ this.externalid ]"
                 result_map: "root.practitioner_id = this.0.internal_id"

any ideas? thanks again, David.
[pdirzeomega.zip](https://github.com/Jeffail/benthos/files/7746634/pdirzeomega.zip)

**Comment by DavidDattner-nbcuni** [comment]
Nevermind I it needed results_codec or it doesn't work. Error was just misleading. thanks

**Comment by mihaitodor** [comment]
No worries! BTW, we’re up on Discord and Slack if that’s easier for quick questions / chat: https://www.benthos.dev/community
