### ISSUE TITLE
Config issue while adding resources (Windows only maybe)

### ISSUE THREAD

**Issue by DavidDattner-nbcuni** [Jeffail/benthos#1022]
Any idea why this is happening. Spent a few hours and can't get it to work on my windows machine.

 line 317: mapping values are not allowed in this context

I've attached the config file.

thanks! David.
[pdirzeomega.zip](https://github.com/Jeffail/benthos/files/7747306/pdirzeomega.zip)

**Comment by Jeffail** [comment]
@DavidDattner-nbcuni looks like an indentation issue at the bottom, fixed version attached

[pdirzeomega.yaml.zip](https://github.com/Jeffail/benthos/files/7747798/pdirzeomega.yaml.zip)

**Comment by DavidDattner-nbcuni** [comment]
thanks!
