### ISSUE TITLE
Issues having same config run on windows/linux

### ISSUE THREAD

**Issue by DavidDattner-nbcuni** [Jeffail/benthos#1025]
Benthos people. Any way I can avoid this when switching between windows/mac

when on mac:
import "./src/npimap.blobl"
when on windows:
import ".\\src\\npimap.blobl"

Thanks, David.

**Comment by Jeffail** [comment]
As far as I can tell this is the same situation covered in https://github.com/Jeffail/benthos/issues/1020, closing this one in favour of it as it has more information.
