### ISSUE TITLE
Epoch timestamps with decimals

### ISSUE THREAD

**Issue by mhite** [Jeffail/benthos#1032]
Hello. I was hoping to use bloblang to transform a timestamp in the following format:

`2021-12-31T03:37:03.739989357Z`

... to an epoch timestamp with decimal places providing millisecond precision.

I've used `format_timestamp_strftime("%s.%f").number()` which gets me `1640921823.739989`

Ideally I'd like to chop this to 3 decimals of precision to get a millisecond representation.

Is there an elegant way of doing this? I don't see any number manipulation functions in bloblang that would do the trick. Does one need to resort to splitting a string and slicing, and then reassembling somehow? 

New to bloblang, sorry for the novice question.

**Comment by Jeffail** [comment]
Hey @mhite, it's a bit clunky but you can do `(foo.format_timestamp_strftime("%s.%f").number() * 1000).floor() / 1000`. 

The other approach is to use `format_timestamp_unix_nano` and do the same division/floor/division: `(foo.format_timestamp_unix_nano() / 1000).floor() / 1000`

**Comment by mhite** [comment]
@Jeffail - Ah, thanks for suggesting this approach! I think this method is great, although I think it would actually look like this:

```
(this.timestamp.format_timestamp_unix_nano() / 1000000).floor() / 1000
```

... Wherein we convert nanoseconds to milliseconds by division, drop the decimal, and then divide that again to convert into seconds (and being left with millisecond precision in the decimal). Does that sound right?
