### ISSUE TITLE
pipeline.threads calls processor constructors for each individual thread

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#1037]
This can be problematic for processors which create clients with underlying connection pools, such as MongoDB and Redis, because a separate client will be created for each thread if one doesn't use a processor resource.

Ash's thoughts from the Discord chat:

> so this dates back to a long time ago where processors themselves weren't necessarily "pure" in that they could contain state and expect to not be called across multiple threads. however, for ages now all the processors have been forced to be stateless and shareable so we can probably remove that restriction now 
> the only exception that I'm aware of is an ancient batch processor, which was a bit of a hack from the early days that did batching as a processor step
> it's been deprecated and hidden away (with a warning log not to use it) for well over a year now so we can probably disable it entirely
> it's worth me doing a quick run through all the processors for edge cases but they should be ready to go

**Comment by Jeffail** [comment]
Fixed: https://github.com/Jeffail/benthos/commit/093788f4828328e49e9abe8d0a67914c505421ac
