### ISSUE TITLE
Inserting/Updating into Postgres shows no error but not inserting.

### ISSUE THREAD

**Issue by DavidDattner-nbcuni** [Jeffail/benthos#1046]
debug logging is coming in as can be seen in screen capture and no error showing but record is not inserting or updating in DB.

Is there any way I can have it show the error of why its not inserting or updating?

I've attached the files.

thanks! David.

[error.zip](https://github.com/Jeffail/benthos/files/7818388/error.zip)

**Comment by DavidDattner-nbcuni** [comment]
OK I got it to work yay!!! but I still think it's a Benthos bug or is it a me bug? The issue was having the two label/logs and so it never made it to the sql to run. Do you guys think this is a bug on your end or is that not allowed to do?

**Comment by Jeffail** [comment]
Looking at that config it's intended behaviour, if you have a resource but nothing uses it then it won't run. We could maybe show a linting error there but it'd be annoying for people who dynamically swap resources out.

**Comment by DavidDattner-nbcuni** [comment]
Ah makes sense. It’s that the resource is not being used. I thought it was the duplicate that was the issue. I’ll close it out thanks for the clarification. I was worried sql was not showing an error message yet not inserting but it wasn’t even getting to that part of the yaml.
