### ISSUE TITLE
Support for Google Cloud Pub/Sub

### ISSUE THREAD

**Issue by andygrunwald** [Jeffail/benthos#105]
Google Cloud Platform offers [Cloud Pub/Sub](https://cloud.google.com/pubsub/docs/overview).
From the first glance, it looks comparable to the native Redis Pub/Sub functionality in terms of Message delivering and queueing.

With this support, it would enable projects (like mine) to use benthos and use Services from Google Cloud, instead of AWS.

**Comment by Jeffail** [comment]
Hey @andygrunwald, I'd be more than happy to have a GCE pub/sub connector. From looking at the API it seems fairly straight forward to add one. Would this be something you'd be interested in implementing? Otherwise I can probably take a look this week.

**Comment by andygrunwald** [comment]
I would be interested to implement this. Sadly, in the next few weeks, I am quite short on time in my private life. That is the reason why i "just" opened up the ticket to gather first some feedback and getting a first "Yep, sounds good" or "Nope, more information needed".

I am not yet familiar with the benthos source code and would like to use a PR where e.g. Redis was implemented. I think this would be a good guide to see what modifications are necessary.

API-Wise I think I would suggest using the Google cloud pubsub client. They have also a couple of [examples](https://godoc.org/cloud.google.com/go/pubsub#pkg-examples) online.

So if you have time and want to play with Cloud Pub/Sub, feel free.
If I find the time (will be tough), I will post in this ticket something like "ok, I try to start now".
And let's see how is doing this in the end. How does this sound for you?

**Comment by Jeffail** [comment]
Sounds good

**Comment by Jeffail** [comment]
Got it working: https://github.com/Jeffail/benthos/tree/feature/add-gcp-pubsub, haven't tested any edge cases yet but I'll probably merge this week.

**Comment by Jeffail** [comment]
Merged: https://github.com/Jeffail/benthos/commit/35cd4b00bf884ea9bb82d6e005144bee49b17fb6
I'll do a release probably this weekend.

**Comment by andygrunwald** [comment]
Thank you, @Jeffail 
I didn't have time to check the code in detail. I will try to build a product with this and see how it goes :)

**Comment by Jeffail** [comment]
@andygrunwald, cool, I've left the config parameters minimal for now so authentication is done via env vars, meaning it's not possible at this point to read/write using different accounts in the same process. If you want any fields adding open this ticket back up and let me know.

**Comment by andygrunwald** [comment]
completely fine. I think this is also the best approach. Thanks for your effort!
