### ISSUE TITLE
Prometheus input latency as a histogram metric type

### ISSUE THREAD

**Issue by BradLugo** [Jeffail/benthos#1060]
The input latency metric for Prometheus is currently exposed as a summary. This makes it difficult for creating dashboards to view quantiles for the following reasons:
- Summary quantiles cannot be aggregated
- It can be difficult to deduce what timeframe the quantiles cover when using a summary
- Summaries calculate quantiles on the client side

It seems like the consensus in the community is to use histograms rather than summaries for quantiles.

Here are some helpful resources to provide further context:
> In general, summaries are not recommended for use cases where a histogram can be used instead. This is because quantiles cannot be aggregated, and it can be difficult to deduce what timeframe the quantiles cover. Note: this is defined by each client library independently (e.g. Prometheus Go client library uses 10 minutes by default). 

\- https://chronosphere.io/learn/an-introduction-to-the-four-primary-types-of-prometheus-metrics/

> This is one of the big problems with calculating quantiles on the client side. If it's the quantile since the processes started, then the samples get less and less relevant to current conditions as time goes on. It's also not possible to do any math or aggregations once you have a quantile, so you can't stitch things back together given the history of the time series.

\- https://www.robustperception.io/how-does-a-prometheus-summary-work

> The essential difference between summaries and histograms is that summaries calculate streaming φ-quantiles on the client side and expose them directly, while histograms expose bucketed observation counts and the calculation of quantiles from the buckets of a histogram happens on the server side using the histogram_quantile() function.

\- https://prometheus.io/docs/practices/histograms/#quantiles
^ This link is from the official Prometheus documentation and has a handy graph covering the primary differences between histograms and summaries.

**Comment by BradLugo** [comment]
I'm happy to implement this change with a little bit of guidance. It seems like the most apparent issue (as Jeffail mentioned in the Discord) is that completely changing this metric type would break some users' dashboards. I'm unsure of the implications of creating a new metric specifically for this issue, though.

**Comment by BradLugo** [comment]
This seems related to https://github.com/Jeffail/benthos/issues/1066. I'm happy to close this ticket and move the discussion there.

**Comment by Jeffail** [comment]
It's relevant but I still need to read through the implications of changing stuff, I think it's likely that some users would rather keep the existing summaries in order to avoid to server-side calculations, so I'm considering exposing this as a configuration field (we'd probably default to histograms).

I'll mark this as V4 so it definitely gets looked at during the migration.

**Comment by Jeffail** [comment]
Okay so I've added a new field https://github.com/Jeffail/benthos/commit/68ff6a2fd3f2ff17be8cb27a984f47e4b942d55f, which allows you to toggle histograms for timing metrics. The plan is that before v4 goes out we have time to consider changing the default to histograms or not.

**Comment by Jeffail** [comment]
Okay histogram is now the default (on v4) https://github.com/Jeffail/benthos/commit/da1b9d8d4a5d5e8e35ad990f92ff325f3d200405
