### ISSUE TITLE
Fix Issue Where `_benthos_test.yaml` files get included in glob `-r './resources/*.yaml'`

### ISSUE THREAD

**Issue by kennyp** [Jeffail/benthos#1098]
Benthos test files in the form `_benthos_test.yaml` files get included in glob `-r './resources/*.yaml'`.

We should either explicitly exclude the pattern when processing the glob, or skip files that only contain a `test` section when processing `resources`, `streams`, and `templates`

This _could_ also fix the case where a `resource` has an embedded `tests` section and the error `field tests not recognised`

Original thread in Discord: https://discord.com/channels/746368194196799589/754099840354615296/938502114920001597

**Comment by Jeffail** [comment]
Thanks for reporting @kennyp, should be fixed in https://github.com/Jeffail/benthos/commit/a257e8726a0529bd951e54c04233525ff5e26333
