### ISSUE TITLE
Add AckWait config option to `nats_jetstream` input

### ISSUE THREAD

**Issue by zbiljic** [Jeffail/benthos#1106]
For NATS JetStream input, it would be nice to be able to specify custom [AckWait](https://docs.nats.io/nats-concepts/jetstream/consumers#ackwait) configuration option.
It for configuring time that the NATS server will wait for an ack for any individual message. If an ack is not received in time, the message will be redelivered.

I found this useful for a pipeline that batches entries for extended time duration (above default consumer time limit of `30s`).

Also, I have already implemented this change [here](https://github.com/zbiljic/benthos/tree/feature/nats_jetstream_input_ack_wait), however following contributing guide I am creating this ticket (before possible PR).

Thank you for your consideration.

**Comment by Jeffail** [comment]
Hey @zbiljic, yeah absolutely I think that'd be great to add.

**Comment by zbiljic** [comment]
Great, then I will create a PR now.
