### ISSUE TITLE
benthos.input.amqp logs password in cleartext

### ISSUE THREAD

**Issue by remen** [Jeffail/benthos#111]
When using amqp as input, the full URL, which includes the password, is logged on info level.

```json
{"@timestamp":"2018-09-27T11:39:55Z","@service":"benthos","level":"INFO","component":"benthos.input.amqp","message":"Receiving AMQP messages from URL: amqps://fakeuser:fakepassword@mi-input-broker-staging.meltwater.net\n"}
```

**Comment by Jeffail** [comment]
Yikes, thanks for raising this @remen!

Fixed: https://github.com/Jeffail/benthos/commit/c43cff528690b41f9ec9722a51ffe778f263532c
Released: https://github.com/Jeffail/benthos/releases/tag/v0.34.1
