### ISSUE TITLE
this.ip mapping seems to have conflicts with environment ip

### ISSUE THREAD

**Issue by brivadeneira** [Jeffail/benthos#1110]
Hello,

Receiving some messages from a pubsub topic, one of the fields to map is called "ip",
howerver, after deploying the pipeline in a kubernetes environment, 
ip value is the pod address, instead of the ip field from the pubsub messages.

Is my pipline calling some reserved method from benthos?

Thanks!

**Comment by Jeffail** [comment]
Hey @brivadeneira, there aren't any reserved fields within structured payloads, and reserved metadata fields are only added during ingestion. Are you able to share any details about your config?

**Comment by brivadeneira** [comment]
> Hey @brivadeneira, there aren't any reserved fields within structured payloads, and reserved metadata fields are only added during ingestion. Are you able to share any details about your config?

Thanks for the answer!

Do you mean config.yaml file?

**Comment by Jeffail** [comment]
Yeah, whereever your processors are configured that populate values and perform message mappings.

**Comment by brivadeneira** [comment]
Dear @Jeffail , it doesn't seem to be a benthos issue, so I will close this issue.

Thank you so much for your time!!!
