### ISSUE TITLE
Add a security policy (SECURITY.md)

### ISSUE THREAD

**Issue by disintegrator** [Jeffail/benthos#1111]
Consider adding a security policy which includes a statement about supported version and guidance on disclosing security issues. GitHub starts can start you off with a sensible template here: https://github.com/Jeffail/benthos/security/policy.

**Comment by disintegrator** [comment]
I'd be happy to contribute an initial draft that you can fill in with your details @Jeffail!

**Comment by Jeffail** [comment]
Hey yeah thats a great idea, we can use security@benthos.dev for receiving alerts.
