### ISSUE TITLE
ElasticSearch _bulk Support

### ISSUE THREAD

**Issue by seanlaff** [Jeffail/benthos#112]
This library is awesome Jeffail, thanks for your work on it.

Currently the elasticsearch output iterates over the messages and makes a post to elasticsearch for each. For large scale elasticsearch ingestion, it is preferred to use the `_bulk` endpoint.  

I think we should add a `bulk` flag to the elasticsearch config that controls whether the requests go through `_bulk`, or the `index` endpoint. This will make `batch` processors in benthos perform better with elasticsearch.

**Comment by Jeffail** [comment]
Hey @seanlaff, sounds good. Is there a significant disadvantage to using the `_bulk` endpoint? If not I'd probably default to using it when batch sizes are greater than 1 and we can avoid extra config fields.

**Comment by iluminae** [comment]
+1 to transparently using bulk on `message.Len() > 1`.

From my understanding, using bulk will transfer all the changes in the bulk 'batch' and afterwards execute reindexing on those new documents. This should reduce load on the server - and thus increase potential throughput.

**Comment by seanlaff** [comment]
The len > 1 approach sounds good to me.

The downside with `_bulk` is that all of the documents in a request do *not* get executed as a transaction- meaning any number of the documents could fail to be inserted (schema mis-match, version conflict, etc).

You could find yourself in a situation where you have a benthos `batch` processor that is grouping together 1000 documents to send to the elasticsearch writer. Elasticsearch could respond that 999/1000 were indexed successfully, but since there is 1 failure, I assume we'd fail the benthos pipeline. That 1 bad document might never be indexable (i.e. for a schema problem), which means benthos would assume that all 1000 parts failed, while in reality only one did and retry (infinitely?).

We could call this out in the docs and let users know they might want to include a `retry` output as part of any `batch` processors that use elasticsearch. With this approach though, if a retrier gives up because of that one faulty document, will that batch of 1000 ever get ack'd?

**Comment by cludden** [comment]
I've encountered a similar problem with Kinesis' bulk write functionality. I opted for the Kinesis [output](https://github.com/Jeffail/benthos/blob/master/lib/output/writer/kinesis.go#L203) to inspect the bulk response for transient errors and retry with backoff logic. I have used a similar approach with elasticsearch in the past, however, certain errors (mapping conflicts, invalid payloads) will never be resolved without updating the batch contents, in which case there would be really be no other choice but to fail the entire batch

**Comment by Jeffail** [comment]
Yeah I was going to suggest we model this based on the Kinesis output work @cludden did. There's a chance I can tackle this later in the week, maybe next, but I've got other priorities right now.

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/654064f5537f5ecc9a9068e70c2145c41d39d6b0
Released: https://github.com/Jeffail/benthos/releases/tag/v0.34.13

Give it a try and let me know how it goes.

**Comment by Jeffail** [comment]
Closing for now, if any issues pop up then please reopen this ticket.
