### ISSUE TITLE
S3 output set 'endpoint' to allow use with non-amazon servers

### ISSUE THREAD

**Issue by iluminae** [Jeffail/benthos#113]
The S3 input has the SQS functionality that does not really translate to other services, but the S3 output works great with google gcs (w/ interoperability api, aka S3) and minio.

it would be extremely easy to add to this minimally, eg:
```diff
@@ -47,6 +47,7 @@ type AmazonAWSCredentialsConfig struct {

 // AmazonS3Config contains configuration fields for the AmazonS3 output type.
 type AmazonS3Config struct {
+       Endpoint    string                     `json:"endpoint" yaml:"endpoint"`
        Region      string                     `json:"region" yaml:"region"`
        Bucket      string                     `json:"bucket" yaml:"bucket"`
        Path        string                     `json:"path" yaml:"path"`
@@ -113,6 +114,9 @@ func (a *AmazonS3) Connect() error {
        if len(a.conf.Region) > 0 {
                awsConf = awsConf.WithRegion(a.conf.Region)
        }
+       if len(a.conf.Endpoint) > 0 {
+               awsConf = awsConf.WithEndpoint(a.conf.Endpoint)
+       }
        if len(a.conf.Credentials.ID) > 0 {
                awsConf = awsConf.WithCredentials(credentials.NewStaticCredentials(
                        a.conf.Credentials.ID,
```

The unfortunate part is the code says Amazon alot, but the above is all that is necessary.

**Comment by Jeffail** [comment]
Hey @iluminae, sounds good. I'm happy to tackle this next time I revisit AWS configs. I'm thinking of reducing the code duplication across `aws` components in Benthos, I'll make sure to add an `endpoint` field when I do it.

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/e56253b5684d5b0eddb1d3d4094c157bd19d506c
Released: https://github.com/Jeffail/benthos/releases/tag/v0.34.3
