### ISSUE TITLE
'aws_s3': failed to create input 'aws_s3': codec was not recognised: csv:| on V3.60.1

### ISSUE THREAD

**Issue by DavidDattner-nbcuni** [Jeffail/benthos#1138]
using [github.com/Jeffail/benthos/v3](http://github.com/Jeffail/benthos/v3) v3.60.1

'aws_s3': failed to create input 'aws_s3': codec was not recognised: csv:|

when trying to use

input_resources:
  - label: combinedmemberrosterdb_input
    aws_s3:
      codec: "csv:|"
      region: ${AWS_REGION}
      delete_objects: true
      credentials:
        id: ${AWS_ACCESS_KEY_ID}
        secret: ${AWS_SECRET_ACCESS_KEY}
        token: ${AWS_SESSION_TOKEN}
      sqs:
        # ObjectCreate events in S3 are published to SQS queue.  We read msgs from the queue here..
        url: ${AWS_SQS_CREATEOBJ_COMBINEDMEMEMBERROSTER_URL}
        key_path: Records.*.s3.object.key
        bucket_path: Records.*.s3.bucket.name
        max_messages: 10

thanks

**Comment by Jeffail** [comment]
This was added in v3.61: the custom delimiter part was added in v3.61: https://github.com/Jeffail/benthos/blob/master/CHANGELOG.md#3610---2021-12-28
