### ISSUE TITLE
Small docs issue under Batch Policy

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#1142]
The first paragraph [here](https://www.benthos.dev/docs/configuration/batching#batch-policy) starts with the following:
> When an input component has a config field `batching` that means it supports a batch policy.

However, the example below shows an output instead of an input.

**Comment by Jeffail** [comment]
Thanks, keen eyes @mihaitodor. I'm not actually sure why it was ever specified as an input thing.

**Comment by Jeffail** [comment]
Clarified some other stuff while I was at it: https://github.com/Jeffail/benthos/commit/231bdfe7310f1e285bd204425793493d81f82f12

**Comment by mihaitodor** [comment]
That clarifies things, thanks @Jeffail! ❤️
