### ISSUE TITLE
Suggestion: Subprocess processor

### ISSUE THREAD

**Issue by simonrussell** [Jeffail/benthos#118]
It would be super useful for making some more complex transformations to be able to run a subprocess and pipe data through it.  There could be a few options, but the simplest one would be one-line-in stdin maps to one-line-out on stdout.  Stderr would be passed on (for logging purposes).

Benthos is super useful because it can connect to so many things; it would make doing a totally custom transformation in the middle a lot easier because that binary wouldn't need any of the plumbing.

If this is already a feature (or a rejected suggestion) then apologies; I did do a bit of a search before creating this issue.

**Comment by Jeffail** [comment]
Hey @simonrussell, would you be able to give a detailed use case? There might be an existing solution I can offer.

**Comment by simonrussell** [comment]
I'll give you a hypothetical which is close enough to how I want to use it (the actual use case is probably too complicated, but this captures the core of it).

I've got a bunch of compressed JSON events coming in a Kinesis stream; I need to be able to process one at a time (not necessarily in-order) in a way which can't be done with Benthos (actually understanding what the payload is etc).  Then I'm writing them to S3 in a batch, compressed.  Benthos would be doing the decompression/compression.

As you can see, Benthos can do a lot of those steps except for the core one.  I could put it in front, piping out to stdout, through my code, then into another Benthos instance on the other end.  But it would be excellent if I could run several instances of my code in parallel, to speed things up.  Once I start doing that, things get pretty complex.  It would be great to use Benthos as a wrapper around my code, so the only thing I need to focus on is my processing task.

How I see it working is that Benthos would do some process management; I suppose there could eventually be various options for how to communicate with the process, and whether to run it once per event (good for adapting some existing stuff) or once per stream (good for customised stuff, or some stream-oriented existing things).  So somewhat like the existing lambda and http processors.

I think this would be a good addition to the general swiss-army knife approach.

**Comment by Jeffail** [comment]
Cool, I've had similar requests in the past. The development of something like this wouldn't be too heavy in terms of effort, but we'd need to do three things:

1. Modify processors to all have a `Close` method, where we would perform our clean up of the process being managed. This would include modifying the general interface for processors.
2. Update all components that have child processors so that they propagate calls to `Close` to their children. This list would include various inputs, processors and outputs.
3. Add a new processor that runs a command. It could have a config param that determines whether to run the command per message or per stream.

**Comment by Jeffail** [comment]
Hey @simonrussell, got an experimental version of this now: https://github.com/Jeffail/benthos/tree/master/docs/processors#subprocess

Implemented: https://github.com/Jeffail/benthos/commit/1c41d0401c4995b70a923ea3d9be4bc7fa158d74
Released: https://github.com/Jeffail/benthos/releases/tag/v0.40.0

**Comment by Jeffail** [comment]
Closing this ticket but if you want to propose and discuss changes feel free to reopen it.

**Comment by simonrussell** [comment]
Looks awesome, I hope to get a chance to try it out over the coming days. Thanks :)
