### ISSUE TITLE
Add regex operator to the text processor

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#124]
It would be nice to have a text processor operator for reducing the document to a regular expression partial match, we currently already have a replace with regexp operator: https://github.com/Jeffail/benthos/tree/master/docs/processors#replace_regexp, but it would also be good to have an operator to simply return the matching section of the expression.

I'm labeling this as a good first issue as it should be a simple matter of mostly copying the existing function from here: https://github.com/Jeffail/benthos/blob/master/lib/processor/text.go#L170

**Comment by u5surf** [comment]
@Jeffail Hi, I'm supposed to work for this issues. but my localmachine does not find "nanomsg.org/go-mangos"
```
[yugo-horie@benthos ]$make
go: nanomsg.org/go-mangos@v1.4.0: unrecognized import path "nanomsg.org/go-mangos" (parse https://nanomsg.org/go-mangos?go-get=1: no go-import meta tags ())
go: error loading module requirements
make: *** [target/bin/benthos] Error 1
```

go version
```
[yugo-horie@benthos 12:45:24]$go version
go version go1.11.1 darwin/amd64
```

I think  go-mango has moved github.com/nanomsg/mangos

**Comment by Jeffail** [comment]
Hey @u5surf, I tried to pull it locally and it worked, that import path is what the owner recommends so I'd rather not change it https://github.com/nanomsg/mangos#using-go-get 

Are you able to connect to nanomsg.org at all?

**Comment by Jeffail** [comment]
Merged: https://github.com/Jeffail/benthos/commit/c8379a2ad7d99d2e247e795353913f7a3692fb3c
Released: https://github.com/Jeffail/benthos/releases/tag/v0.36.3

Thanks @u5surf
