### ISSUE TITLE
Dynamically discover Kinesis Shards + automatic horizontal scaling

### ISSUE THREAD

**Issue by patrobinson** [Jeffail/benthos#127]
[The Kinesis configuration requires you to specify a shard](https://github.com/Jeffail/benthos/blob/master/docs/inputs/README.md#kinesis) to receive records from. Ideally we should discover shards automatically.

I maintain a [Kinesis library](https://github.com/patrobinson/gokini) written purely in Golang (i.e. not using the Java MultiLangDaemon) and was wondering if you'd be interesting in integrating it into this project? It currently supports automatic shard discovery.

Currently the library doesn't support dynamically distributing shards across workers to scale horizontally automatically but I see that as the next feature to be added.

If you think this is worthwhile I will put up a Pull Request.

**Comment by patrobinson** [comment]
Hmm, no we try and gracefully shutdown (i.e. let it finish what it's doing).

I'd consider this an "ungraceful" shutdown, which we don't have an API to signal that. Let me have a think about how that could be implemented.

**Comment by patrobinson** [comment]
Thanks @Jeffail I've got ungraceful termination support in my library now and will work on integrating it with Benthos next.

**Comment by patrobinson** [comment]
Thinking about the integration, Benthos wants to pull records from an input, where as my library pushes records to a consumer. This copies the [AWS implementation](https://github.com/awslabs/amazon-kinesis-client).

To resolve this discrepancy we have two options:
- Implement some new interface to allow for pulling records from the stream, bearing in mind there would need to be some upper bounds on the amount of data returned as it could be very large.
- Implement a buffered channel to keep data from our client library ready for processing while not exhausting memory if the consumer cannot keep up.

**Comment by Jeffail** [comment]
Hey @patrobinson, from your description it sounds like it might be simplest to go for something like the `nsq` input: https://github.com/Jeffail/benthos/blob/master/lib/input/reader/nsq.go, where we have an intermediary channel just to convert from one interface to another.

**Comment by kconwayatlassian** [comment]
My team is pretty interested in this feature but it seems like this thread, and the PR, have gone stale. Is there any outstanding work we could help complete?

**Comment by Jeffail** [comment]
@kconwayatlassian, everything looks good except if we merge right now we'd be missing the ability to set explicit `credentials`, which makes it inconsistent with other AWS components. In order to add `credentials` we need to be able to propagate (or modify) the underlying AWS session in the client lib, I believe @patrobinson was going to take a look into enabling that.

It would also be good to have some integration tests here: https://github.com/Jeffail/benthos/blob/master/lib/test/integration/aws_test.go

**Comment by patrobinson** [comment]
Hopefully my PR is ready now. I'd be interested in your experience if you do end up using it

**Comment by Jeffail** [comment]
Reopening as I still need to enable it and add documentation.

**Comment by Jeffail** [comment]
Okay it's added. I'm not able to test it right now, is someone able to give it a play?

**Comment by Jeffail** [comment]
Closing this for now as we seem pretty stable. I'm leaving the BETA tag on the docs until someone reports using this in production.
