### ISSUE TITLE
support nats_streaming max-inflight config param

### ISSUE THREAD

**Issue by thinktainer** [Jeffail/benthos#129]
It would be good for the nats streaming config to expose the MaxInFlight parameter (https://github.com/nats-io/go-nats-streaming/blob/master/sub.go#L111).
This would help us achieve desired batch document size for indexing in elasticsearch. We have small messages. Our buffers are not going to be of a reasonable size with the default configured max of 1024 messages.

**Comment by Jeffail** [comment]
Hey @thinktainer, sounds sensible. Would you be able to make a pull request for this? Otherwise I can grab it next time I have a chance.

**Comment by thinktainer** [comment]
#130

**Comment by Jeffail** [comment]
Thanks @thinktainer!

Implemented: https://github.com/Jeffail/benthos/commit/b96c689d45999d6f6ce6c2511502c042aefc5494
Released: https://github.com/Jeffail/benthos/releases/tag/v0.37.4
