### ISSUE TITLE
define / explain monitoring strategies for containerized environments

### ISSUE THREAD

**Issue by thinktainer** [Jeffail/benthos#135]
I could not find any documentation / specifications for how to monitor the service processes health or readiness. This would greatly help along satisfying our requirements for deploying benthos pipelines in a kubernetes environment. I would like to suggest that as a starting point a link to a blog post / video explaining how to do this would be great (discoverable via Readme.md ideally).

**Comment by Jeffail** [comment]
Hey @thinktainer, thanks for raising this. You can use the HTTP endpoint `/ping` to check whether the service is running and as a general healthcheck.

The concept of "readiness" in the case of Benthos is somewhat muddy as it depends on exactly what the input and output configurations look like so I'm not entirely decided on what a good mechanism here would be. For the majority of use cases the service is ready to serve messages as soon as `/ping` is active, so for now it can probably be used to signify both.

I'll plan to add some documentation to the README, perhaps above the metrics paragraph in the run section.

**Comment by thinktainer** [comment]
I just discovered that these metrics will allow us to do what we need to in our orchestration, by using prometheus alerts. 
Sharing here to give some pointers to doc efforts / other users who might search for this:
```curl -s localhost:8081/metrics | grep '^[^#].*connection_failed'                                                         benthos_input_connection_failed 322
benthos_input_nats__stream_connection_failed 322
benthos_output_connection_failed 0
benthos_output_tikv_connection_failed 0
```

**Comment by Jeffail** [comment]
Hey @thinktainer, the next major release will have an endpoint `/ready`, which returns a 200 only when both the input and output are connected, otherwise a 503 is returned. I've added a small section to the README explaining this in a new monitoring section: https://github.com/Jeffail/benthos#monitoring

**Comment by thinktainer** [comment]
Awesome, Thank You very much for the fast turn around! Happy to close this now.
