### ISSUE TITLE
Question regarding batch period

### ISSUE THREAD

**Issue by rucciva** [Jeffail/benthos#138]
Hi @Jeffail, just a quick question regarding batch processor,

the docs said 'The period field is non-empty and the time since the last batch exceeds its value'. Does it means the period option will not be in effect at the first batch?

In my case, i have set it up as output-broker's processor (consisting of kafka and elasticsearch) with 20MB batch and 10000 period. But in about 15 minutes , i dont see the outputs sending any data (my data rate is relatively slow currently). Only when i set count to 100 that i see some outputs being sent.

**Comment by Jeffail** [comment]
Hey @rucciva, it should work with the first batch. Did you upgrade recently? The newest version of Benthos no longer has int based periods so it might be that you need to change a field. If you run `benthos -c yourconfig.yaml --lint` it should tell you.

**Comment by rucciva** [comment]
yes i was using 0.41.1 I didn't test it further with that version but since upgrading to 0.42.1 it works.

thanks again.
