### ISSUE TITLE
ExpiredIteratorException in Kinesis

### ISSUE THREAD

**Issue by danrubenstein** [Jeffail/benthos#139]
Hi @Jeffail (et al)

Thanks for this library, I'm really excited by it. 

I noticed that in the kinesis input reader, if one is using the dynamodb table to manage commits to the log, if the Benthos kinesis reader records a message with 0 records, Benthos will throw a timeout error (see https://github.com/Jeffail/benthos/blob/master/lib/input/reader/kinesis.go#L230). I'm sure there's a good reason for this, but one consequence is that the iterator doesn't get updated (https://github.com/Jeffail/benthos/blob/master/lib/input/reader/kinesis.go#L249), so after 300 seconds or so, I start seeing this kind of error. 

```
Failed to read message: ExpiredIteratorException: Iterator expired. The iterator was created at time Thu Dec 27 15:40:30 UTC 2018 while right now it is Thu Dec 27 15:46:18 UTC 2018 which is further in the future than the tolerated delay of 300000 milliseconds.
```

The only way that I've seen to get around this without changing Benthos is to stop the application, delete the DynamoDB table, and then restart the application. 

I'm wondering if you'd be willing to look at a PR that I could put together in the next week or so that would hopefully fix this problem if the kinesis shard returns 0 records. Since the current behavior is to start throwing this exception, I would probably lean towards adding a config flag (although given that the library is not at 1.0, maybe we could permanently change it - I defer to your judgement on this one) to allow the iterator to be updated based on that flag.

If you think this is a reasonable strategy, I'll get started on this PR, and hopefully have it for you in a few days.

Thanks again for all your work here.

**Comment by Jeffail** [comment]
Hey @danrubenstein, next time I'm at a laptop I should be able to quickly fix this. If you want to try a PR that's also fine, I'm pretty sure https://github.com/Jeffail/benthos/blob/master/lib/input/reader/kinesis.go#L249 needs to be moved before the return statements so that the latest iterator is always kept.

**Comment by Jeffail** [comment]
@danrubenstein I suspect this is what is needed: https://github.com/Jeffail/benthos/commit/895562a270d3933842d38f57497c9004e9098d46 but I don't have any Kinesis sources to try it out with. Could you test it with v0.42.2?

**Comment by danrubenstein** [comment]
Hi @Jeffail 

Thanks for pushing this update. 

I did a little bit of testing with this, and it seems like it solves the immediate issue in a single benthos connection (in my case, Kinesis stream to http connection). However, even with this fix, there's a broad issue that the change to the shard iterator does not actually get committed to the Dynamo table. As a result, if you stop the application and then restart it, the new Kinesis reader will take in the stale commit value from Dynamo, as the previous version of the application never committed it.

From my reading of the code, it looks like the Kinesis commit to dynamo happens in the `Acknowledge` function, which is called this chunk of the reader loop: https://github.com/Jeffail/benthos/blob/master/lib/input/reader.go#L204. However, because a 0 record kinesis read throws a timeout error (https://github.com/Jeffail/benthos/blob/master/lib/input/reader/kinesis.go#L235), the reader loop will pick up this error and skip through the rest of the acknowledge code entirely (https://github.com/Jeffail/benthos/blob/master/lib/input/reader.go#L177). 

Again, I'm happy to look at a solution here, but before I get too far into the weeds with tearing apart the kinesis reader, I'm wondering if you have any other recommendations for **how you would prefer Benthos handle the acknowledge of empty reads**. For example, in the metrics, should an "empty read" count as a success? With Kafka, for example, it looks like a similar error is thrown (https://github.com/Jeffail/benthos/blob/master/lib/input/reader/kafka.go#L324), although from what little I know about Kafka, the whole setup is such that the commit offsets are not time based. 

To force something through, we could just force the commit in that if statement (as shown in the following). I've tested this on a kinesis shard + dynamo and it appears to fix the problem, although it feels sort of hack-y.

```
	if res.NextShardIterator != nil {
		k.sharditer = *res.NextShardIterator
	}

	if len(res.Records) == 0 {
		k.sharditerCommit = k.sharditer
		k.commit()
		return nil, types.ErrTimeout
	}
```

Thanks again, and let me know if you have any questions for me.

**Comment by Jeffail** [comment]
Hey @danrubenstein, dang, I see the problem. My understanding of Kinesis is limited so I previously understood the shard iterator as a simple record offset. We can't commit the iterator out of sync with message transactions otherwise we lose our at-least-once delivery guarantees.

I can check for the iterator expiry error during the `Read` call, and that way when it expires we can acquire a new one. From my understanding this situation is unavoidable since we'll hit it if the service is stopped for more than the expiry duration.

I'll take another read through their documentation tomorrow and see if there's something I can do.

**Comment by Jeffail** [comment]
@danrubenstein, turns out I can specify the starting sequence number in the GetIterator request so I'll use that, should fix all of these issues. Hopefully I can get a build out tomorrow.

**Comment by danrubenstein** [comment]
No worries! Thanks for being so responsive to one issue.

I'll probably have a chance to run it by some point tomorrow during the day. I've been using it in docker, so that's (weakly) preferred, although I can also build the binary from that branch, so long as the `make install` command still works. 

Is there a more formal testing setup for kinesis beyond what's in the makefile and associated go source files? I'm not sure what I can commit to in terms of building at the moment, but we're definitely considering this for a good chunk of work over the next few months, so I'm happy to take at least take a look.

**Comment by Jeffail** [comment]
Cool, I've pushed a docker image with the tag `jeffail/benthos:v0.42.2-kinesis-test-1`. What would be awesome is if you could test steps like this:

- start stream with existing dynamo table from before
- see data flow
- stop data flow but leave service running for 10 mins
- restart data, make sure it starts flowing again
- stop Benthos for 10 minutes (wait for expiry)
- start Benthos and make sure the stream picks back up from where it last stopped

**Comment by Jeffail** [comment]
Gave it a slam today and it looks okay, I'll do a proper tag/release this evening unless you report errors.

**Comment by danrubenstein** [comment]
Sounds like a good plan today. I'll keep you posted with what I find.

**Comment by danrubenstein** [comment]
Alright! It worked!

The steps I ran through are what you outlined in the previous posting.

-------

Reference configuration (for folks who want to reproduce).

`config.yaml` (to be mounted inside the docker container)

```
input:
  type: kinesis
  kinesis:
    client_id: ${INPUT_KINESIS_CLIENT_ID:benthos_422_kinesis_client_test}
    commit_period_ms: ${INPUT_KINESIS_COMMIT_PERIOD_MS:1000}
    dynamodb_table: ${INPUT_KINESIS_DYNAMODB_TABLE:benthos_422_kinesis_test_table}
    limit: ${INPUT_KINESIS_LIMIT:1}
    region: us-east-1
    shard: ${INPUT_KINESIS_SHARD:0}
    start_from_oldest: ${INPUT_KINESIS_START_FROM_OLDEST:true}
    stream: ${INPUT_KINESIS_STREAM:benthos_422_kinesis_test_stream}
    timeout_ms: ${INPUT_KINESIS_TIMEOUT_MS:5000}
output:
  type: stdout
  stdout:
    delimiter: ${OUTPUT_STDOUT_DELIMITER}
```

AWS CLI commands to put data in (I roughly used a `while { do this }` type command to make the flow happen with discrete data).

```
aws kinesis put-record --stream=benthos_422_kinesis_test_stream --data="Data=\""$(date +%s)"\"" --partition-key="Data"
```

**Comment by Jeffail** [comment]
Ace! Thanks a lot for raising this and taking the time to try my fixes out.

Fixed: https://github.com/Jeffail/benthos/commit/7729b084a2fdc648fceaf02c42f3ae6324262a6a
Released: https://github.com/Jeffail/benthos/releases/tag/v0.42.3
