### ISSUE TITLE
Case statement processor

### ISSUE THREAD

**Issue by patrobinson** [Jeffail/benthos#141]
I have a use case where I want to normalise some data from a JSON blob that looks something like this:

```json
    "field": {
        "type": "value",
        "a": "b"
    },
```

The contents of "field" depends on the "type" value. We want to normalise the field to have a single, consistent value based on the "type" and some other information.

Currently we do this in python with a dictionary of lambdas

```python
def normalise_field(record):
    return {
      'TypeA': lambda: "somevalue",
      'TypeB': lambda: "someothervalue",
    }[record["field"]["type"]]()
```

Alternatively this could be done in a case statement. Trying to implement this in Benthos I created a rather complex nested conditional processor. This isn't very succinct and is hard to read.

Is there a better way of doing this? Should there be a "switch" processor that enables you to execute arbitrary processors depending on the value of a field?

**Comment by Jeffail** [comment]
Hey @patrobinson, sounds like a sensible idea. I would probably add both a `switch` and a `switch_value` processor similar to the `group_by` and `group_by_value` processors.

It might be a while before I have time to implement these, but in the meantime you can probably achieve something only slightly more verbose than your python function with the [`awk` processor](https://github.com/Jeffail/benthos/tree/master/docs/processors#awk):

``` yaml
type: awk
awk:
  codec: none
  program: |
    function avalue() {
      print create_json_object("foo", json_get("field.a"))
    }
    function bvalue() {
      print create_json_object("bar", json_get("field.b"))
    }
    BEGIN {
      type = json_get("field.type")
      if ( type == "a" ) {
        avalue()
      } else if ( type == "b" ) {
        bvalue()
      }
    }
```

If you want to try this out then I recommend using v1.0.1 or above. The custom functions in the `awk` processor are still a work in progress so they are somewhat limited right now, let me know if there's more functions you need.

**Comment by Jeffail** [comment]
Hey @patrobinson, I've just added a `switch` processor: https://github.com/Jeffail/benthos/tree/master/docs/processors#switch, although your usecase would probably be better solved with a `switch_by_value` processor (TBD).

**Comment by Jeffail** [comment]
Closing this for now as I want to see how this processor plays out before touching it again.
