### ISSUE TITLE
Plugin support on docker image

### ISSUE THREAD

**Issue by thinktainer** [Jeffail/benthos#148]
I was trying to add some compiled plugins to the premade docker image you supply (thank you). However, since CGO is disabled in that build, and go plugins require dlopen() there's nothing i can do other than make my own docker container if i want plugin support. Would you consider providing a container build (potentially in addition to the one you already provide), that has this flag disabled, and allows dynamic linking?

**Comment by Jeffail** [comment]
Hey @thinktainer, there's images tagged with zmq (`latest-zmq`,`v1.1.3-zmq`, etc) that are built with cgo in order to link with ZMQ which you could try.

I haven't tried compiling plugins for docker use yet, but it's extremely sensitive to changes in the build environment so you will probably want to use the dockerfile as a base image: https://github.com/Jeffail/benthos/blob/master/resources/docker/Dockerfile.zmq

**Comment by bertpersyn** [comment]
Hi thinktainer. 

This is what I use (not optimized in any way!!) and is Jenkins proof (the builder stuff of docker can be a pita):

```
FROM golang:latest

WORKDIR /go/src/github.com/Jeffail/benthos/
RUN wget -qO- https://github.com/Jeffail/benthos/archive/v1.1.3.tar.gz | tar xvz -C /tmp

RUN cp -R /tmp/benthos-1.1.3/* /go/src/github.com/Jeffail/benthos/
RUN ls /go/src/github.com/Jeffail/benthos/
RUN cd /go/src/github.com/Jeffail/benthos/

ENV GO111MODULE on
RUN go mod download
RUN GOOS=linux VERSION=1.1.3 make

FROM myrepo.com/docker-base-minimal-master:latest
RUN apk add libc6-compat

COPY --from=0 /go/src/github.com/Jeffail/benthos/target/bin/benthos .
COPY --from=0 /go/src/github.com/Jeffail/benthos/config/env/default.yaml /benthos.yaml
COPY ./benthos-plugins.so /usr/lib/benthos/plugins/

EXPOSE 4195

ENTRYPOINT ["./benthos", "-c", "/benthos.yaml"]
```

**Comment by thinktainer** [comment]
I'm using a similar approach as @bertpersyn. I can trial the zmq image as a base for our plugin experiments, and report back here. At the moment i'm using a similar approach to @betpersyn, where i'm building my own benthos + plugins.

**Comment by Jeffail** [comment]
I've made some improvements to the https://github.com/benthosdev/benthos-plugin-example repo but still haven't found a reasonable workflow for using real Go plugins. I'm giving up on this for now, so my general advice and support is going to be around maintaining a custom `main` function that uses Benthos as a library. It's more work overall but trying to document how to work with Go plugins is a real mess.
