### ISSUE TITLE
Metrics for ephemeral and batch jobs

### ISSUE THREAD

**Issue by bertpersyn** [Jeffail/benthos#151]
I'd like to request a new metric type:

If benthos is not long running, I'ld like to push my metrics, eg: if I use benthos as an ephemeral/batch jobs

For prometheus: https://github.com/prometheus/pushgateway

What do you think?

**Comment by Jeffail** [comment]
Hey @bertpersyn, sounds reasonable, looks like the API would be a straight forward addition to the existing prometheus metrics target https://godoc.org/github.com/prometheus/client_golang/prometheus/push.

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/3030554577e72a096dd9bd40c12260517459f31a

@bertpersyn, would you be willing to test this?

**Comment by Jeffail** [comment]
Cool, please reopen if you find any issues.

**Comment by bertpersyn** [comment]
Hi jeffail! 

I've tested it and it works, thanks 👍 

The only remark I have: 

sometimes I deal with long running jobs and when using grafana&prometheus, it'ld be cool if we push metrics to the gateway in a periodic way. Would it be possible to introduce variable `push_interval: time` and use a go func() that pushes the already gathered metrics to the gateway? When benthos finishes, the final metrics could be pushed (like you do atm).

**Comment by Jeffail** [comment]
Hey @bertpersyn, yeah that seems reasonable.

**Comment by Jeffail** [comment]
@bertpersyn, I've added a field `push_interval` in v1.4.0 https://github.com/Jeffail/benthos/releases/tag/v1.4.0, can you give it a try?

**Comment by bertpersyn** [comment]
Hi!

I've got it up and running in k8s and the gateway receives the pushed metrics.

Question: is it possible to configure the job name ("benthos_push")?

```	return push.New(p.config.PushURL, "benthos_push").Gatherer(prometheus.DefaultGatherer).Push() ```

when closing and when interval hits?

Thanks in advance!

**Comment by Jeffail** [comment]
Hey @bertpersyn, would you want a different job name for interval pushes versus closing?

**Comment by bertpersyn** [comment]
Hi @Jeffail. 

I don't think there needs to be a difference between the two. The reason why I ask is when running multiple batch jobs at the same time (multiple k8s cronjobs/benthos pods), the name of the job should differ.

**Comment by Jeffail** [comment]
Cool, implemented: https://github.com/Jeffail/benthos/commit/1e1bbd3d43df20be0081ee7d83d00ff6e6d36c1e
