### ISSUE TITLE
Closeable interface

### ISSUE THREAD

**Issue by asiragusa** [Jeffail/benthos#155]
Every interface (`input.Type`, `output.Type`, `processor.Type`, etc.) uses the `types.Closeable` interface, this requires a lot of boilerplate for stateless services.

A possible improvement would be to remove the `types.Closeable` interface and to test the instance against that interface. An helper function would simplify this:

```golang
func CallCloseAsync(i interface{}) {
  if closeable, ok := i.(types.Closeable); ok {
    closeable.CloseAsync()
}
}
```
A similar helper method can be written for `WaitForClose`.

Another option would be to provide a mix-in that implements the empty methods, and so a stateless processor would be like this:

```golang
type MyProvider struct {
  types.Stateless
}
```

**Comment by Jeffail** [comment]
Hey @asiragusa, I would suggest the mixin option since it is an explicit declaration by implementers that they have considered the lifetime of their type and that it's not needed. We could potentially add this somewhere in the API docs, maybe in the comment on `types.Closable`.

**Comment by asiragusa** [comment]
Yep, that would do it :)

**Comment by Jeffail** [comment]
I ended up suggesting this approach in the comments https://github.com/Jeffail/benthos/blob/master/lib/types/interface.go#L129 but didn't go as far as writing an implementation as I think it's simple enough as an exercise to the user.
