### ISSUE TITLE
Websocket documentation duplicated

### ISSUE THREAD

**Issue by nuhamind2** [Jeffail/benthos#159]
Doc on websocket as input : [input websocket](https://github.com/Jeffail/benthos/blob/master/docs/inputs/README.md#websocket)
say the same thing with output : [output websocket](https://github.com/Jeffail/benthos/blob/master/docs/outputs/README.md#websocket)

While at it, does the ws input/output has configurable delimiter like stdin/stdout ?

**Comment by Jeffail** [comment]
Hey @nuhamind2, well spotted, thanks.

Fixed: https://github.com/Jeffail/benthos/commit/3e97c74f426b0989b29d9f2aa615be5623ac9044

The input is very basic and bundles discrete messages as they are flushed, but if you need to break down the contents by delimiters you might be able to do that with processors, depending on your goals.
