### ISSUE TITLE
redis list as input?

### ISSUE THREAD

**Issue by gardenia** [Jeffail/benthos#16]
Hi,

I can see there is a redis pubsub input but I'd really like to be able to use redis list semantics (rpush -> blpop etc) which would offer some resilence if the benthos process were not alive when a message was queued.

that way my application can just write to the redis list (rpush) and benthos would poll the list and then deliver it to any of the output plugins (e.g. kafka).  just like pubsub but with the greater resilence of the redis lists to protect from data loss.

What is your opinion?

Thanks

**Comment by Jeffail** [comment]
Hey @gardenia, it's a possibility. There's a few other inputs/outputs I'd want to implement first.

**Comment by Jeffail** [comment]
Hey @gardenia, it looked straight forward so I did it just now.
