### ISSUE TITLE
Support for custom Processors, Inputs and Outputs?

### ISSUE THREAD

**Issue by ekarlso** [Jeffail/benthos#164]
Can this be done without having to pass my inputs into the benthos project itself?

**Comment by Jeffail** [comment]
Hey @ekarlso, yes but the documentation for plugins isn't in a good place quite yet. There's an example repo of an input plugin here: https://github.com/Jeffail/benthos-plugin-example, and processors and outputs are basically the same API.

You can either compile your own version of Benthos with your plugins compiled in, or alternatively you can compile your plugins as a Go plugin and link Benthos to it. There's an open ticket containing some ways of doing this with docker here: https://github.com/Jeffail/benthos/issues/148

**Comment by ekarlso** [comment]
But can I load it in when configuring benthos via pure go code instead of yaml ?

**Comment by Jeffail** [comment]
Sure, in that case you would do something like:

``` go
inputConf := input.NewConfig()
inputConf.Type = "your_custom_type"
```

When using the stream API: https://godoc.org/github.com/Jeffail/benthos/lib/stream

**Comment by ekarlso** [comment]
@Jeffail I tried this 
I build the plugin, I copy the influx_output.so to /usr/lib/benthos/plugins 

I have configured 
	influxOutConf := output.NewConfig()
	influxOutConf.Type = "influx"

And then I just "go run" my program and it crashes with 
panic: output type was not recognised

goroutine 1 [running]:
main.main()
	/home/ekarlso/projects/backend/cmd/streamer/main.go:57 +0x591
exit status 2

**Comment by Jeffail** [comment]
Hey @ekarlso, if you're using Benthos as a framework and you're defining your own `main` function then you don't need to use Go plugins, just include the code for your custom components and they will be compiled in. You only compile components to a `.so` file if you want to include them in a prebuilt version of Benthos.

In your main function have an include like this:

``` go
import (
    _ "path/to/your/plugin/package"
)
```

**Comment by ekarlso** [comment]
@Jeffail but how do you configure the plugin then ?

**Comment by Jeffail** [comment]
It depends on how you've written your plugin, but usually it would be something like this:

``` go
plugConf := yourplugin.NewConfig() 
plugConf.Foo = "bar"

influxOutConf.Type = "influx"
influxOutConf.Plugin = plugConf
```

**Comment by ekarlso** [comment]
I've written it like the one you have in your example :)

**Comment by Jeffail** [comment]
Okay yeah in that case it's `influxOutConf.Plugin = plugConf`, the config field `Plugin` is an `interface{}` type that stands in for any type of config struct your component requires.

**Comment by Jeffail** [comment]
Closing this for now, feel free to reopen if you have more questions.
