### ISSUE TITLE
Input termination - Wait for acknowledgements to propagate

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#174]
During shutdown it's possible for input components to close before a message that's in transit has been acknowledged. This behaviour occurs here: https://github.com/Jeffail/benthos/blob/master/lib/input/reader.go#L213

If we completely remove the case for exiting on our close channel then we risk blocking this component indefinitely, which is a problem since it could prevent resource cleanup whilst running in streams mode. However, we also want to allow a grace period where the input layer waits for an acknowledgement before exiting.

**Comment by Jeffail** [comment]
Fixed: https://github.com/Jeffail/benthos/commit/9d72c1c3150de9887279d59a519edbd252e134ac
Released: https://github.com/Jeffail/benthos/releases/tag/v1.7.10

**Comment by fbretel-cn** [comment]
Did a quick test this morning with v1.7.10. Still had a few messages in excess. I'll try to re-compile with a greater flush timeout (5 seconds?) and debug further when I get a chance.

**Comment by Jeffail** [comment]
@fbretel-cn, are you able to share more information about your configuration?

**Comment by fbretel-cn** [comment]
Yes. So we run basic rabbitmq (3 nodes) and the kafka (1 node) instances in kubernetes. I start 4 benthos replicas with the [attached config](https://github.com/Jeffail/benthos/files/2957208/benthos.txt).

Messages are produced with:
```
for i in $(seq 8); do { /tmp/rabbitmq-perf-test-2.6.0.RC1/bin/runjava com.rabbitmq.perf.PerfTest --id perf-$i --uri amqp://guest:guest@rabbitmq-ha:5672  --exchange benthos-exchange-$i --queue benthos-$i --producers 1 --consumers 0 --predeclared --routing-key rk --use-millis --auto-delete false --pmessages 1000000 -c 500 & } ; done
```
In the middle of the run, I re-deploy all benthos instances in a RollingUpdate manner. As a result I got:
```
$ bin/kafka-run-class.sh kafka.tools.GetOffsetShell  --broker-list localhost:6667 --topic benthos --time -1
benthos:0:8000130
$ for i in $(seq 8); do http --auth guest:guest http://127.0.0.1:15672/api/queues/%2F/benthos-$i | jq .message_stats.publish ; done | awk '{s+=$1} END {print s}'
8000000
$ for i in $(seq 8); do http --auth guest:guest http://127.0.0.1:15672/api/queues/%2F/benthos-$i | jq .message_stats.ack ; done | awk '{s+=$1} END {print s}'
7998437
```

**Comment by Jeffail** [comment]
Thanks @fbretel-cn, I tried reproducing this with a simplified version of your config but failed. I'm not sure when I'll get time to dig deeper but I suspect this is unrelated to the termination logic within `reader.go` so I'm going to close this ticket.

Obviously this is still an issue for you and I'd like to find out more about what's happening so please update this ticket with any clues you find (log output might be useful) and if it looks like it is related I'll reopen, if it's unrelated then we can open a new ticket once we know more.
