### ISSUE TITLE
Question: Concurrent Processing Support

### ISSUE THREAD

**Issue by freedombird9** [Jeffail/benthos#179]
I wonder how does it support concurrency? 

I'm browsing the source code and find that it just creates a list of workers whose number is equal to the number of threads in the config and then loop through them one by one to do the processing.  It  actually just starts one more goroutine, not multiple goroutines.

Basically I have a use case that a consumer needs to consume messages from upstream Rabbitmq and write results to db. It needs high performance, at least several dozens of goroutines to read the MQ concurrently. I wonder if I need to construct the benthos pipeline in multiple goroutines myself?

**Comment by Jeffail** [comment]
Hey @freedombird9,

The parallel processing is handled for you, here's where each processor worker gets constructed: https://github.com/Jeffail/benthos/blob/master/lib/pipeline/pool.go#L52, that constructor kicks off and manages its own goroutine for processing. This loop here: https://github.com/Jeffail/benthos/blob/master/lib/pipeline/pool.go#L120 is where incoming transactions are allocated to processing threads as they become available.

There's a guide here on how to utilize these parallel processing threads from your config: https://github.com/Jeffail/benthos/blob/master/docs/pipeline.md, for AMQP you'd want to use the second pattern.
