### ISSUE TITLE
Failed to delete consumed SQS messages

### ISSUE THREAD

**Issue by asiragusa** [Jeffail/benthos#182]
I get the following error on the SQS input:

```
Failed to delete consumed SQS messages: AWS.SimpleQueueService.BatchEntryIdsNotDistinct: Id 34376646-2fb8-4131-ba1c-d2db2f0060cc repeated.
	status code: 400, request id: 0c4b21eb-174f-5ae3-a3b3-74ccbad399b1
```

when one of the processors or outputs returns an error response (`response.NewError`). Moreover the Acknowledge function does not take into account such errors and voids the at-least-once guarantee. Instead of deleting the message, the visibility timeout should be set to 0, as the doc states: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html#terminating-message-visibility-timeout

**Comment by Jeffail** [comment]
Hey @asiragusa, thanks for raising this.

Looks like I wrapped the input with a preserver https://github.com/Jeffail/benthos/blob/master/lib/input/sqs.go#L51, which should preserve ALO but isn't idiomatic use of SQS. When an error occurs the input retries the same SQS message until success, but if that loop lasts longer than the visibility timeout we'll end up with the same message consumed multiple times, which potentially breaks the batch deletes once the error loop ends (duplicate IDs in the batch request).

I'll try and get a fix out today.

**Comment by Jeffail** [comment]
Fixed: https://github.com/Jeffail/benthos/commit/2512b42bdbd7c8d91842e4f259093be66b3e608e
Released: https://github.com/Jeffail/benthos/releases/tag/v1.10.10

@asiragusa, I've reproduced the issue and tested the fix with a relatively low volume queue, but we don't use this consumer in production so I don't have a heavy load to throw at it. If you still get problems please reopen this ticket and I'll do some heavier testing.

**Comment by asiragusa** [comment]
Cool, thanks!
