### ISSUE TITLE
Env Vars For Streams API

### ISSUE THREAD

**Issue by kconwayatlassian** [Jeffail/benthos#189]
When using Benthos in the standard mode it will load a configuration file and inject environment variables into placeholders matching the `${}` pattern. However, this only happens as a part of `main.go` and only if the configurations are provided at startup time ( <https://github.com/Jeffail/benthos/blob/master/cmd/benthos/main.go#L228> ).

When running the service in "streams" mode, the configurations are accepted by the HTTP server which uses a different set of methods to parse and sanitize the configuration. ( <https://github.com/Jeffail/benthos/blob/master/lib/stream/manager/api.go#L230> ) The net result is that the streams API does not inject environment variables.

It seems like it would be easy enough to add a call to `text.ReplaceEnvironmentVariables` in streams but wanted to get your opinion of where/how this should be done or if you meant for streams to have this feature as unsupported.

**Comment by Jeffail** [comment]
Hey @kconwayatlassian, I left this out originally as I wanted time to see how streams mode would be adopted (if at all), but I have no problem with adding it in. I'm happy to take a pull request.

Also, if you're able to share details about how you're making use of it I'd be very interested to hear.

**Comment by kconwayatlassian** [comment]
Happy to share the use case.

Some of the systems my team is using with Benthos have deployments managed on EC2 instances using some internal, company tooling. A deployment of a new version of a stream processing service roughly equates to generating a new auto-scale group of EC2 with the new code. There is a system that tracks which auto-scale groups are "active" or "inactive" for a given logical system and sends signals to instances within each group as they change states.

We leave old versions (and their full auto-scale groups) around for a while after a new version is deployed because this model for managing resources tends to be a bit slow and we want to be able to quickly roll-back a bad version. In the cases where we have two or more versions "warm" we have an issue where all versions are still consuming events from their target streams because we don't have a way of selectively targeting the Benthos containers with a signal when a version becomes "inactive" and we don't have a way to restart that one container if/when the version becomes "active" again due to a rollback. This isn't necessarily a problem but it is far less than optimal for us given the amount of time we keep versions warm.

Our solution, which is still going through testing, is to run Benthos is "streams" mode and adapt our "active"/"inactive" events into POST/DELETE calls to the streams API. The end result is that "inactive" versions stop consuming from a stream until they are reactivated. The transition is fairly straightforward since the streams API consumes the same YAML documents as the default Benthos runtime. The one exception has been the env var injection which we are currently emulating in our service that adapts internal events to Benthos calls.

I'll get a PR up that adds it to streams and see what you think.

**Comment by Jeffail** [comment]
Very interesting, thanks for sharing!
