### ISSUE TITLE
Adding link to jaegertracing.io

### ISSUE THREAD

**Issue by spier** [Jeffail/benthos#197]
I read the documentation about [Tracer Types](https://github.com/Jeffail/benthos/blob/master/docs/tracers/README.md
), and was wondering if it would be useful to link to https://www.jaegertracing.io, so that readers know exactly which tool you are talking about?

Further from our conversation I recalled that all docs are generated from the code.
So say I wanted to add the link mentioned above, would I have to change the *header* in `lib/tracer/constructor.go`?

**Comment by Jeffail** [comment]
Hey @spier, each implementation within the `tracer` package has its own snippet of documentation at the top, so for the Jaeger section you would want to edit this string: https://github.com/Jeffail/benthos/blob/master/lib/tracer/jaeger.go#L40

Once that's done if you have Go installed you can regenerate the documentation within the `./docs` directory with `make docs`.
