### ISSUE TITLE
Should batch processor emit the batch on AsyncClose()?

### ISSUE THREAD

**Issue by iluminae** [Jeffail/benthos#216]
Calling `Stop()` on the stream will try to drain the pipeline - but if you use a `batch` processor type, it could be holding messages that cannot be flushed, as no message coming into the batch will trigger {time, messages, messagesize} limits.

If there was a way that the batch could emit its held message without having a input message trigger that send - the `CloseAsync()` call could force the `batch` the emit its messages. Also, the time based emit could take advantage of this as well, and emit asynchronously.

Similarly, being able to specifically Noack the previously Unack'd messages on shutdown would also help my case of my input source only redelivering messages that have not been acked after a time expiry (gcp_pubsub).

**Comment by Jeffail** [comment]
Hey @iluminae, I'm trying to gradually migrate towards batches configured at the input layer (https://docs.benthos.dev/inputs/#kafka_balanced `max_batch_count` for example) as it avoids this issue entirely. The problem with a `batch` processor is that if we emit messages asynchronously then we have no mechanism for propagating the acknowledgements back to the input layer.

We could probably do the noack for unacked messages on shutdown though and that sounds like a good suggestion to me. I'll need to think through the implications but we can implement this on an input by input basis.

I can take a look at adding a `max_batch_count` field for the `gcp_pub_sub` input for you as that should solve your problems with unacks, would that work for you?

**Comment by iluminae** [comment]
@Jeffail in general I like your direction with that - although the settings of {time, size, #messages} seems more flexible than just `max_batch_count` available in eg: kafka_balanced.

I wonder if there is a pattern we can develop that integrates a common interface for attaching this batching functionality to inputs? Like attaching a buffer to a input as a child in a way that the input can use the buffer like we want, but the buffer can be pluggable and configurable?

**Comment by Jeffail** [comment]
We possibly could but the implementation needs to sit within the input implementation itself otherwise we hit similar problems.

I think for now having `max_batch_count` on inputs as well as the option for the `batch` processor covers most use cases. If you need the throughput of batches but also need flushed messages on shutdown then use `max_batch_count`, if you need granular batch controls like timing and can live with unacks use `batch`.

**Comment by Jeffail** [comment]
@iluminae, I've added the field `max_batch_count` to the `gcp_pubsub` input, that gives you a batching option that always results in flushed messages. Batching is always going to be a work in progress but I'm closing this issue for now, feel free to reopen if you have questions or problems with the new field.

**Comment by Jeffail** [comment]
Hey @iluminae, just as a follow up, I've refactored batching in Benthos in v3.3.0, it's now much more flexible (for all inputs): https://docs.benthos.dev/batching/
