### ISSUE TITLE
minio and SQLSelect

### ISSUE THREAD

**Issue by ghost** [Jeffail/benthos#222]
I would like to use this with minio and SQLSelect.
SQLSelect is pretty nice as it allows you to query data inside a minio bucket using just SQL.
Because its just SQL it more in line with the benthos approach of configuration rather than writing imperative code.

Here is their code that acts as a "gateway" in that you can use simple CURL like calls.
https://github.com/minio/minsql

It supports both querying and also mutations into Minio.
It also supports positional queries, which means it has Queue like semantics. I am testing it out as a queue.

From what i can understand the backend is here:
https://github.com/minio/minio/tree/master/pkg/s3select

**Comment by Jeffail** [comment]
Hey @gedw99, I don't really know much about Minio but if it has an HTTP API then you can just use the `http` processor and `http_client` input and outputs to interact with it.

**Comment by Jeffail** [comment]
Hey @gedw99, have you had a chance to try this out at all?
