### ISSUE TITLE
Panic on YAML unmarshal

### ISSUE THREAD

**Issue by andreis** [Jeffail/benthos#239]
Error

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4c4cd07]

goroutine 1 [running]:
gopkg.in/yaml%2ev3.handleErr(0xc0005787d8)
	/Users/andreisimionescu/go/pkg/mod/gopkg.in/yaml.v3@v3.0.0-20190502103701-55513cacd4ae/yaml.go:276 +0x9a
panic(0x55883a0, 0x6d99fd0)
	/usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:522 +0x1b5
github.com/Jeffail/benthos/lib/processor.(*Config).UnmarshalYAML(0xc00040cc00, 0xc00023e1e0, 0xc00040cc00, 0xba91098)
	/Users/andreisimionescu/go/pkg/mod/github.com/!jeffail/benthos@v0.0.0-20190522104139-ab5df3141333/lib/processor/constructor.go:312 +0x6a7
[...]
```

[Gist with error and config](https://gist.github.com/andreis/0c059e470ab24a3b83b736c689164c02)

After some sleuthing it turns out it could be because of the yaml lib update.

I discovered by accident that it does not panic if the plugin name is invalid, and returns an error as expected.

```
{"@timestamp":"2019-07-29T11:01:49+01:00","@service":"benthos","level":"ERROR","component":"benthos","message":"Service closing due to: failed to create processor 'customer-platform-application-wrong': processor type was not recognised"}
{"@timestamp":"2019-07-29T11:01:49+01:00","@service":"benthos","level":"INFO","component":"benthos.input","message":"Receiving HTTP messages at: http://localhost:7080/applications"}
```

**Comment by Jeffail** [comment]
Hey @andreis, thanks for the panic dump, are you providing a nil config constructor along with the plugin spec? If so I think this looks like an issue that should be fixed since [2.8.0](https://github.com/Jeffail/benthos/blob/master/CHANGELOG.md#280---2019-06-24). If not then is it possible to provide some information about your plugins config structure?

**Comment by andreis** [comment]
See email

**Comment by Jeffail** [comment]
Hey @andreis, were you able to try this after upgrading?

**Comment by andreis** [comment]
Hi @Jeffail I'm not associated with @utilitywarehouse anymore, you might want to ask @thinktainer. Thanks
