### ISSUE TITLE
MQTT clean session option

### ISSUE THREAD

**Issue by woosteln** [Jeffail/benthos#245]
Would love to see a config option for an mqtt clean session on the mqtt input.

Currently, though unlikely, there's a risk of dropped messages.

Would be happy to fork and PR myself if this gets a go-ahead.

**Comment by Jeffail** [comment]
Hey @woosteln, my understanding of MQTT is only rudimentary, could this be a simple configuration flag or would it need to be a more fundamental change (perhaps a separate input type altogether)?

Either way it sounds like a good fit for Benthos, if you'd be willing to put a PR together that would be awesome.

**Comment by woosteln** [comment]
From scanning the code, I think it would just be adding a config option and applying that option in creating the client.

I'll see what I can do.

BTW. Only ever hosted PRs on github, is only way to contribute one to fork first?

**Comment by Jeffail** [comment]
Sounds good. Yeah you create a fork to your account, push your changes to that fork, then you'll be able to submit a PR to this repo.

**Comment by woosteln** [comment]
Done. https://github.com/Jeffail/benthos/pull/246

Great job on this by the way!

**Comment by Jeffail** [comment]
Released: https://github.com/Jeffail/benthos/releases/tag/v2.11.2
