### ISSUE TITLE
Question: Serverless distribution with custom plugins?

### ISSUE THREAD

**Issue by benbooth493** [Jeffail/benthos#251]
What is the correct way to build the Lamda distribution while using a custom plugin?

**Comment by Jeffail** [comment]
Hey @benbooth493, to get something exactly similar to the official build you need to copy the contents of https://github.com/Jeffail/benthos/blob/master/cmd/serverless/benthos-lambda/main.go to a file and include your plugin imports, then build it with:

```sh
GOOS=linux go build ./yourfile.go
```

The copy/paste is a bit annoying so I'll flag this issue under documentation and look into making it simpler, with an example in the https://github.com/benthosdev/benthos-plugin-example repo.

**Comment by Jeffail** [comment]
Got it simplified in this commit: https://github.com/Jeffail/benthos/commit/dad5d08eae97f65e7f2328fc296968fc83d6233b

I'll add an example to https://github.com/benthosdev/benthos-plugin-example next.

**Comment by Jeffail** [comment]
Updated the benthos-plugin-example with the required instructions: https://github.com/benthosdev/benthos-plugin-example#serverless

**Comment by benbooth493** [comment]
Excellent! Thanks for the info.

**Comment by Jeffail** [comment]
API changes released: https://github.com/Jeffail/benthos/releases/tag/v2.12.0
