### ISSUE TITLE
Support grok pattern definitions

### ISSUE THREAD

**Issue by ilyaglow** [Jeffail/benthos#252]
At the moment benthos doesn't support custom pattern definitions, it has only [default ones](https://github.com/trivago/grok/blob/master/patterns.go#L5).

It would be useful if we can specify our specific definitions to use in grok patterns.

**Comment by Jeffail** [comment]
Merged, but I'd like to fix https://github.com/Jeffail/benthos/issues/257 before I make a release, might need to wait until tomorrow as I need sleep and (subsequently) sugar.
