### ISSUE TITLE
Create new, dedicated directory for release packages

### ISSUE THREAD

**Issue by torandu** [Jeffail/benthos#256]
Hi Jeff. This is a suggestion for enhancement to the release package. The tarball unpacks into the current directory and risks overwriting files and directories with the same names. It's also a bit of a hassle to clean up. Suggest using a dedicated directory, e.g. in the case of `benthos_2.11.2_linux_amd64.tar.gz`, it should unpack to `benthos_2.11.2_linux_amd64`. Thanks!

**Comment by Jeffail** [comment]
Hey @torandu, this seems reasonable. I'm not sure whether something like this ought to be reserved for a major version bump as it would impact any install scripts others have made, so best be on the safe side.

I'm going to tag this as an improvement for V3, if anyone has any thoughts or counter-proposals in the meantime please reply here.

**Comment by Jeffail** [comment]
Hey @torandu, just realised I missed this during the V3 release (it was a bit of a rush due to Go modules). I'm planning to start scraping stats about downloads and maybe based on that I can see how large of an impact this change would be.

**Comment by Jeffail** [comment]
Hey @torandu, I'm realising there's already quite a lot of build systems relying on the current format and that changing it is going to create a fair amount of friction even if we wait for a major version release. I'm going to close this ticket for now but if there's more demand for change then I'll revisit.
