### ISSUE TITLE
output to a raw L4 socket 

### ISSUE THREAD

**Issue by DpoBoceka** [Jeffail/benthos#258]
Hi! I accidentally created a regular syslog message out of my json using "text" processor and some hardcore magic like that:
```
  - text:
      operator: set
      value: "${!timestamp_utc} ${!json_field:Hostname}: ${!content}"
```
But now I have a great desire to feed such log to my perfect system which, alas, understands only syslog messages (hence my magic tricks).
Is it possible at the moment to perform so with some already written output module or my need is completely out of order and I should immediately cease such nonsense?

**Comment by Jeffail** [comment]
Hey @DpoBoceka, not currently unless you pipe Benthos stdout output to something like netcat. However, I'm definitely not opposed to adding `tcp` and `udp` inputs and outputs to Benthos.

**Comment by Jeffail** [comment]
Work in progress but I've added tcp and tcp_server inputs: https://github.com/Jeffail/benthos/commit/b09155a64f6dc32e2b5ea3a97ca611fe6418373a

**Comment by Jeffail** [comment]
Hey @DpoBoceka, in [v2.14.0](https://github.com/Jeffail/benthos/releases/tag/v2.14.0) I've added a bunch of tcp and udp inputs and outputs. I'll probably stop there unless you have a specific need that isn't yet met, in which case feel free to reopen this ticket.
