### ISSUE TITLE
Batch processor with NSQ

### ISSUE THREAD

**Issue by meganfeichtel** [Jeffail/benthos#262]
In your documentation, you are clear that the "batch" processor should always be put in the input section of the yaml file: 

![Screen Shot 2019-08-23 at 9 12 21 AM](https://user-images.githubusercontent.com/19913408/63595139-38c16a00-c586-11e9-90df-e4265dee1b24.png)

However, my team is using the NSQ input type, trying to batch messages into an s3 bucket in 5 minute intervals. We noticed that placing the "batch" processor in the input section of our process, the messages were not being acked properly off of nsq (they need to be acked within 1 minute of being retrieved or else the request will timeout, but they won't get acked until after the input block with benthos). 

We moved the "batch" processor to the first block in the pipeline section of our process, and it appears that everything is working smoothly, both the inputs from nsq, as well as the rest of our processors in the pipeline section.

I'm wondering if maybe this warning is misleading for some of the input options that benthos allows, since we are producing correct results even though we're going against the warning.

**Comment by Jeffail** [comment]
Hey @meganfeichtel, doing it that way will also potentially result in duplicate messages when you restart Benthos (im assuming.you have multiple consumers). If you dont need strict delivery guarantees then you could put in a small memory buffer which would decouple the input from the processing pipeline entirely.

I'll update the docs to explain it, and look into whether it's possible to skip the lint error when a buffer is present as it's irrelevant at that point anyway.

**Comment by Jeffail** [comment]
Hey @meganfeichtel, I haven't put out a release yet but I've added functionality to the memory buffer that allows you to set a batch policy: https://github.com/Jeffail/benthos/tree/master/docs/buffers#memory

This is more powerful than the batch processor as it ensures that the batches get flushed at the period even when the input stream is stalled, and it's a good way of decoupling the input from your pipelines. I've also updated the docs.
