### ISSUE TITLE
Support publishing to Amazon SQS FIFO

### ISSUE THREAD

**Issue by AdamGlazerMW** [Jeffail/benthos#269]
Publishing to FIFO Amazon SQS queues take 2 additional message parameters not covered in message attributes: **MessageGroupId** which is required and **MessageDeduplicationId** which is optional. 

Benthos would benefit from being able to parse metadata with this specific key name as these special message options when publishing to SQS.

**Comment by Jeffail** [comment]
@AdamGlazerMW, implemented: https://github.com/Jeffail/benthos/commit/8e2c7cdf08d1ab91b3961098d3200ba318818c2c
