### ISSUE TITLE
SQS ChangeMessageVisibilityBatch error code not logged

### ISSUE THREAD

**Issue by zlozano** [Jeffail/benthos#273]
In our application, we are seeing occasional errors like:
Failed to change consumed SQS message '0xc0005266e8' visibility, response code: 0xc0005267a8

These look to be emitted here: https://github.com/Jeffail/benthos/blob/master/lib/input/reader/amazon_sqs.go#L233

Since only the pointer value is getting logged, there is not enough information to diagnose what is happening. I am opening this issue to improve the log line emitted to include the string value of the response code.

Note: I believe this happens in a few other places too.

**Comment by Jeffail** [comment]
Hey @zlozano, this should be fixed in https://github.com/Jeffail/benthos/releases/tag/v2.15.1 and future v3 release candidates.
