### ISSUE TITLE
local Metrics drops labels

### ISSUE THREAD

**Issue by bigkevmcd** [Jeffail/benthos#279]
Hi,

I've been using metrics.Local for testing metrics from custom processors, we have a use-case for labels for a couple of fields...but...

https://github.com/Jeffail/benthos/blob/master/lib/metrics/local.go#L154

This drops the labels, and the raw stats that come through don't quite tell us enough.

Would you be open to a change to support labels on the `LocalStat` values?

**Comment by Jeffail** [comment]
Hey @bigkevmcd, sounds good. How would you imagine the resulting structure should look?

**Comment by Jeffail** [comment]
Released: https://github.com/Jeffail/benthos/releases/tag/v3.1.0
