### ISSUE TITLE
Add 'split' operator in 'json' processor

### ISSUE THREAD

**Issue by DpoBoceka** [Jeffail/benthos#287]
It would be lovely to implement splitting a text value` {"foo":"bar,baz,baq"}` in an array `{"foo": ["bar", "baz", "baq"]}` natively, with no hacks needed.

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/3fa144528054853d30fedaa691ce71bbbc0b3b9c
