### ISSUE TITLE
No Issue Question Only

### ISSUE THREAD

**Issue by gmonk** [Jeffail/benthos#294]
Greetings,

I'm wondering if Benthos would fit my use case. Currently I am sniffing raw traffic from a network and converting the interesting traffic payload into JSON and shipping via MQTT to the cloud for others to consume.  The issue is the data has a lot of repeat data that changes every minute or so along with data that changes every second that acts as counter. I would like to save bandwidth by only sending data that has changed along with the counter data that is needed. Is it possible with Benthos to dedup the changing data  while keeping the constantly changing data in the stream as well ?  Below is  an example of the data with the counter in bold which will count up from 1-120 and start over while the rest of the data will pretty much stay the same for about a minute or so then randomly change. 
Sorry this was so long :)

{"msgType":"ASC3","ctrlID":"5600","phaseReds":[1,2,3,5,6,7],"phaseGreens":[4,8],"phaseVehCalls":[2,3,4,6,7,8],"phasePedCalls":[2,4,6,8],"**coordSync":79,**"coordPattern":20,"localFree":2,"preemptState1":2,"preemptState2":2,"phaseWalks":[4,8],"ovlGroupReds":[1,2,3,4,5,6,7,8],"preemptState3":2,"preemptState4":2,"preemptState5":2,"preemptState6":2,"preemptState7":2,"preemptState8":2,"preemptState9":2,"preemptState10":2,"vehicleDetector1":[3,7],"vehicleDetector2":[9],"phaseReds2":[1,2,3,4,5,6,7,8]}

**Comment by Jeffail** [comment]
Hey @gmonk, sounds like that should be fairly straight forward, take a look at the documentation for the dedupe processor https://docs.benthos.dev/processors/#dedupe, you can access fields within the json document using function interpolations in the key field.
