### ISSUE TITLE
sync_response doesnt preserve initial headers

### ISSUE THREAD

**Issue by jcalonso** [Jeffail/benthos#301]
The `sync_response` output doesn't honor the original request headers when calling back the original HTTP input.

A sample config to reproduce this problem:
```
inputs:
  - http_server:
      path: "/test"

output:
  type: sync_response
```

Curl:
```
curl localhost:4195/test -d '{"key":"val"}' -H 'Content-Type: application/json' -v

*   Trying ::1:4195...
* TCP_NODELAY set
* Connected to localhost (::1) port 4195 (#0)
> POST /v1/annotate HTTP/1.1
> Host: localhost:4195
> User-Agent: curl/7.66.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 13
>
* upload completely sent off: 13 out of 13 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Date: Mon, 14 Oct 2019 19:35:02 GMT
< Content-Length: 13
<
* Connection #0 to host localhost left intact
{"key":"val"}% 
```

The `Content-Type` of the response is now `text/plain` instead of `application/json`.

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/6edec2ff473393bf458459080363a135e3c796b3

In the next release you can specify custom headers for the sync response, which also allows you to use function interpolations in the values based on the contents of the response payload:

```yaml
input:
  http_server:
    sync_response:
      headers:
        Content-Type: application/json
        foo: "${!json_field:foo}"
```

**Comment by jcalonso** [comment]
Awesome!, thanks @Jeffail
