### ISSUE TITLE
Permit customising successful response status in http_client output

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#302]
When using the `http_client` output, it considers every `2xx` response as successful, acking messages in the pipeline. However, it would be desirable to customise this behaviour, by adding additional response statuses that should be considered a "success".

Proposal:

Add `successful_on` field to the `http_client` output that lists additional status codes that are considered successful.

e.g.
```yaml
successful_on:
  - 409
```

**Comment by pkfiyah** [comment]
Bump, would also like this feature

**Comment by Jeffail** [comment]
This'll be in the next release.
