### ISSUE TITLE
Download file with URL encoded path from S3

### ISSUE THREAD

**Issue by edbrodrigues** [Jeffail/benthos#304]
When using S3 with SQS, the file path might be encoded as it is explained on the [documentation:](https://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html)

>The s3 key provides information about the bucket and object involved in the event. The object key name value is URL encoded. For example, "red flower.jpg" becomes "red+flower.jpg" (Amazon S3 returns "application/x-www-form-urlencoded" as the content type in the response).

In my situation I have a file that contains a datatime (eg: `foo_2019-10-21_13:30:00.log`) and the caracter `:` is sent to SQS as `%3A` (eg: `foo_2019-10-21_13%3A30%3A00.log`). For that reason benthos fails to download the object from S3. Is there a way to decode the URL ?

**Comment by Jeffail** [comment]
Hey @edbrodrigues, interesting. Should be quick to fix but I'll need to reproduce this locally.

**Comment by Jeffail** [comment]
Fixed: https://github.com/Jeffail/benthos/commit/e77ceb991acddcdafc57000c8c1ef224b092ef53
Released: https://github.com/Jeffail/benthos/releases/tag/v3.3.1
