### ISSUE TITLE
BigQuery support

### ISSUE THREAD

**Issue by thinktainer** [Jeffail/benthos#306]
Would you be open to accepting a [BigQuery](https://cloud.google.com/bigquery/docs/) output to benthos?

**Comment by Jeffail** [comment]
Hey @thinktainer, sure, sounds like a good fit.

**Comment by thinktainer** [comment]
Would it roughly follow the sql processor's mechanism in your mind, or is there something else you might want to bring my attention that would be better suited?

**Comment by Jeffail** [comment]
Something similar to the SQL processor would be great. Otherwise, just a cache implementation would be a good start and is probably much simpler to implement (but less useful).

**Comment by thinktainer** [comment]
Our use case revolves largely on the sink aspect, so was considering that as a first, if that's OK with you?

**Comment by Jeffail** [comment]
Sure, sounds good.

**Comment by thinktainer** [comment]
Our implementation of this ended up being fairly bespoke, so closing this.

**Comment by Jeffail** [comment]
Thanks @thinktainer, are there any other GCP components you'd be interested in having connectors for? I'm considering adding more as well as serverless functionality to the roadmap.

**Comment by lucasoares** [comment]
@Jeffail I think you should re-open this issue.

My data team uses bigquery a lot and this would be great to have as an output plugin!

Thanks

**Comment by Jeffail** [comment]
Sure!

**Comment by Jeffail** [comment]
Experimental support is in https://github.com/Jeffail/benthos/commit/85a4502b1680e8fb32c18849a261a65fc16bad5b
