### ISSUE TITLE
Empty benthos -version on v3.3.1

### ISSUE THREAD

**Issue by stephanebruckert** [Jeffail/benthos#310]
v3.2.0 was correctly giving:

```
✗ benthos -version
Version: 3.2.0
Date: 2019-10-11T04:49:51Z
```

but the latest v3.3.1 gives an empty version and date:

```
✗ benthos -version    
Version: 
Date: 
```

**Comment by Jeffail** [comment]
Hey @stephanebruckert, thanks for raising this, should be fixed in v3.4.0 and beyond.
