### ISSUE TITLE
Statsd metrics output shouldn't aggregate

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#324]
As noted in https://github.com/Jeffail/benthos/pull/317 the current library used for writing statsd metrics aggregates timings, which is breaking behaviour for some targets. We should either disable that behaviour or use a different library (https://github.com/smira/go-statsd). It might also be a good idea to make metrics targets pluggable like other components.

**Comment by Jeffail** [comment]
I took a quick look at https://github.com/smira/go-statsd and it actually supports datadog format tags, so potentially we could solve https://github.com/Jeffail/benthos/pull/317 by migrating to this library and adding a new config field `tag_format` which can be `none` (default), `influxdb` or `datadog`.

However, it doesn't look like you can send your metrics over TCP with this lib. I'm not sure if anyone is actually using statsd over TCP but I don't want to break backwards compatibility. Therefore we need to fall back to the current library if 'tcp' is specified as the `network` field. We should log when this is happening and error out if the `tag_format` field is used as well.

**Comment by assada** [comment]
I think it needs to be done a little differently.

For the "new" `datadog` metrics type, use https://github.com/smira/go-statsd
`tag_format` can have 3 meanings: `none`, `datadog`, `influxdb`
If `none` then tags are ignored.

If `metrics.type` = `datadog` and `network` = `tcp` then we trigger an error.
If `metrics.type` = `statsd` (legacy) and `tag_format` is not equal to `none` then we trigger an error.
