### ISSUE TITLE
Support TLS NSQ Input

### ISSUE THREAD

**Issue by jochavez** [Jeffail/benthos#333]
Currently our process has been running smoothly using Benthos but a new requirement has been added and we need support for TLS NSQ as input. 

The current [configuration for NSQ](https://docs.benthos.dev/inputs/#nsq) as an input does not give us the flexibility to pass in TLS options. 

Having support for this will increase security measurements and allow us to pass vulnerability tests. 

The current [NSQ config](https://github.com/Jeffail/benthos/blob/master/lib/input/reader/nsq.go#L56) could be updated and there could be a flag that if enabled could add on `tls_v1` and the `tls_config` [properties](https://godoc.org/github.com/nsqio/go-nsq#Config) that way we can pass the require parameters and TLS can be enabled. 

For example our current need would look like this: 
```
if c.EnableTLS {
    nsqConfig.Set("tls_v1", true)
    nsqConfig.Set("tls_config", &tls.Config{
        InsecureSkipVerify: true,
    })
}
```

Thank you.

**Comment by Jeffail** [comment]
Hey @jochavez, this should be quick to implement. I'll tackle the output at the same time.

**Comment by jochavez** [comment]
Thank you, for responding so quickly. Let me know if i can provide any more information.

**Comment by Jeffail** [comment]
Hey @jochavez, I've got this implemented https://github.com/Jeffail/benthos/commit/512eef3c85e594a05f600adb3ca749a812ead933, would you be willing to give this a try? Either you can build it from master yourself or I can get a release candidate out.
