### ISSUE TITLE
manager.RegisterPlugin usage example

### ISSUE THREAD

**Issue by surfeurX** [Jeffail/benthos#335]
Thanks for this awesome framework, I have some custom processors and I want to pass in a custom data layer plugin, similar to a cache plugin but with different methods. I saw that there is a `manager.GetPlugin` and `manager.RegisterPlugin` but I can't get it to work. The plugin is recognized when a add these settings but never initialized: 
```resources:
  plugins:
    myCustomPlugin:
      type: customPlugin
```

When I run the test command I get: 
plugin initialized: '"myCustomPlugin"'Test 'configs/ema_benthos_test.yaml' failed
  Example test case [line 3]:
    processors resulted in zero output batches

Any examples/ideas of how this can be implemented? 
Thank you

**Comment by Jeffail** [comment]
Hey @surfeurX, I'll add a working example to https://github.com/benthosdev/benthos-plugin-example, if you can give me more details about your processor implementation and the config you're running I might be able to spot the issue.

**Comment by Jeffail** [comment]
I've added an example manager plugin here: https://github.com/benthosdev/benthos-plugin-example/blob/master/manager/global_counter.go
And a processor plugin that uses the manager plugin: https://github.com/benthosdev/benthos-plugin-example/blob/master/processor/global_counter.go
And a config that uses them both: https://github.com/benthosdev/benthos-plugin-example/blob/master/config/example_2.yaml

**Comment by surfeurX** [comment]
Thanks a lot for the great example. 
I just figured out that I'm getting quite the same error when I try to run your example with `./benthos-plugin-example --streams --streams-dir config/`. (config folder containing example_2.yaml only)
```{"@timestamp":"2019-12-09T00:52:35-05:00","@service":"benthos","level":"ERROR","component":"benthos","message":"Failed to create stream (example_2): failed to create processor 'global_counter': failed to obtain resource 'total': plugin not found"}```
Otherwise it works great with `-c config/example_2.yaml`

**Comment by Jeffail** [comment]
Hey @surfeurX, when running in streams mode the resources have to be defined globally in a service level config and are shared across streams. Unfortunately that means they can't currently be mutated dynamically by the REST API. If that's blocking you I can look into adding CRUD endpoints for resources.

I've added a section to the docs to explain this and I'll paste it here:

## Resources

The `resource` section of a Benthos config defines named resources (`caches`,
`rate_limits`, etc) that can be referenced throughout a stream configuration.
When running in streams mode these resources are also shared across streams.

An individual stream config should not define any resources. Instead, they
should be defined in a service-wide config:

```yaml
resources:
  caches:
    foo:
      memory:
        ttl: 3600
```

```sh
benthos --streams -c ./config.yaml
```

This means it is not currently possible to modify resources dynamically. If this
is blocking you from using streams mode then consider
[raising a ticket](https://github.com/Jeffail/benthos/issues).

**Comment by surfeurX** [comment]
that makes sense @Jeffail! thank you so much for your help.
