### ISSUE TITLE
Config reloading

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#338]
It would be cool if Benthos was able to reload configurations without a restart. Initially this would simply involve stopping and starting the entire pipeline, but eventually we might be able to optimise it to avoid downtime entirely.

We should investigate the feasibility of using `SIGHUP` as a signal to reload config. We can also potentially add a REST endpoint. There's also the possibility of watching the config file for changes and reloading automatically (or based on a configured interval).

**Comment by Jeffail** [comment]
Went for the more difficult but more generally useful feature of watching for file changes: https://github.com/Jeffail/benthos/commit/4e741c2ca5914196ce143125ddcd68d1e4c8027f. To turn it on use the new `-w`/`--watcher` CLI flag.

This feature is marked as experimental for now but I'm closing this in favour of follow up issues for extra features and/or bugs.

**Comment by lorenz-qbees** [comment]
Great feature! Thanks @Jeffail 🙏
