### ISSUE TITLE
Kafka broker doesn't recover from failure to commit offsets

### ISSUE THREAD

**Issue by ollystephens** [Jeffail/benthos#342]
When using the `kafka` input, a failure to commit an offset causes the code to attempt to refresh the coordinator.
Unfortunately, it calls the Sarama client.Coordinator() method which, under the hood, uses a cache of the coordinator objects, so will return the same object. The benthos code then closes it (thinking it's closing the old one - not realising it's the same one).
The net effect of this is that it never recovers from the original error; all subsequent attempts cause an error "kafka: broker not connected".

The following PR fixes this by calling client.RefreshCoordinator() for force a refresh first.
It also checks to see if it is given the same one back (which can still happen) and makes sure it doesn't close it.

PR:
https://github.com/Jeffail/benthos/pull/341

Caveat:
Although this made things better for us, it didn't fully fix the issue we were having. We have now moved to using `kafka_balanced` which handles offsets differently, and we have somehow avoided our original issue this way. So whilst this PR is correct - I believe - I based it on the Sarama code used to manage offsets - it may only be a partial fix to a bigger problem, but I no longer have a testcase for that.

**Comment by Jeffail** [comment]
This will be in the next release candidate for v3.7.0.
