### ISSUE TITLE
Support setting S3 storage class

### ISSUE THREAD

**Issue by elundblad** [Jeffail/benthos#346]
It would be useful being able to set the 
`StorageClass` when putting objects to s3. Either as configuration for the entire output, or dynamically per object based on e.g. size.

My use case is that I have several benthos'es shoveling data to an s3 bucket where its structured using a date pattern prefix, and I'd like to transition some objects to infrequent access. 

Some benthos instances close to always put objects larger than 128kb, some always smaller, thus making it configurable per benthos should be good enough.

**Comment by Jeffail** [comment]
Hey @elundblad, sounds like a reasonable addition, should be able to get this in pretty easily.

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/e9f226cdd26b90861d55264a59f47007691ff840

@elundblad, I'm planning to put out a release candidate with this in soon, would you be willing to try it out?

**Comment by elundblad** [comment]
Of course

**Comment by Jeffail** [comment]
Release candidate out: https://github.com/Jeffail/benthos/releases/tag/v3.8.0-rc1

**Comment by Jeffail** [comment]
@elundblad had a chance yet to try it out? got a newer release candidate out: https://github.com/Jeffail/benthos/releases/tag/v3.8.0-rc2

**Comment by elundblad** [comment]
Yes, it works well. Thank you

**Comment by Jeffail** [comment]
Awesome, closing for now. Assuming no issues are found I'll release 3.8 later this week.
