### ISSUE TITLE
Restructure component docs

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#354]
Currently all implementations of a component type (inputs, processors, outputs, etc) have documentation residing in a single long document. These documents consist of a config example (containing all fields) and some text, the text _may_ describe the purpose of particular fields, but most are undocumented.

It would be nice to expand the documentation of a component such that we see a config snippet, a general description of the behaviour and purpose of the component, followed by a break down of each field with further details (where applicable).

In order to do that we certainly need to break out the docs for each component into their own page, otherwise we'll end up bloating the docs. We should therefore solve the following:

1. Doc pages per component implementation, and a `README.md` that lists them (in sections?) and provides component-wide advice.
1a. Should we also redirect `docs/inputs/README.md#foo` to `docs/inputs/foo.md`?
2. Per field documentation
3. Distinction between optional vs mandatory and common vs advanced fields
3a. Should we limit the config example to only common fields?

**Comment by Jeffail** [comment]
Got all this and more on a branch. It's an entirely new site, currently hosting off https://unruffled-spence-927f9b.netlify.com/ while I test links/formatting. I'd really appreciate feedback if anyone has time to try it out. It's already a lot better than the current docs site.

Eventually every component page will have per-field docs but it's a work in progress, I have a good number of inputs finished already.

**Comment by garbelini** [comment]
Awesome stuff!
Regarding 3a: I would prefer common fields only on examples.

**Comment by Jeffail** [comment]
I feel like the new site is pretty much all around better already, so even though the components docs haven't all been updated to give per-field info it's worth moving over. I've also added redirect rules to the new site so that the old documentation site paths will redirect to the correct sections.

Migration plan is as follows:

1. https://benthos.dev gets updated to new site and becomes the official docs moving forwards
2. https://docs.benthos.dev remains as is as a backup option
3. I'll monitor traffic and listen for feedback, if there are issues I'll postpone full migration until they're resolved
4. Finally, redirect https://docs.benthos.dev to https://www.benthos.dev in order to move over people with bookmarks and blog links

**Comment by Jeffail** [comment]
Currently at phase 3 of the plan. Nothing but positive feedback so far. If you've found issues please let me know, otherwise I'm moving to phase 4 this week.
