### ISSUE TITLE
Json (set) processor fails to handle emojis in `U+*` form

### ISSUE THREAD

**Issue by pkfiyah** [Jeffail/benthos#358]
The `json` processor throws this error:
"Failed to apply operator: failed to parse value: invalid character 'U' in string escape code"
when using the `operator: set` function upon encountering (some, potentially all) emoji's in `U+*` encoded format. 

Example problem string: "tweets are my own 🦄"

https://lab.benthos.dev/l/hvb0JvAysPH -> This doesn't show the error text but you can see the manipulation does not occur here as would be expected.

**Comment by Jeffail** [comment]
Interesting, I'll take a look.

**Comment by Jeffail** [comment]
Got it, the function interpolations weren't being correctly escaped. Fixed: https://github.com/Jeffail/benthos/commit/b28585d064448708de1ad9b2bda78701a9620954

I'll put a new release candidate out soon.
