### ISSUE TITLE
Comparision to Vector

### ISSUE THREAD

**Issue by mfzl** [Jeffail/benthos#359]
I'm not sure if this is the best place to ask this question, but here it goes.

Since the author @Jeffail is in Vector team too I wanted to ask what the differences are as I see both trying to achieve same thing. 

Do you have plans to make Benthos work with Vector (as a sink/source)?

**Comment by Jeffail** [comment]
Hey @mfzl, there's a lot of similarity in the projects but ultimately they have very separate goals and architectures.

Vector has a focus around observability data routing (specifically logs and metrics) where typically you need only a limited range of transformations and your top priority is performance (low memory footprint, high data throughput) and a wide range of connectors.

Benthos has a focus around stream processing events which _could_ be logs, metrics, etc, but could also be more enriched and with a higher delivery guarantee requirement (containing critical business logic). Therefore its top priority is powerful stream processing capabilities and strong delivery guarantees.

If you find that your use case aligns with both projects then you're in luck as I'm 100% dedicated to them both and that won't be changing any time soon.

**Comment by Jeffail** [comment]
Also it would be awesome to be able to embed Benthos processors within Vector or visa/versa but plugins within Vector currently aren't scoped out (although they should be implemented eventually) so I can't say for sure whether it'll be feasible.

**Comment by Jeffail** [comment]
Closing for now, I'll add a note in the benthos docs site if we get repeat questions.
