### ISSUE TITLE
Add flatten as a json operator

### ISSUE THREAD

**Issue by JohnRoesler** [Jeffail/benthos#362]
```json
{
  "a": "b", 
  "c": { "d": "e", "f": "g" },
  "h": [
    { "i": "j" },
    { "k": "l" }
  ]
}
```

becomes

```
{
  "a": "b",
  "c.d": "e",
  "c.f": "g",
  "h.0.i": "j",
  "h.1.k": "l"
}
```

Not sure on the best representation of arrays, but a feature that flattened the json would be valuable for outputting a fully nested json struct to a kafka .e.g and at the same time have a separate topic with a flat json output.

**Comment by Jeffail** [comment]
For arrays I would like to follow the same format as our field paths notation (json pointers with dots) https://www.benthos.dev/docs/configuration/field_paths

so

`{"foo":[{"bar":"one"},"two",{"baz":"three"}]}`

would become:

`{"foo.0.bar":"one","foo.1":"two","foo.2.baz":"three"}`

Also we should still follow the `path` field, so if the user specifies a non-root path then we only flatten that target.

**Comment by DpoBoceka** [comment]
Should `Gabs` adopt such function, so it could be reused in `Benthos`?

**Comment by DpoBoceka** [comment]
an issue's covered with https://github.com/Jeffail/benthos/commit/f9e6cb133f5e22f6766e3c5b30fd50a363339cb3
doc's updated, no examples given yet
https://www.benthos.dev/docs/components/processors/json#flatten_array

**Comment by JohnRoesler** [comment]
Thank you @Jeffail 👍
