### ISSUE TITLE
archive documentation improvement

### ISSUE THREAD

**Issue by JensRantil** [Jeffail/benthos#370]
https://www.benthos.dev/docs/components/processors/archive states

> For types that aren't file based (such as binary) the file field is ignored.

However, the example uses `format: binary` with `path`. How about updating the example to use something that requires `path`?

**Comment by Jeffail** [comment]
Hey @JensRantil, unfortunately I can't alter the config example as that shows the default values that are set, and therefore changing it would break backwards compatibility. However, I've added an examples section at the bottom which demonstrates tar archiving with path: https://www.benthos.dev/docs/components/processors/archive#examples
