### ISSUE TITLE
archive documentation doesn't say what "binary" means

### ISSUE THREAD

**Issue by JensRantil** [Jeffail/benthos#371]
https://www.benthos.dev/docs/components/processors/archive doesn't state was binary is. Will each message part simply be concatenated? Or is there some kind of enveloping happening?

**Comment by Jeffail** [comment]
Hey @JensRantil, thanks for the feedback. The format is outlined here: https://github.com/Jeffail/benthos/blob/master/lib/message/message.go#L113, but I'll add some context to the docs to make it clear.

**Comment by Jeffail** [comment]
I've added a formats section similar to other processor docs https://www.benthos.dev/docs/components/processors/archive#formats, which includes an outline of the binary spec.

**Comment by JensRantil** [comment]
Thanks!
