### ISSUE TITLE
Website: make docs secondary nav button more obvious

### ISSUE THREAD

**Issue by JensRantil** [Jeffail/benthos#372]
I wanted to open up the AWK documentation. AFAIK, there's no menu option for it. Could it be my resolution on my phone isn't high enough?

![Screenshot_20200208-120613](https://user-images.githubusercontent.com/730342/74084079-7732de80-4a6b-11ea-8812-387035b38df0.png)

**Comment by Jeffail** [comment]
Hey @JensRantil, thanks for the feedback. That small button in the bottom right opens a second menu for the documentation sections. I had the same conclusion as you when I first tried it out so this definitely needs some sort of action. I can at least alter its colours to make it pop out more.

**Comment by Jeffail** [comment]
I've made the button blue so it stands out more. Can't really tell whether it helps enough.

**Comment by JensRantil** [comment]
Much better! Super minor is that when I push that blue button now in my mobile it turns gray which looks like it behaves a little funky.
