### ISSUE TITLE
Default are really unclear in the documentation

### ISSUE THREAD

**Issue by JensRantil** [Jeffail/benthos#378]
I [just learnt](https://github.com/Jeffail/benthos/issues/370#issuecomment-583826089) that the first example on each component documentation page contains the default values. I had no clue it was such. In fact, I had planned to submit an issue that default values weren't documented but forgot about it until now... Could it be clarified that the first example contains the default value somehow? Or could they be presented in some other way?

**Comment by Jeffail** [comment]
Hey @JensRantil, I've added comments to the top of the config examples pointing out the values are the defaults. I've also added the default to the field specs at the bottom.

**Comment by JensRantil** [comment]
Excellent! 👏
