### ISSUE TITLE
Include error=true tag in IteratePartsWithSpan spans

### ISSUE THREAD

**Issue by seanlaff** [Jeffail/benthos#386]
Tools like jaeger highlight errors when this tag is set- thoughts about adding it to `IteratePartsWithSpan()`?

```diff
func IteratePartsWithSpan(
                }
                if err := iter(i, span, part); err != nil {
                        FlagErr(part, err)
+                       span.SetTag("error", true)
                        span.LogFields(
                                olog.String("event", "error"),
                                olog.String("type", err.Error()),
```

**Comment by Jeffail** [comment]
Sure, makes sense. Am I right in assuming this wouldn't be a breaking change in that it wouldn't break any existing set ups?

**Comment by seanlaff** [comment]
Correct, I can't imagine a scenario in which this would be a breaking change to an opentracing consumer.

Here's some context for the `error` tag, as well as some other common convetions
https://github.com/opentracing/specification/blob/master/semantic_conventions.md

**Comment by Jeffail** [comment]
Sounds like it's good to add. The span is local to the processor so the fact that the processing step itself failed, but the parent span of the overall pipeline hasn't, is represented well by this if I understand it correctly.
