### ISSUE TITLE
metrics dont appear accurate

### ISSUE THREAD

**Issue by GrantEdmunds** [Jeffail/benthos#390]
The metrics numbers I get from port 4195 are not accurate with the word counts of the output file!  What do I need to modify or change to get them accurate?

I'm testing Benthos in Docker.  When I launch Benthos in a docker container I want to be able to pole metrics by running 'curl -s 0.0.0.0:4195/metrics'.  When I look at the output of the json, the numbers don't agree with the word counts of the file I'm writing to.  

[root@pdehost-wc-3p benthos-3.8.0]# wc outputfile; curl -s 0.0.0.0:4195/metrics
   102008   1780049 112846651 outputfile
{"benthos":{"goroutines":10,"input":{"batch":{"received":2142374},"connection":{"failed":0,"lost":0,"up":1},"count":2142374,"latency":516470,"latency_readable":"516.47µs","received":2142374},"output":{"batch":{"bytes":110738318,"latency":456066,"latency_readable":"456.066µs","sent":2142374},"count":2142374,"sent":2142374},"uptime":"1m51.428606739s"}}[root@pdehost-wc-3p benthos-3.8.0]#

The current config is: 
input:
  file:
    path: "/input/infile"
    multipart: false
    max_buffer: 1e+06
    delimiter: ","

metrics:
  whitelist:
    paths:
      - input.received
      - input.count
      - input.batch.received
      - input.connection.up
      - input.connection.failed
      - input.connection.lost
      - input.latency
      - buffer.backlog
      - buffer.write.count
      - buffer.write.error
      - buffer.read.count
      - buffer.read.error
      - buffer.latency
      - pipeline.processor.0.count
      - pipeline.processor.0.sent
      - pipeline.processor.0.batch.sent
      - pipeline.processor.0.error
      - output.count
      - output.sent
      - output.batch.sent
      - output.batch.bytes
      - output.batch.latency
      - output.connection.up
      - output.connection.failed
      - output.connection.lost
    child:
      http_server:
        namespace: benthos

# Config fields, showing default values
output:
  file:
    path: "/output/outfile"
    delimiter: ","

**Comment by Jeffail** [comment]
Hey @GrantEdmunds, are you sure that Benthos has finished processing the file when you query the metrics? With that config I would expect Benthos to shut down once the input file is fully consumed, in which case it wouldn't be possible to use curl to get the final counts.

If you try out the [`stdout`](https://www.benthos.dev/docs/components/metrics/stdout) it'll print a definitive value when the service shuts down, that might help narrow this down.

**Comment by GrantEdmunds** [comment]
I realize with files, Benthos stops as soon as it reads the end of the input file.  But we want to test with Kafka as an input stream also.  So we’d like to know how many output records it has written to the output file, so we can shut it down after a certain amount.   The whole purpose is to test Logstash, with Benthos and Vector and any other log shippers to see which is faster and most efficient with the same inputs, cpus, memory, etc…!

Here’s what my python script does.

  1.  Take input parameters and initialize
  2.  Start dstat in the background
  3.  Launch benthos in docker container in background
  4.  Loop and read port 4195/stats (find the metric that says how many output records are written)

Or

Perform wc -l on output file.   (this isn’t very accurate because of buffer latency and long running when big!)

  1.  When number of records written reaches some level (input parameter) then terminate dstat, docker, and combine all information into output dir.

**Comment by Jeffail** [comment]
If you want to force Benthos to stay open after finishing the file you can add another input that stays open:

```yaml
input:
  broker:
    inputs:
    - http_server: {}
    - file:
        path: "/input/infile"
        multipart: false
        max_buffer: 1e+06
        delimiter: ","
```

The `http_server` input will keep this instance running and shouldn't add any overhead.

**Comment by Jeffail** [comment]
Closing for now, if you have more questions feel free to reopen.
