### ISSUE TITLE
Mongo support (processor or output)

### ISSUE THREAD

**Issue by inliquid** [Jeffail/benthos#393]
I have already mentioned in #391 that we have a task to make `benthos` work with Mongo. Ideally this would look like some specific `mongo` output which outputs processed data to configured collection(s). Having analogue to `sql` processor (so output will basically be set to `drop`), seems ok as well (but maybe not that perfect). Initially we thought about writing a plugin. But maybe there are some plans or work in progress already?

**Comment by Jeffail** [comment]
Hey @inliquid, I'd be happy to add mongo components. In this case it would fit as a `cache`, `processor` or `output`, but it sounds like for your use case something similar to the [`dynamodb` output](https://www.benthos.dev/docs/components/outputs/dynamodb) might be best.

I'm not aware of anyone else looking to implement mongo components. I'm happy to help out and review draft PRs if you need.

**Comment by nmbryant** [comment]
We have a need for a mongo cache and I was going to get started on implementing that. Should I do that as part of this issue or make a new issue specifically for a mongo cache?

**Comment by Jeffail** [comment]
> We have a need for a mongo cache and I was going to get started on implementing that. Should I do that as part of this issue or make a new issue specifically for a mongo cache?

Hey @nmbryant this issue is fine, it'd be useful if you gave details here around which client library you're using as we can reuse that knowledge when making a processor/output.

**Comment by Jeffail** [comment]
Done in https://github.com/Jeffail/benthos/commit/548033877e52f833d92a7c8d42228d2ea6e00cbb
