### ISSUE TITLE
interpreter error

### ISSUE THREAD

**Issue by YHYJ** [Jeffail/benthos#403]
I downloaded the benthos(linux/amd64), it couldn't run, because its interpreter was ”/home/linuxbrew/.linuxbrew/lib/ld.so“, without this file

The interpreter of benthos I compiled is /lib64/ld-linux-x86-64.so.2

![benthos.png](https://i.loli.net/2020/03/10/cRMDeojtQTxPXir.png)

**Comment by Jeffail** [comment]
Hey @YHYJ, sorry about this, the `linux_amd64` release binary was incorrectly dynamically linked. Should be fixed now.

**Comment by Jeffail** [comment]
Closing for now, please reopen if it's not resolved.
