### ISSUE TITLE
Multiple contains operator for text condition

### ISSUE THREAD

**Issue by DpoBoceka** [Jeffail/benthos#406]
I have many cases when I need to check wether the value of specific key contains one of many, could be 30+, given strings. At the moment it looks a bit nasty to use many `or` and there is an overhead since I need to call the same function as many times as many strings I have to check the value against.
We could add `multi_contains` operator to `text` condition which returns true if one of the given strings is found

**Comment by DpoBoceka** [comment]
We could also refactor the existing `contains` to work with `[]byte` and `[][]byte` simultaneously as `arg` filed is an `interface{}`
Should we keep in mind a use case when the user wants all given strings to be a part of a message it is checked against?

**Comment by DpoBoceka** [comment]
And I forgot the fact that `contains` of `json` condition is a better option now in my case so I would rather be keen to implement such functionality for it

**Comment by DpoBoceka** [comment]
After some second thought I'm not sure if it is a good idea, because I also need a multi `suffix`, so perhaps it isn't idiomatic enough..

**Comment by Jeffail** [comment]
Hey @DpoBoceka, we could add a `contains_any` operator, with a list arg similar to https://www.benthos.dev/docs/components/conditions/text#enum
