### ISSUE TITLE
Feedback Wanted: Unit Testing

### ISSUE THREAD

**Issue by DpoBoceka** [Jeffail/benthos#407]
What is the current state of Unit Testing? Is it design-flowed so far?
https://www.benthos.dev/docs/configuration/unit_testing

**Comment by Jeffail** [comment]
I'm fairly happy with it but there are some minor adjustments that might be worth considering. Let's aim to stabilize it in the coming months. I'll use this issue to throw ideas around.

Stuff worth considering:

- Do we want to keep the test filename as `<target>_benthos_test.yaml`? I'm thinking it's a pain and we can get away with `<target>_test.yaml`
- Do we want to consider allowing tests _within_ the target config?

**Comment by Jeffail** [comment]
Unit testing got a lot of love, I'll remove the EXPERIMENTAL flag from the docs next time I update it but I don't plan any future changes. The only optional improvement I might make is to be able to define tests within the target config itself, but I'm not convinced it would be a popular option as the test definitions very quickly become so large it wouldn't be practical.
