### ISSUE TITLE
AMQP TLS support

### ISSUE THREAD

**Issue by EdeMeijer** [Jeffail/benthos#42]
Hello,

I'm considering using Benthos for sending messages to remote tenants of a platform I'm developing. I'd like to offer public access to a RabbitMQ server, which the tenants can then consume the messages from using Benthos. However, in this scenario using a secure connection is critical in order to prevent the users from sending their RabbitMQ credentials over the public internet in plain text. 

RabbitMQ supports TLS, and so does the amqp library you're using, so it shouldn't be too hard to add a TLS feature to the amqp inputs / outputs I think. I might give it a shot myself if you don't have time for it right now once I start trying out Benthos, but I think this is something other users might appreciate as well.

Thanks!

**Comment by Jeffail** [comment]
Hey @EdeMeijer, done. https://github.com/Jeffail/benthos/commit/22c185dbcd393106b9d9cbb36f2cfd7372f917d5, I haven't got a TLS enabled server to test against so would be good if you could try it out and get back to me.

**Comment by EdeMeijer** [comment]
Wow, that's fast. I'll let you know when I get around to testing it, thanks.

**Comment by EdeMeijer** [comment]
I got a TLS secured RabbitMQ instance up and can access the management interface over HTTPS, so the certs are configured correctly on the server side. I tried settings up an amqp input with benthos but I'm getting a tls handshake failure. I'll send you an email with the details where you can find the server for testing and what I tried so far, just don't want to share that here.

**Comment by Jeffail** [comment]
Cool, sounds good, thanks @EdeMeijer

**Comment by EdeMeijer** [comment]
Okay, that was my bad. I had peer verification enabled but not configured. Benthos now happily consumes my test queue.

That raises the question though, is TLS peer verification supported by Benthos? That might be another good thing to test.

**Comment by Jeffail** [comment]
I believe you should be able to do peer verification by exporting your certs and pointing Benthos to them with the `tls.cas_file` field.

The exchange declaration and binding on the input should be a no-op if they already exist, but you're right that it's redundant. I can't exactly remember why I set it up this way originally but you're right to point it out, it's annoying to have to redundantly specify your exchange fields and binding when they should already exist. I'll take a look.

**Comment by Jeffail** [comment]
Moving declaration discussion over to https://github.com/Jeffail/benthos/issues/45, would be good to get your thoughts. Closing this issue.
