### ISSUE TITLE
Add support for Grok pattern definitions in external file(s)

### ISSUE THREAD

**Issue by itkovian** [Jeffail/benthos#424]
We have a lot of Grok patterns and we'd like to deploy the yaml file from our cfgmgmt system. It makes little sense to include the Grok patterns literally -- they are normal deployed using an RPM, we have tests etc for them.

Would it be possible to provide a `pattern_source` giving a directory (preferably) or file of patterns that should be included next to the default patterns?

**Comment by Jeffail** [comment]
Hey @itkovian, that's a reasonable addition. I've classed this as a bughancement as the current behaviour is odd and user hostile.

**Comment by itkovian** [comment]
Thanks!

**Comment by Jeffail** [comment]
Done https://github.com/Jeffail/benthos/commit/0b5664d5bf224f60032821c97ad27828f9423d18, planning to release later this week.
