### ISSUE TITLE
How to configure the db number used by `redis_list`

### ISSUE THREAD

**Issue by YHYJ** [Jeffail/benthos#426]
`redis_list` use the default db0, can i set the db number?

**Comment by Jeffail** [comment]
Hey @YHYJ, in version 3.12 this will be possible, you can get a release candidate from https://github.com/Jeffail/benthos/releases/tag/v3.12.0-rc3 and the syntax is to add a path at the end of the URL: `tcp://localhost:6379/2`

**Comment by YHYJ** [comment]
ok, thk!!
