### ISSUE TITLE
RunTime Error

### ISSUE THREAD

**Issue by kozelok** [Jeffail/benthos#428]
Hello,

I am facing an issue where benthos running on alpine is throwing errors.  Can you help?

[error.log.zip](https://github.com/Jeffail/benthos/files/4496050/error.log.zip)

**Comment by Jeffail** [comment]
Hey @kozelok, this only appears to be the last few lines of a crash dump, would it be possible to collect the rest of it? Also can you provide more details such as:

- which version of Benthos
- what kind of pipeline are you running
- how often does this crash occur

**Comment by kozelok** [comment]
@Jeffail  
Version: 3.11
Pipeline: Attached
Occurs: When threads is set to more than 1
[pipeline.log](https://github.com/Jeffail/benthos/files/4506117/pipeline.log)

**Comment by Jeffail** [comment]
Hey @kozelok, this still isn't enough information I'm afraid, I need the full crash dump (the original zip file you attached only has the last few lines), and ideally I need to know which processors you were running in your config.

I can maybe narrow this down with just a list of processors you were using if you aren't able to share the whole config, but I definitely need the full crash output otherwise there's no way for me to reproduce or analyze what has happened.

**Comment by kozelok** [comment]
oroutine 981 [select]:
github.com/Jeffail/benthos/v3/lib/input.(*AsyncReader).loop.func3(0xc0001741e0, 0xc0001fe140, 0x2d1e9c0, 0xc0005a22e0, 0xc000aac480, 0x2d67bc0, 0xc000c86e40, 0xc000c86ff0, 0xc0014f5b00)
	/Users/yevgeny.khessin/workspace/deviceGateway/mkproxy/vendor/github.com/Jeffail/benthos/v3/lib/input/async_reader.go:199 +0x115
created by github.com/Jeffail/benthos/v3/lib/input.(*AsyncReader).loop
	/Users/yevgeny.khessin/workspace/deviceGateway/mkproxy/vendor/github.com/Jeffail/benthos/v3/lib/input/async_reader.go:190 +0xcbd

goroutine 974 [select]:
github.com/Jeffail/benthos/v3/lib/input.(*AsyncReader).loop.func3(0xc000321fe0, 0xc000dc45a0, 0x2d1e9c0, 0xc000780fc0, 0xc000a1f1e0, 0x2d67bc0, 0xc001583b60, 0xc001583cb0, 0xc000da0ea0)
	/Users/yevgeny.khessin/workspace/deviceGateway/mkproxy/vendor/github.com/Jeffail/benthos/v3/lib/input/async_reader.go:199 +0x115
created by github.com/Jeffail/benthos/v3/lib/input.(*AsyncReader).loop
	/Users/yevgeny.khessin/workspace/deviceGateway/mkproxy/vendor/github.com/Jeffail/benthos/v3/lib/input/async_reader.go:190 +0xcbd
@Jeffail Please see below. 
goroutine 995 [select]:
github.com/Jeffail/benthos/v3/lib/input.(*AsyncReader).loop.func3(0xc000435440, 0xc0001fe280, 0x2d1e9c0, 0xc0005222c0, 0xc000a1e9f0, 0x2d67bc0, 0xc000b4c960, 0xc000b4cba0, 0xc0015a6960)
	/Users/yevgeny.khessin/workspace/deviceGateway/mkproxy/vendor/github.com/Jeffail/benthos/v3/lib/input/async_reader.go:199 +0x115
created by github.com/Jeffail/benthos/v3/lib/input.(*AsyncReader).loop
	/Users/yevgeny.khessin/workspace/deviceGateway/mkproxy/vendor/github.com/Jeffail/benthos/v3/lib/input/async_reader.go:190 +0xcbd

**Comment by kozelok** [comment]
Was able to track this down further. Looks like an issue with adding new metrics dynamically.

  - for_each:
    - metric:
        type: counter
        path: count.custom.field
        value: ${!metadata:topicMetric}
        labels:
          topic: "topic"

fatal error: concurrent map writes

goroutine 365 [running]:
runtime.throw(0x276b824, 0x15)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:1112 +0x72 fp=0xc001ac9928 sp=0xc001ac98f8 pc=0x1035e92
runtime.mapassign_faststr(0x2454e80, 0xc0005dfe30, 0xc000991670, 0x5, 0xc000680000)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc001ac9990 sp=0xc001ac9928 pc=0x10154f7
github.com/Jeffail/benthos/v3/lib/metrics.(*LocalStat).setLabelsAndValues(0xc0005f87c0, 0xc0009e6cd0, 0x1, 0x1, 0xc002c32270, 0x1, 0x1, 0x15f7bef)
        /Users/workspace/benthos/vendor/github.com/Jeffail/benthos/v3/lib/metrics/local.go:45 +0xad fp=0xc001ac99e8 sp=0xc001ac9990 pc=0x15f5bcd
github.com/Jeffail/benthos/v3/lib/metrics.(*Local).GetCounterVec.func1(0xc002c32270, 0x1, 0x1, 0x5d22398, 0xc000346900)
        /Users/workspace/benthos/vendor/github.com/Jeffail/benthos/v3/lib/metrics/local.go:219 +0xa2 fp=0xc001ac9a40 sp=0xc001ac99e8 pc=0x1603d12
github.com/Jeffail/benthos/v3/lib/metrics.(*fCounterVec).With(0xc000011980, 0xc002c32270, 0x1, 0x1, 0x2d1e880, 0xc002c32280)
        /Users/workspace/benthos/vendor/github.com/Jeffail/benthos/v3/lib/metrics/vector_util.go:10 +0x47 fp=0xc001ac9a78 sp=0xc001ac9a40 pc=0x1601397
github.com/Jeffail/benthos/v3/lib/metrics.(*combinedCounterVec).With(0xc000c3cb80, 0xc002c32270, 0x1, 0x1, 0xc00475d800, 0xc002c32270)
        /Users/workspace/benthos/vendor/github.com/Jeffail/benthos/v3/lib/metrics/combine.go:85 +0x9e fp=0xc001ac9ad8 sp=0xc001ac9a78 pc=0x15f285e
github.com/Jeffail/benthos/v3/lib/processor.(*Metric).handleCounter(0xc000b94000, 0x0, 0x0, 0x2d67ca0, 0xc00475d800, 0x2d333a0, 0xc00475d800)
        /Users/workspace/benthos/vendor/github.com/Jeffail/benthos/v3/lib/processor/metric.go:253 +0xa8 fp=0xc001ac9b28 sp=0xc001ac9ad8 pc=0x1881af8
github.com/Jeffail/benthos/v3/lib/processor.(*Metric).handleCounter-fm(0x0, 0x0, 0x2d67ca0, 0xc00475d800, 0x0, 0x0)
        /Users/workspace/benthos/vendor/github.com/Jeffail/benthos/v3/lib/processor/metric.go:251 +0x52 fp=0xc001ac9b70 sp=0xc001ac9b28 pc=0x18c64b2
github.com/Jeffail/benthos/v3/lib/processor.(*Metric).ProcessMessage(0xc000b94000, 0x2d67ca0, 0xc00475d800, 0x1, 0xc002c32220, 0x1, 0x1, 0x1)
        /Users/workspace/benthos/vendor/github.com/Jeffail/benthos/v3/lib/processor/metric.go:327 +0x73 fp=0xc001ac9bf0 sp=0xc001ac9b70 pc=0x1882293
github.com/Jeffail/benthos/v3/lib/processor.ExecuteAll(0xc0009e6cf0, 0x1, 0x1, 0xc002c32220, 0x1, 0x1, 0xc001ac9d40, 0x101616a, 0xc002c32210, 0xc002c321e0, ...)
        /Users/workspace/benthos/vendor/github.com/Jeffail/benthos/v3/lib/processor/util.go:25 +0x165 fp=0xc001ac9cb0 sp=0xc001ac9bf0 pc=0x18a3355
github.com/Jeffail/benthos/v3/lib/processor.(*ForEach).ProcessMessage(0xc000b921c0, 0x2d67ca0, 0xc00475d770, 0x1, 0xc002c321e0, 0x1, 0x1, 0x1)
        /Users/workspace/benthos/vendor/github.com/Jeffail/benthos/v3/lib/processor/for_each.go:149 +0x171 fp=0xc001ac9d50 sp=0xc001ac9cb0 pc=0x186dd01
github.com/Jeffail/benthos/v3/lib/processor.ExecuteAll(0xc000bb3920, 0x3, 0x3, 0xc001d30ea0, 0x1, 0x1, 0xc00496ea20, 0x1, 0x1, 0x0, ...)
        /Users/workspace/benthos/vendor/github.com/Jeffail/benthos/v3/lib/processor/util.go:25 +0x165 fp=0xc001ac9e10 sp=0xc001ac9d50 pc=0x18a3355
github.com/Jeffail/benthos/v3/lib/pipeline.(*Processor).loop(0xc0000eaab0)

**Comment by Jeffail** [comment]
Thanks @kozelok! That should be all I need, and I'll try and reproduce and get a fix out soon.

**Comment by Jeffail** [comment]
Hey @kozelok, reproduced and (I believe) this is fixed now. I'll put a new release out tomorrow evening.
