### ISSUE TITLE
Kinesis partition_key re-used?

### ISSUE THREAD

**Issue by kostas-theo** [Jeffail/benthos#431]
We are using the kinesis output and using the interpolation `${uuid_v4()}` as the partition_key. In the case where we need to make multiple PutRecords calls to kinesis, is the same partition_key used for successive calls or are new uuids generated?

**Comment by Jeffail** [comment]
Hey @kostas-theo, the UUID will be generated once per record sent. If a send request fails for a record then it will be reattempted with the same UUID. Also there's a typo in your example, it should be `${!uuid_v4()}` (with a ! at the beginning of the expression).

**Comment by Jeffail** [comment]
Closing for now, if you have any follow up questions feel free to reopen.
