### ISSUE TITLE
kafka_balanced input left with zombie consumers when broker terminates connection

### ISSUE THREAD

**Issue by andrewjmurphy** [Jeffail/benthos#433]
Following a timeout with zookeeper kafka brokers will remove connected consumers from their consumer group:

```[2020-04-27 15:24:50,492] INFO [GroupCoordinator 120]: Member d1ab40db-ab13-4b75-b73c-9fafb9580d0b in group xxxxxxxxxx has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)```

When this happens the benthos consumer occasionally does not respond and reconnect to the consumer group. The benthos instance continues consuming data from the topic, and reports no errors, but no offsets are committed to kafka and the broker reports that there are no active consumers for that group.

All consumers need to be restarted to allow them to rejoin the group, however unless a manual offset reset is performed this results in duplicate data being processed.

The kafka consumer is configured with a 3s heartbeat interval and 60s session timeout.

```      kafka_balanced:
        addresses:
          - ${KAFKA_IN_ADDRESSES}
        topics:
          - ${KAFKA_IN_TOPIC}
        client_id: benthos001
        consumer_group: ${KAFKA_CONSUMER_GROUP}
        group:
          heartbeat_interval: ${HEARTBEAT_INTERVAL:3s}
          rebalance_timeout: ${REBALANCE_TIMEOUT:90s}
          session_timeout: ${SESSION_TIMEOUT:60s}
        ....
```

**Comment by Jeffail** [comment]
Hey @andrewjmurphy do you get any logs from Benthos after it's removed (while it's still consuming)?

**Comment by andrewjmurphy** [comment]
@Jeffail sorry, I should have made that clear.
Benthos does not log anything unusual, it continues processing as if nothing had happened.
I am trying to reproduce but it is a rate intermittent error. If I can reproduce I will try to do so with a process in debug.

**Comment by Jeffail** [comment]
And which version of Benthos?

**Comment by andrewjmurphy** [comment]
`Version: v3.9.0`

**Comment by Jeffail** [comment]
Closing for now as I'm not sure there's anything we can do to confirm or address this. If anyone else sees this issue then please reopen and give us any information you can gather.
