### ISSUE TITLE
What happens to a batch after a failure?

### ISSUE THREAD

**Issue by atheken** [Jeffail/benthos#435]
We are writing to dynamodb with unlimited retries. This works great, but we've had a few cases that appeared to have the benthos broker stalled waiting to retry due to throttling, long after dynamodb had autoscaled write capacity up. If we were to limit the number of retries, would would that result in the batch failing, and the input reattempting delivery with another broker?

We want things to retry, but it's unclear whether the "stall" is due to the output in the broker "pausing", or some other type of unhandled failure condition in benthos. If we knew that errors would result in the entire pipeline being reattempted for that batch, we could limit the number of attempts in the output. I suppose this is possible with a more complex `try` output pattern, but I am wondering if there's a simple way to cause benthos to do this by default?

As a side note, dynamodb clients usually have some "jitter" configured for retries so that thundering herd situations don't cause writers to throttle each other when they get synchronized on failures. Is it possible to randomize the retry interval within a range?

**Comment by atheken** [comment]
After closer reading of the documentation, this does appear to be documented, though it may be slightly non-obvious what the _noack_ mechanism is for each input:

> ### Retries
> When a Benthos output fails to send a message the error is propagated back up to the input, where depending on the protocol it will either be pushed back to the source as a Noack (e.g. AMQP) or will be reattempted indefinitely with the commit withheld until success (e.g. Kafka).

**Comment by Jeffail** [comment]
Hey @atheken, I've opened https://github.com/Jeffail/benthos/issues/437 as this ought to be documented clearly for each input.
