### ISSUE TITLE
Support more operations in elasticsearch output

### ISSUE THREAD

**Issue by atheken** [Jeffail/benthos#436]
Most messages we process and write to external systems with benthos are idempotent, so we can safely overwrite entries to those systems with duplicates.

However, we do have one use case where the content of a record can impact whether it should overwrite the target when writing batches to elasticsearch.

Is it possible to declare whether a message should overwrite a document in elasticsearch, or be skipped, and in general, do you have documentation on how to handle conflict resolution?

**Comment by atheken** [comment]
OK. Answering my own question a little bit here, too.

For ElasticSearch, [it would appear that the output uses the `index` operation, exclusively](
https://github.com/Jeffail/benthos/blob/master/lib/output/writer/elasticsearch.go#L263). Presumably, this will result in conflicts/failed messages when attempting to re-insert the same doc.

Is it possible to make this configurable on the output to select the operation that should be used? 
Options are: `index`, `update`, `delete` (where "update" is actually behaves as an _upsert_).

**Comment by Jeffail** [comment]
Hey @atheken, this is definitely something worth adding.

Related issues:
https://github.com/Jeffail/benthos/issues/373
https://github.com/Jeffail/benthos/issues/374
https://github.com/Jeffail/benthos/issues/318

**Comment by atheken** [comment]
I can take a crack at adding this. I would probably make a new config option 

`operation` that could be sibling to the `index` option of the elasticsearch config, and this would be defaulted to `insert`, but could be overridden to `update`, and `delete`.

There are some use cases where streams could have mixed inserts, updates, and deletes, but I would probably allow the normal pipeline ops do the grouping, and dynamically select the operation for based on each group, as opposed to piling more metadata into each message.

I'm also not really a _gopher_, so this may take me a little while to hack something together, if someone else produces a patch, first, my feelings won't be hurt.

**Comment by Jeffail** [comment]
Done https://github.com/Jeffail/benthos/commit/7c5e637552fb6fc81479513f741cb1832a72703e
