### ISSUE TITLE
RabbitMQ: Make exchange durable option configurable

### ISSUE THREAD

**Issue by andytruong** [Jeffail/benthos#44]
We are trying to connect our RabbitMQ server exchange but durable param is not compatible. It's great if we can support this configuration.

Thanks

**Comment by Jeffail** [comment]
Hey @andytruong, done. https://github.com/Jeffail/benthos/commit/8eacd3a7d27c599ba112e3d4e5662bbac67d47be

**Comment by Jeffail** [comment]
@andytruong, I'll be pushing a change soon that means you no longer even need to specify these fields if the exchanges and queues exist.
