### ISSUE TITLE
Question: Custom Processor Drop Message

### ISSUE THREAD

**Issue by kozelok** [Jeffail/benthos#441]
Hello,

 If I am using a custom processor with some of benthos utilities:

```
// Always create a new copy if we intend to mutate message contents.
	newMsg := msg.Copy()

	proc := func(index int, p types.Part) error {
		
		if filtered() {
			p.Metadata().Set("filtered_out", "1")
			m.mFiltered.Incr(1)
			return nil
		}
		//modify message
		return nil
	}
	IterateMessages("presenceProcessor", newMsg, proc)
	m.mBatchSent.Incr(1)
	msgs := [1]types.Message{newMsg}
	return msgs[:], nil
```

How would I drop a filtered message here without breaking consistency guarantees and not invoking a downstream partsfilter?

**Comment by Jeffail** [comment]
Hey @kozelok, the simplest way is to create a new slice of message parts, append to it only the messages that aren't being removed, and then add them to a new message. If all the messages of a batch are being removed then simply return `nil, response.NewAck()`.

The bloblang processor is a good example of this: https://github.com/Jeffail/benthos/blob/master/lib/processor/bloblang.go#L134

**Comment by Jeffail** [comment]
Closing for now, if you have any follow up questions feel free to reopen.
