### ISSUE TITLE
feature request: support output resources in streams mode

### ISSUE THREAD

**Issue by cludden** [Jeffail/benthos#444]
apologies as this is not obvious to me, but is there a reason this cannot be supported without a breaking change? referring to https://github.com/Jeffail/benthos/blob/dba92179df16a15be17522fed934ad0fff666690/lib/output/resource.go#L95

**Comment by Jeffail** [comment]
Hey @cludden,

Adding a method `GetOutput` to `types.Manager` would technically be a breaking change as it's possible users are running Benthos as a library with their own custom `types.Manager` implementation.

However, this doesn't stop us from being able to use resources in streams mode, I just need to add the method to https://github.com/Jeffail/benthos/blob/master/lib/stream/manager/namespaced_manager.go#L15

Which would allow you to use output resources defined in a global config. Would you also want to reference resources defined within the individual stream config itself? That's also something I can add but I've waited up until now for a use case.

**Comment by cludden** [comment]
I think the second use case would be helpful, primarily for logging & metrics, but not essential if it requires a major effort.

**Comment by Jeffail** [comment]
Implemented using the root level resources: https://github.com/Jeffail/benthos/commit/d79043eeef05f5cad666de4f9d21802f8e5e33a3

I've left out enabling stream level resource definitions for now as there's a lot of stuff that needs thinking through in order to support that.
