### ISSUE TITLE
Add type property to amqp_0.9 output

### ISSUE THREAD

**Issue by jimgus** [Jeffail/benthos#447]
In order to be able to use the amqp_0.9 output to send messages to an existing consumer that expects the Type property to be set on the messages, a configuration option need to be added to be able to set that property. Preferably supporting interpolations in the same fashion as the 'key' config option. I have a solution to this that I can put up as a PR if this request is accepted.

More info on the Type property: https://www.rabbitmq.com/consumers.html#message-properties

**Comment by Jeffail** [comment]
Hey @jimgus, looks like a reasonable addition.

**Comment by Jeffail** [comment]
I'll put a release out with this feature included this weekend.
