### ISSUE TITLE
Use http.RoundTripper option for HTTP Client type

### ISSUE THREAD

**Issue by zlozano** [Jeffail/benthos#453]
The `http.RoundTripper` interface is effectively the only point by which we can inject custom functionality into the `http.Client`. Our team uses tooling such as https://github.com/asecurityteam/transport to use custom connection management strategies, telemetry, tracing, token based auth, access logging, etc.

While most of this is provided in benthos, it's advantageous to emit the standard metrics our org defines so that we can reuse dashboards as well as the standard log shape our log indexer expects. For these reasons, we are looking to create an output plugin for a customized http client. It appears that most of what we need is already available, and if we could configure the existing http client type with our `http.RoundTripper` decorator, we'd have all we need.

It seems that we can [provide a concrete](https://github.com/Jeffail/benthos/blob/master/lib/util/http/client/type.go#L248) `http.Transport` implementation, but if we were able to provide and `http.RoundTripper` instead, our custom HTTP client plugin could reuse most of the logic that currently resides in [client.Type](https://github.com/Jeffail/benthos/blob/master/lib/util/http/client/type.go).

Happy to hear your thoughts, or if there is perhaps a different/better way to go about this.

**Comment by Jeffail** [comment]
Hey @zlozano, that makes total sense. In hindsight the opt func `OptSetHTTPTransport` should've originally had an `http.RoundTripper` parameter.

I've added a new opt func `OptSetRoundTripper` that basically does the same thing, and deprecated the existing func: https://github.com/Jeffail/benthos/commit/0c550aaa02a880be01eeeb2369bb63fd11b0b634

**Comment by zlozano** [comment]
Awesome! Thanks

**Comment by Jeffail** [comment]
Released: https://github.com/Jeffail/benthos/releases/tag/v3.17.0
