### ISSUE TITLE
http processor doesn't respect keep-alives

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#467]
We're seeing benthos making thousands of new HTTP connections per second to the same remote services, which indicates that Benthos is not reusing connections.

There is currently no configuration for keep-alive connections in the HTTP processor, but our understanding is that connections should be automatically reused whenever possible.

**Comment by Jeffail** [comment]
Hey @nicktelford, can you give me the exact version of Benthos you're running?

**Comment by Jeffail** [comment]
Hey @nicktelford I tried this out and confirmed the `http` processor is negotiating and using keep alives automatically on a local server, are you able to provide more information on how the HTTP traffic is being routed to/from Benthos?

**Comment by nicktelford** [comment]
@Jeffail Yeah, upon further investigation, it looks like Benthos is not at fault here. Some additional metrics around this would be very helpful though!
