### ISSUE TITLE
AMQP Output - Batched Messages are sent to wrong topics

### ISSUE THREAD

**Issue by kozelok** [Jeffail/benthos#473]
Hello,

Using the AMQP output and batching, there is a small defect. 

https://github.com/Jeffail/benthos/blob/07e31971131b33a7131ecf1084d60c94fc696956/lib/output/writer/amqp.go#L216

The topic is set once per message, not per part. Looks like that code just needs to move into the iterator function.

Benthos: 3.12

**Comment by Jeffail** [comment]
Hey @kozelok, I should be able to tackle this today.

**Comment by Jeffail** [comment]
Fixed, https://github.com/Jeffail/benthos/commit/f1b14dd23cd1ef51cc3da9029678233353516a9a I'll add this to tomorrows release.
