### ISSUE TITLE
Question - Disable http endpoint

### ISSUE THREAD

**Issue by mallikvala** [Jeffail/benthos#476]
Hey @Jeffail 
Every time i launch benthos,  by default listens on port `4195` for http requests. Is there a way to disable it? for example i wouldn't be needing it in an AWS lambda.

**Comment by Jeffail** [comment]
Hey @mallikvala, there's currently no setting for turning it off, but when running benthos as a lambda function it won't be started anyway, I'll add a note of that in the docs.

It makes sense to be able to disable it in normal operation as well so I'll look into adding a field `enabled` to the `http` config.
