### ISSUE TITLE
HealthCheck Ready Support in Streams Mode

### ISSUE THREAD

**Issue by louisburton** [Jeffail/benthos#477]
There is documented support for a `/ready` endpoint, which is very handy for a Docker HEALTHCHECK, letting us know the inputs and outputs are connected and that effectively the stream is ready for processing.
https://www.benthos.dev/docs/guides/monitoring/#health-checks

I believe we do not have this support however in Streams mode. There is a `/streams` endpoint which gives information as to if each stream hasn't been stopped, and to how long they've been up, but no information equivalent to the ready check for aggregating. When running Benthos via Streams Mode as a service, it's good to understand the readiness still as a whole.

Having an equivalent `/ready` endpoint that could respond with `200` if all inputs and outputs were connected would be handy.

Thanks for all your work on this project! 😄

**Comment by Jeffail** [comment]
This should be straight forward to implement, I'll try and make time for it this weekend.
