### ISSUE TITLE
Potential collision and risk from indirect dependence "github.com/gotestyourself/gotestyourself"

### ISSUE THREAD

**Issue by KateGo520** [Jeffail/benthos#488]
## Background
Repo `Jeffail/benthos` used the old path to import `gotestyourself` indirectly.
This caused that `github.com/gotestyourself/gotestyourself` and `gotest.tools` coexist in this repo：
https://github.com/Jeffail/benthos/blob/master/go.mod （Line 44 & 101）
```
github.com/gotestyourself/gotestyourself v2.2.0+incompatible // indirect
gotest.tools v2.2.0+incompatible // indirect 
```

That’s because the `gotestyourself` has already renamed it’s import path from "github.com/gotestyourself/gotestyourself" to "gotest.tools". When you use the old path "github.com/gotestyourself/gotestyourself" to import the `gotestyourself`, will reintroduces `gotestyourself` through the import statements "import gotest.tools" in the go source file of `gotestyourself`.

https://github.com/gotestyourself/gotest.tools/blob/v2.2.0/fs/example_test.go#L8 
```
package fs_test
import (
	…
	"gotest.tools/assert"
	"gotest.tools/assert/cmp"
	"gotest.tools/fs"
	"gotest.tools/golden"
)
```

"github.com/gotestyourself/gotestyourself" and "gotest.tools" are the same repos. This will work in isolation, bring about potential risks and problems. 

## Solution
Add replace statement in the go.mod file:
```
replace github.com/gotestyourself/gotestyourself => gotest.tools v2.3.0
```
Then clean the go.mod.

**Comment by KateGo520** [comment]
@Jeffail  Could you help me review this issue? Thx :p

**Comment by Jeffail** [comment]
Hey @KateGo520, thanks for the great write up, this was very easy to follow. I've had a skim over the deps that include this and it looks like I can eliminate it entirely by upgrading dockertest.

**Comment by KateGo520** [comment]
Thanks for your efforts and feedback.
