### ISSUE TITLE
Add `subprocess` input

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#495]
This should behave similarly to the [`subprocess` processor](https://www.benthos.dev/docs/components/processors/subprocess) but we should also considering adding a field `restart_on_close` as a convenience.

**Comment by stergiotis** [comment]
Benthos is a marvelous piece of work, much in the tradition of good old unix tools and a joy to use. Many, many thanks!

Adding support for a few length-prefixed binary formats like netstring, delimited protobuf, benthos "binary" archive format etc would be IMO cover many additional use-cases.

**Comment by Jeffail** [comment]
What are peoples thoughts about `subprocess` as a name? I'm maybe thinking while I'm at this we could consider calling these components `cmd`, `command`, `exec` or something else entirely. The name `subprocess` seems to slip under the radar for a lot of people.

**Comment by qjcg** [comment]
Personally, I had no trouble finding `subprocess`, but of the alternatives you mention, `command` seems to me to be the most obvious (i.e. the one a broad userbase would be least likely to have trouble finding).

**Comment by jedjones-uk** [comment]
I would second a name change to `command`/`exec`, I didn't find `subprocess ` until after I started on a plugin. I actually prefer `exec` as I think that is a more common convention across OS/Languages.

I also feel it is important to mention in the docs that generally it is executing things with a root of the benthos directory, so if that 3rd party app is writing to a relative path that path will be relative to benthos. I know for a lot of people that is an obvious fact, but I am pretty sure it will save at least a few complaints.

I'd also add to the general issue/ticket that it is immensely helpful as an output as well, and then you can call out to a 3rd party app at any point in the chain.

**Comment by jackxbritton** [comment]
I prefer `subprocess`. It's consistent with Python3 and I'm used to that.

This input sounds fine to me - the specific configuration for what to do on failure / exit will have to be nailed down ofc. Would this component support running a terminating subprocess periodically, as well as subprocesses intended to run forever?

I suppose the former could be achieved by combining a period bloblang input with a subprocess processor.

**Comment by mfamador** [comment]
I think `command` or `exec` (biased by go, kotlin, java, etc.), or even `process` would be perhaps clearer, but no strong opinion here, I found `subprocess` easily enough.

**Comment by Jeffail** [comment]
Awesome, thanks everyone. I think for now I'll keep these components named `subprocess` and put some extra work into making them more discoverable. The plan right now is to implement a basic input and output, where messages are consumed and written as newline delimited stream.

Once that's in and usable the next step will be adding a field `codec` to each, where you can specify a different method for breaking messages up, such as JSON stream, binary protocols, etc. I don't see why we couldn't also add that to the `subprocess` processor.

**Comment by Jeffail** [comment]
New input and output added in: https://github.com/Jeffail/benthos/commit/873eb66f27c4bb297d33ee62b6bd7b97c1de67ae, just the one `lines` codec for now but it's easy enough to add stuff like binary protocols if anyone is interested.

**Comment by Jeffail** [comment]
Released: https://github.com/Jeffail/benthos/releases/tag/v3.31.0
