### ISSUE TITLE
Build fails on bluemonday 

### ISSUE THREAD

**Issue by darsenault** [Jeffail/benthos#498]
I'm following the blog post about building Benthos Plugins using v2 and using the linked main.go file but get a build error always failing on bluemonday. 

`go build`
`go: downloading github.com/microcosm-cc/bluemonday v1.0.4`
`../../../go/pkg/mod/github.com/!jeffail/benthos/v3@v3.28.0/internal/bloblang/query/methods_strings.go:27:2: github.com/microcosm-cc/bluemonday@v1.0.4: stream error: stream ID 1; NO_ERROR`

Oddly `go get github.com/microcosm-cc/bluemonday` also fails.

`go get github.com/microcosm-cc/bluemonday`
`go: downloading github.com/microcosm-cc/bluemonday v1.0.4`
`go get: github.com/microcosm-cc/bluemonday@v1.0.4: stream error: stream ID 3; NO_ERROR`

Other clues:

- The author of bluemonday cannot replicate the error using the same Catalina macOS and go version. His `go get` works fine.
- Same error using go 1.14.9 and 1.15.2
- Same error on two different networks.
- I am able to successfully go get ever other library I try, even random picks from Awesome Go. The rest of Benthos' deps come in just fine. 
- Other projects using modules work perfectly fine. 

I am truly puzzled and would deeply appreciate any hits/ideas to push past this showstopper. Thank you.

**Comment by Jeffail** [comment]
Hey @darsenault, some stuff to try out:

Run without using the goproxy: `GOPROXY=direct go build -o ./benthos`

Add this line to your `go.mod`:

```
replace github.com/microcosm-cc/bluemonday v1.0.4 => github.com/Jeffail/bluemonday v1.0.4
```

I've forked the `bluemonday` repo to my account, I have no idea why that would change anything but given other modules are downloading fine maybe this will work. I tried that replace rule locally and it pulls fine, but then so does the original repo so I'm not holding my breath, but it might give us more clues.

**Comment by Jeffail** [comment]
Also have you tried doing a `go get` of a different tagged version? Try something like `go get github.com/microcosm-cc/bluemonday@v1.0.1`. I'm maybe thinking there's a specific file in the repo that is getting blocked or something.

**Comment by darsenault** [comment]
@Jeffail the go proxy was indeed the problem for some odd reason.

`export GOPROXY="direct"`

Prior value:
`GOPROXY="https://proxy.golang.org,direct"`

Now Benthos builds its glorious self without complaint even, using the original repo for bluemonday.
**Problem solved.** Thanks so much for this pro tip.

**Comment by Jeffail** [comment]
@darsenault, no problem! Glad I could help.
