### ISSUE TITLE
Add ability to create new fields via regular expression's Named Captured Group

### ISSUE THREAD

**Issue by DpoBoceka** [Jeffail/benthos#512]
Suppose, we have a text-formatted message:

`Group <AnyConnect> User <test.user> IP <7.7.77.777>`

it'll be handy to call just one regular expression with names in it and get a json object with those names and matching groups as keys and values respectively.

Say, following expression

`"Group <(?P<foo_group>.*)> .*User <(?P<foo_user>.*)> "`

would return with a json

`{"foo_group": "AnyConnect", "foo_user": "test.user"}`

It must present some type-savings in cases when you need to get a dozen of fields out of a single message with regular expression. 

So, perhaps, adding a blobl method "re_expand" would get us out of a pickle.

**Comment by Jeffail** [comment]
I've added two methods `re_find_object` and `re_find_all_object` in https://github.com/Jeffail/benthos/commit/843a39f138e2d1eec9a53bf44a8d73aa032b651a

Which allows you to do `root.matches = this.value.re_find_object("Group <(?P<foo_group>.*)> .*User <(?P<foo_user>.*)> ")`. Or, if you want to remove the whole match, use: `root.matches = this.value.re_find_object("Group <(?P<foo_group>.*)> .*User <(?P<foo_user>.*)> ").without("0")`.
