### ISSUE TITLE
NATS input replies

### ISSUE THREAD

**Issue by iluminae** [Jeffail/benthos#513]
The NATS input has a stub for acknowledgements, yet the NATS system supports replies creating an acknowledgment system. From the [NATS documentation](https://docs.nats.io/nats-concepts/acks): 
> When you are publishing an event or data stream, one way to ensure message delivery is to turn it into a request-reply with the concept of an acknowledgement message, or ACKs. In NATS an ACK can simply be an empty message, a message with no payload.

So may I suggest that we add a conditional ACK if the `*nats.Msg` has a `Reply` string? Based on the Nats documentation and a quick peek at the code it would just be a `n.natsConn.Publish(msg.Reply, nil)`. That way a NATS publisher could confirm a message was processed in it's entirety.

Thanks!

**Comment by Jeffail** [comment]
Hey @iluminae, interesting, yeah that seems like a reasonable addition.

**Comment by mihaitodor** [comment]
Docs link broken. Please refer to https://github.com/nats-io/nats.docs/blob/080861171b23d30c7181b4b5aebda688d78de697/nats-concepts/acks.md until they fix it: https://github.com/nats-io/nats.docs/issues/344
