### ISSUE TITLE
-r flag should accept multiple arguments

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#525]
Currently, you have to specify `-r` for each file you wish to include:
```
benthos -c conf.yaml -r snippets/foo.yaml -r snippets/bar.yaml
```
It would make life much easier if it accepted multiple arguments, allowing shell expansions to function as expected:

```
benthos -c conf.yaml -r snippets/*.yaml
```
is equivalent to:
```
benthos -c conf.yaml -r snippets/foo.yaml snippets/bar.yaml
```

**Comment by Jeffail** [comment]
You'll be able to do `benthos -r "snippets/*.yaml" -c ./conf.yaml`, note the need for quotes, otherwise your shell will expand the glob patterns and the cli is invalid.
