### ISSUE TITLE
csv input support glob patterns

### ISSUE THREAD

**Issue by gmonk** [Jeffail/benthos#529]
How would i consume a directory of csv files using the csv input?  I have a directory of about 30k. I tried using a wild card for the path but that does not seem to work nor does just pointing it the directory seems i have to list each file in the path array.

Thanks

**Comment by Jeffail** [comment]
Hey @gmonk, unfortunately it doesn't support that but it should be quick to add.

**Comment by Jeffail** [comment]
Done https://github.com/Jeffail/benthos/commit/6b9b8d51cfd2d45f515ee3bb7924fe3ad33777ba, it'll be in the next release.
