### ISSUE TITLE
CSV glob not working v3.31.0

### ISSUE THREAD

**Issue by gmonk** [Jeffail/benthos#538]
Trying to import csv files in folder fails with "Failed to connect to file: open csv/*.csv: no such file or directory"

tried the following with no success using both with and without double quotes.
"csv/\*.csv"
"/csv/\*.csv"

**Comment by Jeffail** [comment]
Hey @gmonk, the CSV globbing is part of v3.32.0, there's currently a release candidate: https://github.com/Jeffail/benthos/releases/tag/v3.32.0-rc1

**Comment by gmonk** [comment]
oops sorry about that i jumped the gun..  I will download the rc and test.

Thanks
