### ISSUE TITLE
Support for Redis streams?

### ISSUE THREAD

**Issue by mtwilliams** [Jeffail/benthos#54]
Hey Ash,

First off, this is lovely and so frickin' useful. Thanks for open-sourcing it.

I was curious - are there (immediate) plans for supporting [Redis streams](https://redis.io/topics/streams-intro)?

**Comment by Jeffail** [comment]
It's a good fit so yeah definitely, it looks as though support has been added to github.com/go-redis/redis so there aren't any blockers. I'll take this if I have time but it's not a priority for me right now.

**Comment by Jeffail** [comment]
Hey @mtwilliams, I had a look at the spec for streams and I'm really impressed, very simple and clean. Thanks for bringing it into the spotlight.

Implemented: https://github.com/Jeffail/benthos/commit/539bc2ed3e03932162778815ac7581383a7a1c4a
Released: https://github.com/Jeffail/benthos/releases/tag/v0.26.1

**Comment by mtwilliams** [comment]
You're amazing. Thank you!
