### ISSUE TITLE
Switch processor permits empty cases

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#546]
The switch processor allows both cases with no `processors`, and cases with no `check`. This can cause typos to lint, despite not being valid:

```
switch:
- check: foo == "bar"
- processors:
  - resource: bar
```

This lints, despite `resource: bar` being impossible to execute, because there is no condition associated with it to ever run.

**Comment by Jeffail** [comment]
Done https://github.com/Jeffail/benthos/commit/2e081491c6e0cd3430bb47d848ddbdfa57cf5813
