### ISSUE TITLE
Syntax errors in bloblang expressions not checked by linter

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#547]
The linter assumes that every bloblang expression is valid, this can cause invalid bloblang expressions anywhere in your configuration to prevent benthos from starting, despite the lint passing.

Expected behaviour: Linter flags all syntax errors in all bloblang expressions (including interpolated expressions).

**Comment by Jeffail** [comment]
This is done and will be in the next release: https://github.com/Jeffail/benthos/commit/cd97a28ab8d87c95fd07029309d92136d28bf5a0
