### ISSUE TITLE
using benthos as prometheus metrics pusher

### ISSUE THREAD

**Issue by dilipkk-foyernet** [Jeffail/benthos#548]
Is it advisable to use benthos to push data to Prometheus instead of using Prometheus push gateway? Let us say, we are streaming entire time-series to Prometheus using benthos. Is it a good idea?

Thanks,
Dilip
https://www.benthos.dev/docs/components/metrics/prometheus

**Comment by Jeffail** [comment]
Hey @dilipkk-foyernet, I can't say definitively which is a better option but I would probably lean towards using the prometheus push gateway since from my understanding that's exactly what it's built for, whereas benthos would require a fair amount of configuration in order to get this right.

**Comment by dilipkk-foyernet** [comment]
Thank @Jeffail.
