### ISSUE TITLE
Nanomsg interoperability with NNG is out of date 

### ISSUE THREAD

**Issue by egimbernat** [Jeffail/benthos#551]
Hi! I just trying to use NNG along with Benthos and I found out that Mangos dependency is outdated and needs to be upgraded to a modern one (go.nanomsg.org/mangos/v3) in order to support many features that came after version 1 of Mangos.

At first, glance seems that the update is trivial and it only needs the dependency upgrade, otherwise I can make a PR with this change.

**Comment by Jeffail** [comment]
Hey @egimbernat, will do, I should be able to get this in before the next release.

**Comment by Jeffail** [comment]
Had a quick go and it looks okay but the tests fail, needs looking into but I probably won't get around to it until tomorrow, working off a branch: https://github.com/Jeffail/benthos/tree/upgrade-nanomsg

**Comment by egimbernat** [comment]
Hi Jeffail, I just work on the solution, seems that the writer has an invalid option that previous Mango version were not validating, the fix is a follows: https://github.com/egimbernat/benthos/commit/90370fb0f61e1adf8b405503ae9e90b4a8a79031#diff-8c9c583411865c52ffad5b6c6c0940fcf2449881d3598e40e56411081d6d23f1R122

PD: the commit contains whole working implementation of Mangos V3

**Comment by egimbernat** [comment]
Just as an update, the input part also has an issue with the timeout options, I fixed it with the correct one. 

I can confirm that the update works on the input and output along with interoperability with NNG.

**Comment by Jeffail** [comment]
@egimbernat nice! That must be a three year old bug 😅 merged https://github.com/Jeffail/benthos/commit/841c7416908c7cc6330c6752b57b2bb918c10fe8

I'll hopefully make time to add more integration tests for nanomsg soon.

**Comment by Jeffail** [comment]
Closing for now but please reopen if you have any issues.

**Comment by egimbernat** [comment]
Awesome that change is already merged! I saw an issue on lib/input/reader/scale_proto.go, since PULL and SUB are receiving sockets only, **OptionSendDeadline** is not an allowed option.

From my tests the only option allowed and needed is:
```

err = socket.SetOption(mangos.OptionRecvDeadline, s.repTimeout)
	if nil != err {
		return err
	}
```

**Comment by Jeffail** [comment]
Ah I see, I've removed it for now https://github.com/Jeffail/benthos/commit/9f19b54dec85a634f749843a47d138c9e44ae8aa, although eventually I should add it back in for req/res sockets.

**Comment by Jeffail** [comment]
@egimbernat, I added some proper integration tests and surfaced a couple of other issues as well, hopefully good now since https://github.com/Jeffail/benthos/commit/f64dfacb65cf89879aefd18f26a6bd6d90e1bcb9
