### ISSUE TITLE
file input is missing path metadata

### ISSUE THREAD

**Issue by cludden** [Jeffail/benthos#558]
the now deprecated `files` input supported metadata that included the file path, this behavior seems to be missing from the new `file` input, was that intentional?

**Comment by Jeffail** [comment]
Whoops, the intention is definitely to have parity so I'll make sure this is in the next release.

**Comment by Jeffail** [comment]
Added: https://github.com/Jeffail/benthos/commit/83c27eb12264ab3df81ddc0143d1c5032929619a
