### ISSUE TITLE
Add amqp_0_9 output custom content-type support?

### ISSUE THREAD

**Issue by dz-at-tc** [Jeffail/benthos#562]
I see that amqp_0_9 input automatically makes the incoming message content-type available as a metadata field.

But alas, as near as I can tell, amqp_0_9 output always sets the outgoing message content-type to application/octet-stream.

Would it be possible to make this configurable?

Thanks!

**Comment by Jeffail** [comment]
Hey @dz-at-tc, sounds like a good fit.

**Comment by dz-at-tc** [comment]
Hi @Jeffail , thanks mate!

**Comment by Jeffail** [comment]
Done https://github.com/Jeffail/benthos/commit/a0e1a19b07434d1c9676ef0b44f012510be1f68b
