### ISSUE TITLE
Output "sent" metric counts batches, not messages, when batching is enabled

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#563]
When you enable `batching` processors in an output, the `sent` metric counts the total number of messages produced by the batching processors, and not the total number of input messages successfully sent.

While at first glance this seems reasonable, it's not the behaviour you'd really expect. The `batch.sent` metric already reports the number of batches written, so when `batching` processors are used, the `sent` metric is always the same as `batch.sent`, and there's no way to know how many messages were successfully written to the output.

As an example, if you have an S3 output with the following:
```
batching:
- processors:
  - archive:
      format: tar
  - compress:
      algorithm: gzip
```
`sent` will record the total number of `.tar.gz` files written to S3, but there's no way to know how many messages were actually written to that file.

Either the `sent` metric should be changed to reflect the total messages successfully written to the output as a whole, or a new metric should be introduced that provides this information.

**Comment by Jeffail** [comment]
Fixed: https://github.com/Jeffail/benthos/commit/e5802ee001565b1c228b3c21aa14518b9d64bdc0
