### ISSUE TITLE
Include Postgres as input

### ISSUE THREAD

**Issue by adolsalamanca** [Jeffail/benthos#570]
Would it be possible to implement PostgreSQL as input source? 

Deliver data using Streams is feasible, there are a few implementations:
https://github.com/tmc/pqstream
https://github.com/hasura/pgdeltastream

Thanks,

Adolfo

**Comment by Jeffail** [comment]
Hey @adolsalamanca, there's an existing issue for change data capture: https://github.com/Jeffail/benthos/issues/8. Thanks for the links, I've added them to the other issue. This is definitely something I intend to add but I can't give any estimates, definitely still at the early ideas phase.
