### ISSUE TITLE
env bloblang function produces empty string instead of null for missing env vars

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#571]
If an env var is not set, the `env` function always produces an empty string instead of a null/missing value.

This means you can't use the coalesce operator with env vars:
```
foo = env("FOO") | "bar"
```
will always yield:
```
{
  "foo": ""
}
```

A viable work-around is to use a `match`:
```
match env("FOO") { "" => "bar", _ => this }
```
But this is cumbersome, especially when you want to use an env var in more complex expressions:
```
foo = json(env("FOO_PATH") | bar.baz) | "bar"
```
vs.
```
foo = json(match env("FOO_PATH") { "" => "bar.baz", _ => this }) | "bar"
```

**Comment by Jeffail** [comment]
There's currently an inconsistency between standard JSON queries `foo.bar.baz`, metadata queries with `meta`, and `env`:

| Query type | Value when missing |
| :------------- | -----------: |
|  JSON | `null` |
|  Metadata | Errors |
| Env var | Empty string |

Changing the behaviour of JSON queries is out of the question as it's almost guaranteed that returning `null` is already relied on in a lot of mappings. Changing `meta` or `var` would also technically be a breaking change. However, it could be also be considered a bug to return an empty string on a non-existent env var so there's room for interpretation, and as long as we're considerate over how we might impact existing mappings we should be fine.

Options for `env` and `meta` are to return `null`, return an empty string and add a convenience method `not_empty`, or return errors in both cases. Changing `env` and `meta` to return `null` is the most breakingest change so I feel uneasy about that. Returning errors could work but is significantly different to JSON queries.

Adding `not_empty` would allow `foo = env("bar").not_empty() | "waddup"`, which is a little long winded but would be fully backwards compatible.

**Comment by Jeffail** [comment]
Consistency across all these is now added to v4: https://github.com/Jeffail/benthos/commit/cec72e7c627997dd8db6fec3e8fffe2961fb3ed3
