### ISSUE TITLE
XML data processed by the xml processor breaks jmespath

### ISSUE THREAD

**Issue by fitter22** [Jeffail/benthos#575]
Hi Jeffail,
I am operating with API which reports data as XML, as one of the first steps I process the input with xml processor to get a json out of it. Lets analyze this simplified data structure:
```
{
  "-coord_deg_lat": "str",
  "-coord_deg_lon": "str",
  "-coord_deg_sl": "105",
  "-id": "1375",
  "-last_measure": "1606740301",
  "name": "Test"
}
```
I after the processing I want to filter the data I want to send to the DB, so far I was using jmespath queries for that. For example:
```
- jmespath:
    query: "{vendor_id: -id, name: name}"
```
This breaks the pipeline with `failed to compile JMESPath query: SyntaxError: Invalid token: tNumber"`. Looks like the additional minus sign is the problem here, which upsets the jmespath interpreter. I was trying to escape this somehow, but no luck. Is there any way to access or filter that data in a different way?

I am not sure if this a bug though, the names are completely valid according to the JSON spec AFAIK, bloblang seems to be fine with such names also, the only problem I found was with jmespath processor.

**Comment by Jeffail** [comment]
Hey @fitter22, I believe in JMESPath you can quote the field path, so in your case:

```
  - jmespath:
      query: '{vendor_id: "-id", name: name}'
```

Should work, note that I've used single quotes for the query to avoid having to escape the quotes within it.

**Comment by fitter22** [comment]
Thank you for this VERY quick answer, which in fact solves my issue completely. I wasn't aware of this feature of jmespath. I tested it just now, normal escaping for the quotes also works.
Cheers!
