### ISSUE TITLE
Can't delete fields in Bloblang JSON expressions

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#576]
There's an inconsistency with JSON expressions in bloblang
```
$ echo '{}' | ./benthos blobl 'root.foo = deleted()'
{}
$ echo '{}' | ./benthos blobl 'root = { "foo": deleted() }'
{"foo":null}
```
This is a problem, because you can't do regular mappings inside an if statement; you have to use JSON, and there's no way to have optional fields in the JSON.

**Comment by Jeffail** [comment]
Yeah this is definitely a bug, you should be able to do both `{"foo": this.count | deleted()}` and also things like `{"foo": if this.count > 5 { this.count }}` and result in `{}` for both when the conditions are not met.

**Comment by Jeffail** [comment]
Fixed: https://github.com/Jeffail/benthos/commit/b1b2ea5d521d5cc512390c85f2164ac22d35272d
