### ISSUE TITLE
Prometheus metrics via push_url with basic auth (on Lambda)

### ISSUE THREAD

**Issue by razor-x** [Jeffail/benthos#577]
I am trying to push metrics out of AWS lambda via prometheus push gateway. I have a `push_url` that requires basic auth. I tried using a url of the form `https://user:pass@example.com` but that doesn't work.

Seems like the Go client supports this via a separate option:  https://godoc.org/github.com/prometheus/client_golang/prometheus/push#Pusher.BasicAuth

I also want to confirm that this is supported on Lambda, i.e., the metrics will push out before the lambda env shuts down.

**Comment by Jeffail** [comment]
Hey @razor-x, yeah I believe that the final push should still happen with lambda. Although there's no guarantee as to how many invocations might occur beforehand.

**Comment by razor-x** [comment]
@Jeffail Should be handled by https://github.com/Jeffail/benthos/pull/578
