### ISSUE TITLE
Cannot use local config on lambda (simple to fix)

### ISSUE THREAD

**Issue by razor-x** [Jeffail/benthos#579]
1. AWS lambda limits env var size to 4KB. So larger configs must be read from file system.
2. This looks to be supported here: https://github.com/Jeffail/benthos/blob/9768b9b6e4fac1e5eb3d260878edb401188adc72/lib/serverless/lambda/lambda.go#L21-L25
3. However, these should be relative paths, NOT absolute paths. When I add the config file to the lambda zip, the entire config is mounted at `/var/task`. So My config is at `/var/task/benthos.yml` but Benthos tries to read `/benthos.yml`.

AWS lambda throws this error when Benthos tries to read from the root

```
START RequestId: d63aaf04-0b56-4e11-9ed3-6d2cd7acfa76 Version: $LATEST
fork/exec /var/task/benthos-lambda: permission denied: PathError
null
```

So (A) root is locked out and (B) there is no way to put files at the root anyway.

**Comment by Jeffail** [comment]
I've added two relative checks, `./benthos.yaml` and `./config.yaml`. I didn't remove the absolute paths because I can't rule out someone isn't doing something crazy that relies on them: https://github.com/Jeffail/benthos/commit/3bd0bdc52660d131c18cfff34aeeca6aadeb08aa

**Comment by razor-x** [comment]
Just a quick followup;

1. The original reported error was due to a different deployment problem, but otherwise the inability to deploy the config at the root via the zip is still valid.
2. We deployed this and it's working!
3. We are using a Node.js build step to inject the configs into new zips. Code snippet below in case it helps anyone:

```js
import fs from 'fs'

import jszip from 'jszip'

// srcPath = path to the normal benthos lambda zip 
// outputPath = path to save the new zip (use this as the serverless artifact)

const generateZipWithFiles = async (srcPath, outputPath, filesAndContent) => {
  const input = await fs.promises.readFile(srcPath)
  const zip = await zipLoadAsync(input)

  for (const { name, content } of filesAndContent)
    zip.file(name, content, { unixPermissions: '644' })

  const buff = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    platform: process.platform
  })

  await fs.promises.writeFile(outputPath, buff)

  console.log(`Created ${outputPath}`)
}
```

If using serverless

```yaml
myfunc:
  handler: benthos-lambda
  package:
    artifact: tmp/myfunc-benthos.zip
    # UPSTREAM: https://github.com/serverless/serverless/issues/4720#issuecomment-681750260
    individually: true
    include: []
    exclude: ['*/**']
```

**Comment by Jeffail** [comment]
Ace, thanks for the update @razor-x!
