### ISSUE TITLE
kafka_balanced performance bug

### ISSUE THREAD

**Issue by bigkraig** [Jeffail/benthos#58]
I have noticed some slow Kafka inputs and it looks like `offsetLastCommitted` isn't set in the kafka_balanced plugin.

**Comment by Jeffail** [comment]
Ding ding ding, we have a blob of the day. Fixed https://github.com/Jeffail/benthos/commit/1c5656a4432d8ff86ecf96df00e3449358062d5f, released in https://github.com/Jeffail/benthos/releases/tag/v0.25.1

Thanks @bigkraig
