### ISSUE TITLE
Add json_equals unit test predicate

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#583]
The `content_equals` predicate does an exact string match on the output document. This has several drawbacks when working with JSON:
  * structural whitespace, which is irrelevant in JSON, is included in the test
  * ordering of fields, which is also irrelevant in (most) JSON, is strictly enforced

This can be problematic for a number of reasons:
  * Very large JSON fixtures have to be compacted and inlined to a single, very long, line in the test YAML document.
  * If the field ordering of a mapping behaves non-deterministically, it may not be possible to write a test for it.

The solution is to create a `json_equals` predicate, that behaves similarly to `content_equals`, but with the following differences:
  * the test fixture must be a valid JSON document
  * the output message must be a valid JSON document
  * structural whitespace is ignored during comparison
  * field ordering is ignored during comparison

**Comment by ollystephens** [comment]
See https://github.com/Jeffail/benthos/pull/621 for incoming PR that implements this.
Also adds `json_contains` predicate which passes if condition is structural subset of message.
Also adds `json_content` so can specify input messages structurally too.
