### ISSUE TITLE
Is there a way to prepend bytes to the message value

### ISSUE THREAD

**Issue by nik-kor** [Jeffail/benthos#584]
We'd like to use benthos to generate Avro messages from json files and then publish them into Kafka topic. 
The problem we encountered is that confluent Kafka format requires additional 5 bytes before the actual message https://docs.confluent.io/3.2.0/schema-registry/docs/serializer-formatter.html#wire-format . 

I could not find a way to prepend those bytes using one of the processors. Is there a way to do it in benthos?
like (json -> avro -> **prepend 5 bytes** -> publish to kafka topic)

**Comment by Jeffail** [comment]
Hey @nik-kor, you might need to experiment a little bit but I _think_ this should work:

```yaml
pipeline:
  processors:
    - bloblang: |
        root = "\x00\x01\x02\x03\x04" + content()
```

Strings in bloblang follow the same rules as Go strings, so you can create a string with binary characters using hexadecimal format as well as some other ways: https://blog.golang.org/strings

I've seen other users hit the same issues with confluents avro format so it really seems like something Benthos should understand natively in the avro processor. Unfortunately, I'm not particularly well versed in avro and its uses so for now I'll link this to a general purpose "improve avro" issue: https://github.com/Jeffail/benthos/issues/381 and maybe we can tackle this somehow in a better way in future.

**Comment by Jeffail** [comment]
Closing for now, feel free to reopen if you have any follow up questions.
