### ISSUE TITLE
Unit tests do not recognize new output types

### ISSUE THREAD

**Issue by razor-x** [Jeffail/benthos#604]
I don't have a complete list of the missing ones, but I'm guessing it mostly affects the `aws_*` and the new `reject` types. 

For example

```
Failed to execute test target 'config/bifurcate-queue.yaml': line 52: line 62: unable to infer type, candidates were: [reject]

Failed to execute test target 'config/bifurcate-queue.yaml': line 48: unable to infer type, candidates were: [aws_lambda]
```

**Comment by Jeffail** [comment]
Hey @razor-x, are you 100% sure your tests are being run by the latest version? I'm not able to reproduce this.

**Comment by razor-x** [comment]
Yup, that was it 🤦🏻 I thought I was updated locally. Sorry for wasting your time, happy new year! 🎆
