### ISSUE TITLE
Add min, max, abs, log, ln and ceil methods

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#606]
The following methods would be tremendously useful for mathematical calculations:
* `min` and `max` on an array of numbers to produce the smallest/largest number in the array, respectively.
* `abs` on a number to take the absolute value, irrespective of sign.
* `log` on a number to take the logarithm (base 10) of the number.
* `ln` on a number to take the natural logarithm (base e) of the number.
* `ceil`, the inverse of `floor` to always round a number up.

**Comment by Jeffail** [comment]
Done https://github.com/Jeffail/benthos/commit/fce4bbdffda41996c08675b0316a623c6332f2e1

**Comment by Jeffail** [comment]
FYI I've named the log methods `log` for natural log and `log10` for decimal log, as those match the Go standard lib.
