### ISSUE TITLE
grok'ing into nested objects ?

### ISSUE THREAD

**Issue by filippog** [Jeffail/benthos#607]
I'm trying out Benthos to replace a Logstash pipeline (and more!). So far it looks super interesting, thank you for your work!

I'm looking into a specific use case we have now and how to do the same with Benthos, specifically how to grok strings into nested fields. I know Logstash supports the `%{PATTERN:[outer][inner][field]}` to parse `PATTERN` into `outer.inner.field.` I tried a few different combinations, with no joy so far:

```
pipeline:
  processors:
    - grok:
        patterns:
          - "%{NOTSPACE:[nested][field]"
```

Results in the grok processor finding no matches

```
echo "test" | ./benthos -c inout_grok.yml --log.level debug
{"@timestamp":"2020-12-14T16:37:40+01:00","@service":"benthos","level":"DEBUG","component":"benthos.pipeline.processor.0","message":"No matches found for payload: test"}
```

Ditto while using `"%{NOTSPACE:nested.field}"`, of course using `${NOTSPACE:field}` works as intended:

```
{"field":"test"}
```

One of my tests has also been to use e.g. `%{NOTSPACE:nested__field}` and then use blobl to recursively set the nested fields, although I can't quite figure out how to achieve the same with a generic (recursive?) bloblang.

Is grok'ing into nested fields something that's possible in Benthos?

**Comment by Jeffail** [comment]
Hey @filippog, this should be quick to implement as it's a limitation in how the target expression is parsed. I'll aim to tackle https://github.com/Jeffail/benthos/issues/424 at the same time.

**Comment by Jeffail** [comment]
Done https://github.com/Jeffail/benthos/commit/0b5664d5bf224f60032821c97ad27828f9423d18, planning to release later this week.

**Comment by filippog** [comment]
Fantastic, thanks a lot @Jeffail !
