### ISSUE TITLE
Compilation error due to time.Reset()

### ISSUE THREAD

**Issue by ianaz** [Jeffail/benthos#609]
`ticker.Reset()` have been introduced only in 1.15 and Benthos makes use of this.

Building with previous versions fails with `b.timer.Reset undefined (type *time.Ticker has no field or method Reset)`

**Comment by Jeffail** [comment]
Since it wasn't an intentional upgrade and came as a surprise I'm happy to look into allowing older versions again if there's a need for it, so I've opened https://github.com/Jeffail/benthos/issues/611 just in case you or others are blocked by this.
