### ISSUE TITLE
The socket_server input is throttled on single message in flight

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#612]
Currently the `socket_server` allows only one message to be in flight per open connection, this means that when writing to outputs that block for acknowledgement the throughput is heavily limited, and that batching at the output level is not possible. This input should be expanded to allow arbitrary in flight messages, relying on the back-pressure downstream to prevent the flow of messages.

Care should be made to ensure that retries are attempted if an error occurs downstream, but if there's a clear trade off to be made then we can expose it as a config parameter.

**Comment by yev-dimo** [comment]
@Jeffail Is there any reason to not auto "ack", since tcp/udp input has no real acknowledgment?

**Comment by Jeffail** [comment]
@yev-dimo we can, but in the default case where we're writing `socket_server` to a destination without brokering or using `drop_on` etc I want the behaviour to be that if the output becomes unavailable or rejects a message then we retry it indefinitely and apply back pressure.

Ideally Benthos should always make a best attempt to deliver all messages (with a preference for back pressure when nacks aren't possible upstream) unless you tell it otherwise.

I already have some components for doing this automatically, I just need to hook them up and test, etc.

**Comment by Jeffail** [comment]
Taken care of as part of https://github.com/Jeffail/benthos/commit/d9f99b5ea0a0a4fab775b507c63e4d31fbda9519
