### ISSUE TITLE
Allow disabling consumer groups with `kafka` input

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#618]
The kafka input should have an option to support ignoring any stored offsets and instead consume from the latest (or oldest) offset each time the connection is established.

**Comment by codingconcepts** [comment]
Would making consumer_group an interpolation field help here, perhaps?

**Comment by Jeffail** [comment]
An alternative is that you allow users to specify an empty consumer group which disables partition balancing and offset persistence. A minor annoyance here is that Benthos sets it to a default value, so you'd need to add an explicit `consumer_group: ""` to your config, but we can have it empty by default in V4.

Allowing consumer group interpolations has the advantage of being able to resume a previous group if you later decide to, but we're not really offering any tools for enabling that, so you'd need to manually dig out the random identifier and make it explicit in the Benthos config. It would also mean persisting an unbounded number of group offsets, meaning if the retention period (`offsets.retention.minutes`) of the broker is high we'd potentially end up taking a significant amount of space and resources for information that's likely being unused.

The consumer group interpolation approach is definitely cleaner for us to implement (kudos to @DeeJayBro) but I'm a little worried that once the cats out of the bag we're then responsible for any negative repercussions, and this is something that could end up slowing down brokers if a user isn't careful.

**Comment by DeeJayBro** [comment]
Another alternative would be to add an option to reset the offset to oldest or newest on startup, but this could potentially lead to problems with other consumers already online, but completely disabling offset persistence would prob be the cleanest solution

**Comment by Jeffail** [comment]
Yeah let's go with disabling the consumer group. The logic for the kafka input is already quite complex specifically around commits due to the checkpointer but hopefully this should be fairly quick and easy to add.

**Comment by mfamador** [comment]
And what about to have a parameter like the `-o` (offset) in `kafkacat` where we can set if we want to read from the end (`-o end`), from the beginning (-o begin) or from an absolute or relative value:
```  -o <offset>        Offset to start consuming from:
                     beginning | end | stored |
                     <value>  (absolute offset) |
                     -<value> (relative offset from end)
                     s@<value> (timestamp in ms to start at)
                     e@<value> (timestamp in ms to stop at (not included))```

**Comment by DeeJayBro** [comment]
What about disabling `auto.commit.offset`, so we can use the existing `start_from_oldest` to define the offset at each startup. Because no last offsets are saved in the Kafka, thus the user doesn't accidentally flood resources etc

**Comment by yev-dimo** [comment]
+1 for this request. disabling offset commit via explicit variable works for me. Specifying empty clientid works as well.

**Comment by kozelok** [comment]
Would use this feature as well!

**Comment by Jeffail** [comment]
Disabling commits might be a nice compromise. A risk there is that because you would still be joining a consumer group you are subject to partition rebalancing, and since we wouldn't have an offset saved it would mean that every time a rebalance occurs you would either introduce a flood of duplicates with `start_from_oldest`, or drop data without. My understanding is that rebalances can occur quite often under certain circumstances, and even when there's only one active client in the group.

I'm still in the mindset that the ability to disable consumer groups is so far the only clean solution here that doesn't introduce odd side effects and confusing behaviour.

This seems like quite a high demand feature so if I have time I'll take a look soon.

**Comment by Jeffail** [comment]
Okay so I've implemented this in https://github.com/Jeffail/benthos/commit/76264dfe8c6afba31b5383093ee97041578fc92b, you can now set the consumer group to be empty (`consumer_group: ""`). However, I _haven't_ enabled this for unexplicit partitions, so for example with `topics: [ foo ]` you will get an error if you don't have a consumer group specified, but `topics: [ foo:0-10 ]` will work (and consume partitions 0 through 10).

My reasoning for this is that it would be reasonable to expect in the case of `topics: [ foo ]` that if new partitions are created whilst Benthos is consuming that it would automatically consume those as well, and until that behaviour is implemented I'd rather not imply that it is.

We also don't have a way of specifying a specific offset to start from. I've considered expanding the topic syntax to allow for this but it'd need some design work, it could look something like `topics: [ foo:0:1020 ]`, not sure how we'd also offer timestamps.

If you're interested in any of these outstanding features then please open a separate issue.
