### ISSUE TITLE
Prometheus Push Gateway configuration

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#619]
I was trying to configure Benthos to use the Prometheus Push Gateway and, according to [the docs](https://www.benthos.dev/docs/components/metrics/prometheus#push-gateway), I need to set the `push_url` field:

> The field push_url is optional and when set will trigger a push of metrics to a Prometheus Push Gateway once Benthos shuts down. It is also possible to specify a push_interval which results in periodic pushes.

Since Benthos would be running only briefly, I reasoned that I don't need to set the `push_interval` too and was assuming that Benthos will simply emit metrics just before shutting down. Unfortunately, that's not the case, because [this code](https://github.com/Jeffail/benthos/blob/9cf647c8c6d2eb978c49881272ee9703be51b0e2/lib/metrics/prometheus.go#L151-L152) prevents the pusher from being initialised if `push_interval` is not set, so then no metrics will be emitted [on shutdown](https://github.com/Jeffail/benthos/blob/9cf647c8c6d2eb978c49881272ee9703be51b0e2/lib/metrics/prometheus.go#L415-L423).

I think it's desirable to adjust the code to allow the pusher to work even if `push_interval` is not set, but, otherwise, I'd also be OK with adjusting the docs to explicitly mention that `push_interval` is mandatory when setting `push_url`. WDYT?

**Comment by Jeffail** [comment]
Hey @mihaitodor, yeah I think it'd be fine to allow an empty `push_interval` in this case.
