### ISSUE TITLE
The `file` input should allow walking a directory

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#623]
I was testing copying files from a folder to another and I noticed that the [`files`](https://github.com/Jeffail/benthos/blob/1452d751f850999f5e47f80f1a465dae35f0c602/lib/input/files.go) input has been deprecated and the [`file`](https://github.com/Jeffail/benthos/blob/2b5ae3925faad91dfb141af4dacb9e87691a5050/lib/input/file.go) input is meant to replace it. However, the `file` input only supports [glob patterns](https://github.com/Jeffail/benthos/blob/2b5ae3925faad91dfb141af4dacb9e87691a5050/lib/input/file.go#L29) as input paths, which won't work if the passed in path points to a directory.

Under the hood, `files` calls [`filepath.Walk`](https://github.com/Jeffail/benthos/blob/2b5ae3925faad91dfb141af4dacb9e87691a5050/lib/input/reader/files.go#L52), but the `file` input doesn't attempt to do this. Is there any way to achieve the same functionality with the `file` input?

Also, the `file` input only [sets](https://github.com/Jeffail/benthos/blob/2b5ae3925faad91dfb141af4dacb9e87691a5050/lib/input/file.go#L43) `path` as metadata. If I use the `file` output, is it possible to use  bloblang to extract the filename from the `path`, so I can store the file directly in the output path?

**Comment by Jeffail** [comment]
Hey @mihaitodor, I'm hoping to eventually support super wildcards in the `file` input that'll allow you to walk a directory. However, since that's not done yet I'll mark this issue as v4 as we ought to have this solved before the `files` input is potentially removed.

For extracting the file name right now you'll need to do something slightly hacky like `meta("path").split("/").index(-1)`, but I can add proper methods to bloblang for parsing and chopping up paths.

**Comment by mihaitodor** [comment]
@Jeffail Thanks for confirming! Indeed, that hack is not ideal, since it's not platform independent. Would be great to consider exposing (some of) the [`filepath`](https://golang.org/pkg/path/filepath/) methods via Bloblang.

**Comment by mihaitodor** [comment]
Thank you for adding `filepath_split` and `filepath_join` so quickly in 42cb803! Looks great 💯

**Comment by Jeffail** [comment]
> When you say super-wildcards, do you mean using some 3rd party library, such as [go-zglob](https://github.com/mattn/go-zglob) or [doublestar](https://github.com/bmatcuk/doublestar)?

Yeah exactly, I was going to do some due diligence as to whether this solves all use cases and is also something we can maintain long term.

**Comment by Jeffail** [comment]
Super glob support is now in: https://github.com/Jeffail/benthos/commit/489338983649146d957b507649d8bb892cca0142 so you can walk a directory with stuff like `paths: [ "./foo/**/*" ]`.

**Comment by mihaitodor** [comment]
Oh, awesome! Thank you for getting back to this one Ash! Super-handy to have this feature.
