### ISSUE TITLE
Jepsen

### ISSUE THREAD

**Issue by bbrown** [Jeffail/benthos#627]
Have you considered getting Benthos [evaluated](http://jepsen.io/analyses) by Jepsen? I have no idea how expensive it is but maybe the community could fundraise it if we knew the cost involved and if you were interested in getting that done.

**Comment by Jeffail** [comment]
Hey @bbrown, I haven't really looked into it but I definitely wouldn't oppose an evaluation, I've marked this as a cool idea for now. If anyone fancies investigating and outlining the steps we'd need to take in this issue then please go ahead and I'll help whenever I can.

**Comment by bbrown** [comment]
Okay, I've sent him an email requesting the price and linking to this issue. I'll post the response and next steps, if any. Thanks!

**Comment by gedw99** [comment]
Is he the "Call me maybe" guy ????

**Comment by bbrown** [comment]
That's a side gig—pop music. The main gig is evaluating distributed systems for fault tolerance.

**Comment by bbrown** [comment]
I've received back his pricing and it's more than this community can bear. I still think it would be good to push Benthos to its limits but it'll have to wait.
