### ISSUE TITLE
Support for TLS client auth for kafka 

### ISSUE THREAD

**Issue by nwest1** [Jeffail/benthos#63]
I *think* this would be fairly straightforward, and useful for those in the unfortunate situation of having to use mutual tls authentication.

In addition to the configuration options and reading the client cert adding something like the following would do.

```go
return &tls.Config{
    Certificates: []tls.Certificate{cert},
    InsecureSkipVerify: c.InsecureSkipVerify,
    RootCAs:            rootCAs,
}, nil
```

**Comment by Jeffail** [comment]
Hey @nwest1, sounds reasonable. We could expose a tls config option `client_cert_files`, which would be an array of paths. I assume you already have a set up that would benefit from this, in which case if we create a branch with this feature would you be willing to test it?

**Comment by nwest1** [comment]
Would be happy to!

**Comment by ghballiet** [comment]
I'd be glad to participate in this as well, as I also need this feature. @Jeffail would you be open to just doing a PR review on this change, if I can get it in quickly?

**Comment by ghballiet** [comment]
@Jeffail PR: https://github.com/Jeffail/benthos/pull/71

**Comment by Jeffail** [comment]
Got this on a branch: https://github.com/Jeffail/benthos/tree/feature/tls-configs

Would be great if you both could try it out and confirm it's enough for your use case, I'm falling asleep at the keyboard but I'll merge into master and put a build out in the morning if there's no issues.

**Comment by Jeffail** [comment]
Released: https://github.com/Jeffail/benthos/releases/tag/v0.27.0

**Comment by Jeffail** [comment]
@nwest1 if you need more config fields for your use case then feel free to reopen this ticket.

**Comment by nwest1** [comment]
Was able to test this out just today - works like a charm. Additional config fields unneeded.
