### ISSUE TITLE
Output codec without delimiter

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#641]
Looking at the [available output codecs](https://www.benthos.dev/docs/components/outputs/file), I noticed that `all-bytes` [truncates](https://github.com/Jeffail/benthos/blob/d10ce3d96f0f313c79af7a7264f016b78d295c5f/internal/codec/writer.go#L71) on each message and `delim` [doesn't support](https://github.com/Jeffail/benthos/blob/d10ce3d96f0f313c79af7a7264f016b78d295c5f/internal/codec/writer.go#L58-L60) an empty delimiter.

Would you consider removing the non-empty delimiter restriction in the `delim` output codec? I need this when using the `chunker` input codec that I added in #640 for the use case of transferring a large file from Azure to a local file.

**Comment by Jeffail** [comment]
Ahh of course, rather than allow empty delimiters it's probably better for discovery if we add an explicit `append` codec, that'll simply write the raw data.

**Comment by mihaitodor** [comment]
Ah, `append`. Of course! I was struggling to figure out what to name it 😁  Coming right up!
