### ISSUE TITLE
Add JetStream support

### ISSUE THREAD

**Issue by smoothd** [Jeffail/benthos#646]
[JetStream](https://github.com/nats-io/jetstream) will be NATS Streaming's successor, replacing it eventually. JetStream is supported by [jsm.go](https://github.com/nats-io/jsm.go).

It would be great to have `jsm` Inputs and Outputs analogous to today's `nats_streaming` support.

[Edit] I'm happy to collaborate on this and to provide an initial PR if wanted.

**Comment by Jeffail** [comment]
Hey @smoothd, sounds good. The NATS APIs are usually very clean so I'm happy to add experimental support even if they're subject to change.

**Comment by bkcsfi** [comment]
@smoothd are you still interested in Jetstream for Benthos? 

It looks like the go client now has some jetstream support https://github.com/nats-io/nats.go but the api is a bit different than jsm.go

There are still some issues to be fixed..

**Comment by Jeffail** [comment]
It's happening https://github.com/Jeffail/benthos/tree/nats-jetstream, still waiting for a tagged release of https://github.com/nats-io/nats.go containing the new APIs before I merge it but I'll have the connectors prepared.

**Comment by bkcsfi** [comment]
awesome, thank you very much for working on this!

**Comment by Jeffail** [comment]
Awesome, they tagged a release https://github.com/nats-io/nats.go/releases/tag/v1.11.0, and now it's in: https://github.com/Jeffail/benthos/commit/90b2a62dfb204fd621a4392b22d4b438fcea928f

I'll put a release out soon.

**Comment by smoothd** [comment]
@Jeffail Wonderful, thank's a lot for the effort. Will take some time to try it out though since we still run on `nats-streaming`.
