### ISSUE TITLE
Kafka output topic interpolation

### ISSUE THREAD

**Issue by rucciva** [Jeffail/benthos#65]
Hi @Jeffail, sorry for bothering you again with small boring thing like this.

i'm just wondering wether you could turn kafka output `topic` config to support interpolation. 

Currently, all of my docker container logs--which are stored in syslog--are exported to one kafka topic using filebeat. I would like to use benthos to parse the syslog's program name to extract container name and/or image and export that parsed message to each different kafka topic so that future stream processing on a specific container logs don't need to receive and filter message from unrelated container, thus saving bandwidth.

**Comment by Jeffail** [comment]
Hey @rucciva, seems like a reasonable request.

**Comment by rucciva** [comment]
glad to hear that @Jeffail, looking forward to it

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/fde9ff6842ff6ee0984e1cecedabbdd5f46dc516
Released: https://github.com/Jeffail/benthos/releases/tag/v0.27.0
