### ISSUE TITLE
socket_server panic: send on closed channel

### ISSUE THREAD

**Issue by jicanghaixb** [Jeffail/benthos#650]
I use socket_server as input, benthos run in stream mode. benthos version v3.37.0.
i create a test task, and  run a client to send msg to socket_server. if i first stop client and last stop task, it seem ok. but, when i first stop task, because benthos colsed transactions which client cause panic.

example:
input:
  type: socket_server
  socket_server:
    network: "unix"
    address: "./test.socket"

panic: send on closed channel

goroutine 126 [running]:
github.com/benthos/lib/input.(*SocketServer).loop.func2(0x37257c0, 0xc000ca41e0, 0xc000c9adb0, 0x1)
        /media/vdb/workspace/src/github.com/benthos/lib/input/socket_server.go:215 +0x1d4
github.com/benthos/lib/input.(*SocketServer).loop.func3.1.1()
        /media/vdb/workspace/src/github.com/benthos/lib/input/socket_server.go:253 +0xda
github.com/benthos/lib/input.(*SocketServer).loop.func3.1(0xc0008c4e40, 0xc000cb44c0, 0x3697a00, 0xc000736140, 0x3725640, 0xc00026eb48)
        /media/vdb/workspace/src/github.com/benthos/lib/input/socket_server.go:275 +0x27c
created by github.com/benthos/lib/input.(*SocketServer).loop.func3
        /media/vdb/workspace/src/github.com/benthos/lib/input/socket_server.go:247 +0x6d

**Comment by Jeffail** [comment]
Hey @jicanghaixb, thanks for raising this. It's definitely a bug, I should have a fix and release this evening.

**Comment by Jeffail** [comment]
Fixed in https://github.com/Jeffail/benthos/commit/14b08a940799483264d61c305ecd78cffeafa2ec
