### ISSUE TITLE
GCS (Google Cloud Storage) support

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#652]
Would there be any interest in having support for GCS in Benthos (both input and output)? Their [API](https://pkg.go.dev/cloud.google.com/go/storage) [looks](https://github.com/GoogleCloudPlatform/golang-samples/blob/master/storage/objects/main.go) quite straightforward to use.

**Comment by Jeffail** [comment]
100%, I'd love to have more GCP connectors in general.

**Comment by mihaitodor** [comment]
Fixed by Ash in 9a99026.
