### ISSUE TITLE
Transform one input message into multiple different output messages

### ISSUE THREAD

**Issue by nenad** [Jeffail/benthos#664]
Hey ~Jeff~ Ash, first of all, thank you for building this amazing tool, it has saved me a lot of time.

Now, onto the question I could not find an answer in the docs, or maybe overlooked. As the title suggest, is it possible to get one input message, process it, and output multiple ones?

In my use-case I receive this JSON payload as input message:
```json
{
    "ts":"2021-02-11 08:06:30.316",
    "category":"SystemMonitor",
    "text":"System/Host/Health",
    "data":{
        "Resources":[
            {
                "ResourceType":"CPU",
                "ResourceID":"Total",
                "Total":100,
                "Used":0.12852253,
                "Unit":"%"
            },
            {
                "ResourceType":"CPU",
                "ResourceID":"Core0",
                "Total":100,
                "Used":0.2309811,
                "Unit":"%"
            },
            {
                "ResourceType":"CPU",
                "ResourceID":"Core1",
                "Total":100,
                "Used":0.02606398,
                "Unit":"%"
            },
            {
                "ResourceType":"CPU",
                "ResourceID":"NumCores",
                "Total":2,
                "Used":2,
                "Unit":"Count"
            },
            {
                "ResourceType":"PhysicalMemory",
                "ResourceID":"",
                "Total":4294426624,
                "Used":2088386560,
                "Unit":"Byte"
            }
        ]
    }
}
```
And I would like to insert multiple records in a database for each Resource Type, i.e.

|timestamp|resource_type|resource_id|total|used|unit|
|---|---|---|---|---|---|
|2021-02-11 08:06:30.316|CPU|Core0|100|0.2309811|%|
|2021-02-11 08:06:30.316|CPU|Core1|100|0.02|%|
|...|...|...|...|...|...|

Is this something Benthos can do, or is it not a "mundane" enough task? I'd appreciate any ideas you have, thanks!

**Comment by Jeffail** [comment]
Hey @nenad, this is definitely a boring task and very much up our street. This requires a two step process, the first is use Bloblang to map your individual messages as an array, then use the unarchive processor with the format `json_array` in order to break the array out into individual messages, there's an outline of it here: https://www.benthos.dev/docs/guides/bloblang/advanced#message-expansion

In your case it'll look something like this:

```yaml
pipeline:
  processors:
    - bloblang: |
        let doc_root = this.without("data")
        root = this.data.Resources.map_each($doc_root.merge(this))
    - unarchive:
        format: json_array
```

**Comment by nenad** [comment]
Thank you!
