### ISSUE TITLE
Support for HDFS

### ISSUE THREAD

**Issue by ajbosco** [Jeffail/benthos#67]
Are there any plans for supporting writing to HDFS? I'd imagine it would be similar to the S3 writer. I'd be interested in contributing, if it seems like a reasonable idea.

**Comment by Jeffail** [comment]
Hey @ajbosco, seems like a good fit. This library looks promising: https://github.com/colinmarc/hdfs, might be worth exploring use cases for reading as well.

**Comment by ajbosco** [comment]
👍 Yep, I've been working with that library on something similar to this and it works well. I'll get started on this soon.

**Comment by Jeffail** [comment]
Implemented: https://github.com/Jeffail/benthos/commit/1928fb60bfd3113b54e3d438c8f03265c6a25a5d
