### ISSUE TITLE
Add cli flag for arbitrary config field override

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#670]
Right now we have a configuration file made for the docker distribution that adds an environment flag for every single field in the Benthos config spec: https://github.com/Jeffail/benthos/blob/master/config/env/default.yaml

The only purpose of this file is to enable env var based configuration of docker deployments in extremely simple pipelines. For example:

```sh
docker run --rm \
	-e "INPUT_TYPE=http_server" \
	-e "OUTPUT_TYPE=kafka" \
	-e "OUTPUT_KAFKA_ADDRESSES=kafka-server:9092" \
	-e "OUTPUT_KAFKA_TOPIC=benthos_topic" \
	-p 4195:4195 \
	jeffail/benthos
```

However, the code that generates this file is rather ugly and the config that it produces has various flaws. A better approach to convenient field setting would be to add a cli flag that we can specify any number of times that allows us to set a field (identified by a dot path) to any arbitrary value. The above example would look like this:

```sh
docker run --rm \
	-p 4195:4195 \
	jeffail/benthos \
          --set "input.type=http_server" \
          --set "output.type=kafka" \
          --set "output.kafka.addresses.0=kafka-server:9092" \
          --set "output.kafka.topic=benthos_topic"
```

The implementation of this doesn't need to be overly clever, we could likely get away with parsing a config as normal, marshalling it back into a generic structure, using Gabs to set each dot path, then marshal and reparse the config again. String types are easy here, but we will need to be careful about booleans and numbers, either by parsing them explicitly or by simply returning an error and stating we only support strings.

**Comment by mihaitodor** [comment]
Maybe this is a non-issue for most configs, but I wonder if it has the potential to hit some command line limits. For example, on Windows, the limit is [8191 chars](https://stackoverflow.com/questions/3205027/maximum-length-of-command-line-string). On other OSes, `getconf ARG_MAX` returns:
- `262144` on my OSX, which I guess is big enough for dev tasks.
- `131072` on the Alpine Docker container, which feels a bit on the small side.
- `2097152` on the Busybox, Ubuntu, Debian and Centos Docker containers.

**Comment by Jeffail** [comment]
Forgot to update but this is now done.
