### ISSUE TITLE
Exiting if creds / tokens expire after a while

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#684]
Is there any mechanism at the input/output level to instruct Benthos to stop trying to read / write messages and exit if it gets an invalid / expired credentials error? I'd be interested to implement this for Azure (for now). Or can it be achieved somehow with some try / catch config?

**Comment by Jeffail** [comment]
I don't think this is possible via configuration, but you could implement this quite easily by returning `types.ErrTypeClosed` from the `ConnectWithContext` method when the credentials fail. That shouldn't be the default but maybe we could introduce some sort of `shutdown_on_connection_error` field for inputs.

**Comment by mihaitodor** [comment]
Wonderful, thanks for the hints Ash! :)
