### ISSUE TITLE
Restrict which metadata fields are sent to outputs

### ISSUE THREAD

**Issue by Jeffail** [Jeffail/benthos#685]
The following outputs currently support enriching messages sent with metadata:

- `kafka`
- `aws_s3`
- `amqp_0_9`
- `redis_hash`
- `redis_streams`
- `aws_sqs`
- `gcp_pubsub`
- `http_client`

However, sometimes there are metadata fields we'd like to use for interpolation but not add to the resulting message sent over the output. In order to solve this we have three options:

1. Add a "private tier" to metadata given a certain key prefix (`_` is a common prefix for private variable names), private metadata can be explicitly referenced but will always be excluded from outputs
2. Add a field `include_meta_pattern` which is a metadata key pattern to include in the output messages
3. Add a field `exclude_meta_pattern` which is a metadata key pattern to exclude in the output messages

Options 2 or 3 are "safer" in that they're capable of being implemented in a backwards compatible way, but also add another config field to all of the above outputs. Option 1 is passive and (I think) intuitive but could trip some users up that aren't expecting it, and in the unlikely case where a user wants to send metadata keys with our chosen prefix there wouldn't be a work around to solving it.

I'm currently leaning towards option 3.

**Comment by mfamador** [comment]
Maybe having both 2 and 3 mutually exclusive would be a good solution: if we'd specify the `include` we'd just keep the ones matching the pattern if by the contrary we'd specify `exclude` we'd keep all metadata unless it'd match the pattern.

**Comment by Jeffail** [comment]
Starting off with just `exclude_prefixes`, which is a static list of key prefixes to ignore: https://github.com/Jeffail/benthos/commit/a4d9dfc23b6fcc13c28f6d45a4ea94eb6e28ca3e, we can expand that later if/when it doesn't satisfy a particular use case.

@dmoeff, we could potentially do things that way as messages carry a `Context` which we could add arbitrary values to. However, I'm keen to try and solve this without adding a new "tier" of metadata as I think it might be difficult to document the differences and it'd mean a whole new suite of tooling would need to be built out.

If this solution turns out to be confusing or awkward to deal with then we can revisit but I think this should be good enough for now.
