### ISSUE TITLE
UCS-2 configuration yaml file does not interpolate environment variables

### ISSUE THREAD

**Issue by serkrebs** [Jeffail/benthos#693]
I created a yaml configuration file for benthos. It seemed to work perfectly on Windows except for interpolation of environment variables in the configuration file. I have included a shortened sample configuration file which demonstrates the problem.

To replicate the problem
1. set an environment named TEMP
2. run benthos with http_test2.yaml (e.g. benthos.exe -c http_test2.yaml)
3. use postman or curl to POST any body text to localhost:4195

Benthos will create a file named a-${TEMP}-foo.barf without replacing ${TEMP} with the environment variable value.

System: Windows 10
Benthos version: 3.42.0
Config file encoding: UCS-2 LE BOM (UTF-16 with little-endian byte-order-mark)

[http_test2.zip](https://github.com/Jeffail/benthos/files/6086391/http_test2.zip)

**Comment by Jeffail** [comment]
Hey @serkrebs, thanks for the details and the example config, I've got this reproduced locally and will take a look.

**Comment by Jeffail** [comment]
@serkrebs is it generally a pain to save files as utf-8 on windows? To do this properly it looks like I'll need to convert the config bytes into utf-8, in which case I can either attempt that with (possibly dodgy) heuristics to determine the provided encoding, or the safer approach would be to expose this as some sort of cli flag like `benthos -c ./config.yaml --encoding ucs-2` so that it's explicit. Would that flag be useful to you?

**Comment by serkrebs** [comment]
Thank you for your response.

I didn't actually intend to use UTF-16 and I'm not certain how this one config file got that way. But I had been using it successfully for days and it only caused me some heartburn when it refused to interpolate the environment variables I added today. It took me a few hours to determine the root cause. It was a very strange experience because absolutely nothing else (VS code, Benthos, Windows Explorer) gave me any indication how this one config file was different from all the others.

From my perspective, a nice error message such as this one would be very welcome and would have saved me half the day:

"Look, you bonehead, nobody uses UCS-2 in configuration files. Change it to UTF-8 this moment. Your mother is forever terribly ashamed of you notwithstanding the manner in which you resolve this fatal error."

Thanks for your consideration,
Randall Krebs

**Comment by Jeffail** [comment]
What I've done is add a lint when you load a config: https://github.com/Jeffail/benthos/commit/ab4141fefc474bcb0c2335f0e95365ee1dc999b3, which prints `Detected invalid utf-8 encoding in config, this may result in interpolation functions not working as expected`. It's a lint error which means you can still force benthos to load it with the `--chilled` flag.

**Comment by serkrebs** [comment]
Brilliant! (hoping I can comment without re-opening.)
