### ISSUE TITLE
Benthos Kafka Component and Schemas

### ISSUE THREAD

**Issue by brandongilzean** [Jeffail/benthos#699]
Hi,

Does benthos kafka input have the ability to use schema validation (avro schemas). Also does this have the ability to deserialization from kafka as well?

**Comment by Jeffail** [comment]
Hey @brandongilzean, there's a general purpose avro processor for converting messages from a schema to JSON and back: https://www.benthos.dev/docs/components/processors/avro

However, there are known limitations that are waiting to be worked on: https://github.com/Jeffail/benthos/issues/381, which relate to schema validation from the confluent platform. There are work arounds (https://github.com/Jeffail/benthos/issues/584) but they aren't great.

**Comment by Jeffail** [comment]
Ongoing discussion over in https://github.com/Jeffail/benthos/issues/381
