### ISSUE TITLE
AMQP as input nevers ack it's messages..

### ISSUE THREAD

**Issue by ThomasADavis** [Jeffail/benthos#7]
In testing, I found that if you use AMQP (RabbitMQ) as an input, the messages will never get ACK'd in rabbitmq, which causes a backlog to build.

In the AMQP input file, you've turned off AutoACK, but never ack any messages as being delivered.

You also never set a QOS, which then defaults to 0 in the rabbitmq.  This also could cause problems if multiple benthos are sharing the same queue, or performance problems in heavy queue traffic.

**Comment by Jeffail** [comment]
Hey @ThomasADavis, sorry for the delayed response, this issue slipped under my radar. I'll take a look next time I get a chance, or I'd be happy to take a pull request.

I'm still fairly unfamiliar with AMQP so thanks for highlighting these issues.

**Comment by Jeffail** [comment]
Hey @ThomasADavis, had a quick moment this afternoon to push a fix for this but haven't got time to test today. If you give it a try then let me know how it goes.

**Comment by sukria** [comment]
Hey there. I'm also hit by this bug, I'm going to give your fix a test.

**Comment by ThomasADavis** [comment]
I will not have time for several weeks to work on this.  A quick glance at the code it does appears to be correct.

**Comment by sukria** [comment]
Works for me! Thanks for the fix.
