### ISSUE TITLE
http server timing out

### ISSUE THREAD

**Issue by sathiya-mit** [Jeffail/benthos#70]
First of all I would like to say thank you for making benthos 👍 

I have configured benthos.yaml with http server as input and kafka as output and few processors in pipeline. All is fine while http client request is minimal.

When I increased to 20 parallel http client request, I could see http timeout on client side, even after increasing http server timeout to 20 seconds. But I found almost all request reached to kafka.

But when I increased http client parallel request to 50, I could see almost 50% data loss in kafka along with http timeout on client side.

In logs I didn't see any warnings/errors. I am running benthos on 8 CPU and I configured 8 threads for pipeline processor.

Interestingly when I change the output to file, I don't see any data loss even for 50 parallel http request.

My question is how can I isolate/debug the issue. problem could be in both the places 

1) kafka client (i.e. benthos output) 
2) kafka server side

Appreciate your help !!! Thanks in advance 👍 

Below is my benthos.yaml snippet.

type: kafka
kafka:
  ack_replicas: false
  addresses:
  - xxxxx:9092
  client_id: benthos_kafka_output
  compression: none
  key: ""
  max_msg_bytes: 1e+06
  round_robin_partitions: false
  target_version: 1.0.0
  timeout_ms: 20000
  tls:
    cas_file: ""
    enabled: false
    skip_cert_verify: false
  topic: xxxxxxx

logger:
  prefix: benthos
  level: DEBUG
  add_timestamp: true
  json_format: true

**Comment by Jeffail** [comment]
Hey @sathiya-mit, there's a general guide for configuring pipelines for maximum throughput here: https://github.com/Jeffail/benthos/blob/master/docs/concepts.md#maximising-io-throughput

Kafka specifically benefits a lot from batching.

**Comment by sathiya-mit** [comment]
thanks @Jeffail It worked. I did both batching and increased number of parallel output sinks. I tested up to 200 parallel http connection.

BTW is that make any sense to increase http input source like mentioned below

input:
  type: broker
  broker:
    copies: 4
    inputs:
    - type: http_server
      http_server:
        address: ""
        cert_file: ""
        key_file: ""
        path: /post
        timeout_ms: 20000
        ws_path: /post/ws
      processors:
      - type: combine
        combine:
          parts: 10
buffer:
  type: none
  none: {}

**Comment by Jeffail** [comment]
@sathiya-mit, great! Just use a single `http_server`, it's a special case as each request handler will be running on its own goroutine, so you wouldn't benefit from having multiple instances, they would also overwrite each others' endpoints.
