### ISSUE TITLE
bloblang - string method format question

### ISSUE THREAD

**Issue by luck02** [Jeffail/benthos#700]
Wondering why this:

```
        root.meta.s3_path = "%s%s".format(root.meta.s3_prefix, root.meta.event_name)

```

results in:
```
{
"meta": {
        "event_name": "some-event-name",
        "s3_prefix": "failed_validation/",
        "s3_path": "%!s(<nil>)%!s(<nil>)"
   }
}
```

Not sure what I'm missing there,

Thanks!

**Comment by Jeffail** [comment]
Hey @luck02, `root` on the right hand side currently doesn't have any special meaning and therefore `root.meta.s3_prefix` is short-hand for `this.root.meta.s3_prefix` (querying the input document). If you want to reuse fields that you've already mapped then you would need to use variables like this:

```coffee
let s3_prefix = this.some.path.or.something
let event_name = this.some.other.path

root.meta.s3_prefix = $s3_prefix
root.meta.event_name = $event_name
root.meta.s3_path = "%s%s".format($s3_prefix, $event_name)
```

Eventually the plan will be to make `root` on the right-hand side a keyword. However, there's still some debate as to whether it should refer to the root of the new document being constructed (as was your intuition here) or the absolute root of the input document being mapped from (useful in cases where the context is changed).

Given the feedback I've got so far I think having `root` refer to the document that's being constructed wins out. At the very least, allowing paths like `root.foo.bar` on the right-hand side is very confusing and should be dealt with ASAP, either by returning a compile error (for now) or with the new behaviour.

**Comment by luck02** [comment]
Hi @Jeffail, apologies I missed something that's probably important,  see first two lines in the below snippet

```
        root.event = this
        root.meta = meta()

        meta = deleted()

        root.meta.s3_path = "%s%s".format(root.meta.s3_prefix, root.meta.event_name)
```

Which is why I presumed that would work.  

I'll pull the variables directly out of meta() before deleting it.  I'm deleting it because some of the meta keys mess up the s3 upload (they become s3 headers, and some of them contain contents that are disallowed)

Here's the full snippet, just testing it now:

```
        root.event = this
        root.meta = meta()
        let event_name = meta("event_name")
        root.meta.processing_time = timestamp_unix()

        meta = deleted()
        meta data_event_consumer_rev = "0.0.0"

        let validation_status = if meta("schema_passed_validation").contains("false") { 
          "failed_validation/" 
        } else {
          "raw/"
        }  

        root.meta.s3_path = "%s %s".format($validation_status, $event_name)
        meta s3_prefix = root.meta.s3_path
```

which now yields:
```
"meta": {
        "ValidEventTypeName": "True",
        "event_name": "event_name",
        // kafka metadata blargh
        "processing_time": 1615563570,
        "s3_path": "failed_validation/ event_name",
        "schema_passed_validation": "false",
        "schema_validation_errors": "etc"
    }
```

I'm still a bit fuzzy on the issue as I'd created root.meta.[etc] before referencing them. 

In any case it works so i'm out of those particular woods. 

Thanks a bunch

**Comment by Jeffail** [comment]
This is phase one: https://github.com/Jeffail/benthos/commit/93884968bc6c2222c8b5b6309e627fe1c4623b9f, basically you'll get an error message if you try and use `root.foo` on the right hand side.

The next phase will be to actually implement `root` on the right hand side. It's very quick to implement but I want to let this first phase roll out and exist in the wild for a bit before we fully commit.

**Comment by luck02** [comment]
Thanks @Jeffail much appreciated!
