### ISSUE TITLE
Question about checkpoint.Capped behavior

### ISSUE THREAD

**Issue by greysond** [Jeffail/benthos#701]
I've been reading through the code for the [`checkpoint.Capped`](https://github.com/Jeffail/benthos/blob/master/internal/checkpoint/capped.go#L20) implementation to understand how the `checkpoint_limit` configuration worked on the `kafka` input and I _think_ I found some undesirable behavior.

In kafka, compacted topics can have some pretty wild differences in offsets from one message to the next, but I don't think `checkpoint_limit` takes this into account, which can break batching.

Here's a test that fails where I would expect `checkpoint_limit: 2` to allow two "sequential" offsets `1000` and `2000` through:
```golang
func TestBigJumpsMore(t *testing.T) {
	c := NewCapped(2)
	assert.Equal(t, 0, c.Highest())

	ctx, done := context.WithTimeout(context.Background(), time.Second*5)
	defer done()

	require.NoError(t, c.Track(ctx, 1000))
	assert.Equal(t, 0, c.Highest())

	require.NoError(t, c.Track(ctx, 2000))
	assert.Equal(t, 0, c.Highest())

	v, err := c.Resolve(1000)
	require.NoError(t, err)
	assert.Equal(t, 1000, v)
	assert.Equal(t, 1000, c.Highest())

	v, err = c.Resolve(2000)
	require.NoError(t, err)
	assert.Equal(t, 2000, v)
	assert.Equal(t, 2000, c.Highest())
}
```

I just want to make sure this behavior isn't desired before I attempt a workaround.

**Comment by Jeffail** [comment]
Hey @greysond, yeah this ought to be expanded to allow for any range between sequential offsets. It might need a bit of a refactor, it's been a while since I wrote the checkpointer but I probably did it this way for a reason. The only other component that uses this is the `aws_kinesis` input, but it won't be impacted since it has a (slightly gross) wrapper around this to account for the fact that the shard iterators are arbitrarily long numbers.

**Comment by greysond** [comment]
Mind if I take a crack at it? And how would you feel about a linked-list implementation?

**Comment by Jeffail** [comment]
Go for it, any implementation is fine but keep an eye on the benchmarks. It doesn't need to be super efficient but it'd be nice not too regress too far.

**Comment by greysond** [comment]
Should it be assumed that `Capped.Track(ctx, offset)` can be called from more than one goroutine? If not and there will only ever be one goroutine waiting on that call (like a sarama partition consumer), I have a much simpler solution.

**Comment by Jeffail** [comment]
Yes, but `Resolve` can be called from any number of goroutines. Although I wouldn't be opposed to breaking the mutex out when needed.

**Comment by Jeffail** [comment]
Solution merged: https://github.com/Jeffail/benthos/commit/7cccc3002b60b71c6efd316810f15af458ff6285
