### ISSUE TITLE
Capture path in http_server input

### ISSUE THREAD

**Issue by abasse** [Jeffail/benthos#720]
Is it possible to extract parts of the path of http_server input?
eg.

input:
  http_server:
    address: ""
    path: /post
    allowed_verbs:
      - GET
    timeout: 5s
    rate_limit: ""

I would like to call, http://localhost:4195/post/foo/123456 and to use the parts of the path ("foo" and "123456") in the following processing steps.

Thanks for your help.

**Comment by Jeffail** [comment]
Hey @abasse, not currently but it can easily be added as a metadata field.

**Comment by abasse** [comment]
Hi @Jeffail, that would be fantastic. Something you can consider for the next release? :)

I also would like to say **thank you**, Benthos is fantastic!
