### ISSUE TITLE
Google Cloud Storage - Issue with large files

### ISSUE THREAD

**Issue by karankap** [Jeffail/benthos#722]
Hi,

I am trying to read large files from a GCS bucket and push the content to GCP PubSub. The file is a CSV of size ~150 MB (800K lines).

The behaviour I notice is that after reading few lines from the CSV and pushing to PubSub, the container just exits with the message: "Pipeline has terminated. Shutting down the service". For small files (size in few KBs), the complete file content is published successfully to PubSub.

I tried with files of comparatively less size (~30 MB) and found a similar behaviour, after publishing few lines, the container just exited.

I am deploying using docker, below is the benthos config YAML file

```
input:
  label: gcs
  gcp_cloud_storage:
    bucket: my-personal-bucket
    prefix: 123/big_file_data_1030.csv
    codec: lines
output:
  label: pubsub
  gcp_pubsub:
    project: my-personal-project
    topic: benthos_test
    max_in_flight: 25
logger:
  prefix: benthos
  level: ALL
  format: json
  add_timestamp: true
  static_fields:
    '@service': benthos
```

Here are some logs from the container
```
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"gcs","level":"TRACE","message":"Consumed 1 messages from 'gcp_cloud_storage'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Attempting to write 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Attempting to write 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"gcs","level":"DEBUG","message":"Waiting for pending acks to resolve before shutting down."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"pubsub","level":"TRACE","message":"Successfully wrote 1 messages to 'gcp_pubsub'."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"gcs","level":"DEBUG","message":"Pending acks resolved."}
{"@timestamp":"2021-04-02T13:27:10Z","@service":"benthos","component":"benthos","level":"INFO","message":"Pipeline has terminated. Shutting down the service."}
```

I have tried multiple codecs; lines, auto, csv but found same behaviour. Also, tried with increasing the memory and cpu for the docker container but that also didn't help.

I understand that the feature is still in experimental mode, but just wanted to know if I am missing something in the config that is causing this behaviour or does it seem to be an issue with the benthos GCS input.

**Comment by Jeffail** [comment]
Hey @karankap, thanks for raising this, your config looks fine so this is either an issue with the `gcp_cloud_storage` input not fully consuming the file, or it could be that the `gcp_pubsub` isn't flushing all messages before the pipeline terminates. Does the number of `Successfully wrote 1 messages to 'gcp_pubsub'.` log lines match the number of lines within the file? I should be able to reproduce this locally but that'd help narrow it down.

**Comment by karankap** [comment]
Hi @Jeffail, no the number of “Successfully wrote 1 messages to gcp_pubsub” don’t match the actual number of lines in the file.

**Comment by Jeffail** [comment]
Thanks @karankap, got it fixed in: https://github.com/Jeffail/benthos/commit/38daec51af033f8f73d69e8f6ee3f9e82d70d467, the context used for consuming objects was a short lived one, so the reader was closing early.

I'll likely have the next release out some time next week, but if you're blocked on this input let me know and I can get a patch release out earlier.

**Comment by karankap** [comment]
Thanks @Jeffail, if its possible to give a patch earlier please, that would certainly help. I need to work on something urgent.

**Comment by Jeffail** [comment]
@karankap will do, in the meantime if you're deploying via docker there's a tag `edge` which is built nightly and includes this fix https://hub.docker.com/layers/jeffail/benthos/edge/images/sha256-e1308076da6ef5eef821118a88e734fc56119d3f8cd15258528982d4272185a5?context=repo

**Comment by karankap** [comment]
Thanks a lot @Jeffail, I used the tag `edge` and it worked like a charm. 

I will switch to `latest` once this gets released.
