### ISSUE TITLE
GPL scans being triggered by hdrhistogram-go

### ISSUE THREAD

**Issue by iluminae** [Jeffail/benthos#729]
so `github.com/HdrHistogram/hdrhistogram-go@v1.0.0` lists `github.com/golangci/golangci-lint` in its go.mod file, which is GPLv3. Our lawyers will not allow us to use anything that uses GPL in a binary that gets used in production.

The good news is `github.com/HdrHistogram/hdrhistogram-go@v1.0.0` pulling in `github.com/golangci/golangci-lint` looks like a mistake (its a tool that is used in the Makefile, not a real dep). Upgrading to `github.com/HdrHistogram/hdrhistogram-go@v1.0.1` or newer removes that, and the scan would pass.

I imagine this is an issue for other business users of benthos - thanks in advance for looking into this.

**Comment by Jeffail** [comment]
Hey @iluminae, thanks for raising this, upgraded: https://github.com/Jeffail/benthos/commit/ae101767715cc0ebf36c2c7c977508e4b2077957, and I'll put a release out this evening.

**Comment by Jeffail** [comment]
Released: https://github.com/Jeffail/benthos/releases/tag/v3.44.0
