### ISSUE TITLE
Add elseif to bloblang

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#748]
Currently, it's possible to use `match` for this purpose, but I'm not sure if it can cover all possible cases. It would be handy to support `elseif` (or `else if`) as well, in case something like `if... elseif... else...` is needed.

**Comment by Jeffail** [comment]
Done: https://github.com/Jeffail/benthos/commit/da5804fb86bfa7437075e690f098f366a359f912

**Comment by mihaitodor** [comment]
Thank you so much Ash for the quick resolution! I was trying to see how this could be implemented, but it does look like it’s a bit more involved than just mixing in some extra combinators. Really easy to follow, though.

**Comment by Jeffail** [comment]
No worries, probably would've been a good one to do on stream but I'm in my cozy evening wear so it wouldn't be proper. The old parser was pretty long and gross so I ended up pulling it out into three separate ones.

**Comment by mihaitodor** [comment]
Hahahah, that’s OK. Didn’t mean to mess up your evening. Thanks again!
