### ISSUE TITLE
Feature Request: Configured rate_limits emit metrics 

### ISSUE THREAD

**Issue by davidshrive** [Jeffail/benthos#768]
This would be helpful to allow you to easy observe if you are hitting your configured rate limits.

**Comment by Jeffail** [comment]
I'm thinking we'll have a counter for the number of times a rate limit is checked and another counter of the discrete times a rate limit gets activated.

**Comment by Jeffail** [comment]
Done https://github.com/Jeffail/benthos/commit/276e1d62574b6604bf2d03a31f479cd4f885bd29
