### ISSUE TITLE
Possibility of signing a JSON Web Token (JWT)

### ISSUE THREAD

**Issue by manute** [Jeffail/benthos#769]
Hey 👋 , just opening this issue because I haven't seen this option in the docs.  

So I just need to sign a JWT token, specifically for [this](https://docs.github.com/en/developers/apps/authenticating-with-github-apps#authenticating-as-a-github-app),  and I could not find any option like that in the http component nor in the bloblang encoding docs.  
Do you think is feasible to do with other component or this option is still not available? 

Thanks in advance!

**Comment by Jeffail** [comment]
Hey @manute, if you have a generated token you can add it as a header to your requests:

```yaml
http:
  url: TODO
  verb: POST
  headers:
    Authorization: "Bearer <your generated jwt>"
```

And the header values support interpolation so if you extract the token from somewhere as metadata you can add it to the request with something like `Authorization: 'Bearer ${! meta("jwt") }'`. I think there are some users out there that configure token renewal as part of their pipeline and store/retrieve it in [caches](https://www.benthos.dev/docs/components/caches/about), but it's a bit fiddly.

I'll mark this as an enhancement and we can take a look at possibly adding this to HTTP components similar to the existing oauth fields.

**Comment by manute** [comment]
Thanks @Jeffail for the answer and that would be ideal. I will see if I can create a PR for this.

**Comment by manute** [comment]
Hey @Jeffail, I've created a [PR](https://github.com/Jeffail/benthos/pull/772) for this. Lemme know if the approach in the PR is what you had in your mind.

**Comment by Jeffail** [comment]
:tada:
