### ISSUE TITLE
Set different log level on retries

### ISSUE THREAD

**Issue by george-koulouris-form3** [Jeffail/benthos#770]
We are reading from an SQS queue and writing to an S3 bucket (`try`+`aws_s3` output). When a write to S3 fails (e.g. due to network blips), then a message with level `error` is logged both by the `s3` and the `try` components. However, the operation is retried and ultimately succeeds.

In this case, should we not log with level `warning`?

Happy to share our config, if that'd be helpful :)

**Comment by Jeffail** [comment]
Hey @george-koulouris-form3, that's an interesting one. I'd say you're correct given the message is (eventually) successfully delivered. It's probably worth doing a general audit of how/when/why various logs occur at the output level as it's been a while.

**Comment by george-koulouris-form3** [comment]
Thanks @Jeffail - would you be open for us opening a PR to fix this one? Or is this something you'd preferring doing at your own time?

**Comment by Jeffail** [comment]
Sure, go for it, let me know if you have any questions.
