### ISSUE TITLE
Add Source & Sink Support for LiftBridge

### ISSUE THREAD

**Issue by gc-ss** [Jeffail/benthos#778]
Although there's already support for NATS, NATS JetStream, NATS Streaming Support in benthos, it would be awesome to have Source & Sink Support for LiftBridge.

Here's the sister issue in liftbridge to help track the same. I see opportunity in synergy between both: https://github.com/liftbridge-io/liftbridge/issues/346

Here's a short writeup for why liftbridge as a parallel implementation of NATS Streaming is actually valuable: https://liftbridge.io/docs/faq.html#why-was-it-created

**Comment by Jeffail** [comment]
Hey @gc-ss, I'd love to have Liftbridge support, hoping to get around to it soon. There's an existing issue open for this https://github.com/Jeffail/benthos/issues/295 so closing this one.

**Comment by gc-ss** [comment]
Makes sense. Thank you Jeff
