### ISSUE TITLE
Update the dgrijalva/jwt-go library

### ISSUE THREAD

**Issue by mihaitodor** [Jeffail/benthos#779]
PR #772 introduced a slightly outdated version of `dgrijalva/jwt-go` which might require some critical patches (for example [this one](https://github.com/dgrijalva/jwt-go/issues/463)). Unfortunately, the original author doesn't have time to maintain it so there is a conversation happening [here](https://github.com/dgrijalva/jwt-go/issues/462) to figure out a permanent home for this popular library. I have subscribed to this conversation and will submit a PR with the updated lib once the dust settles.

**Comment by oxisto** [comment]
Just saying, hi! We are setting up a community effort clone of the aforementioned library at http://github.com/golang-jwt/jwt . We are still in the process of setting everything up, but we made great progress. https://github.com/golang-jwt/jwt/pull/12 will fix the mentioned issue.

**Comment by mihaitodor** [comment]
Thank you very much @oxisto! I'll keep an eye on it.

**Comment by oxisto** [comment]
We just released `v3.2.1` with a fix. https://github.com/golang-jwt/jwt/releases/tag/v3.2.1
