### ISSUE TITLE
How about adding dotenv to benthos

### ISSUE THREAD

**Issue by wirtsi** [Jeffail/benthos#791]
Not sure if this is go thing or not ... but it might be nice to add a dotenv parser to the project (eg. https://github.com/joho/godotenv)

We are building a rather large project with a number of ENV vars that need to be set (mostly hostnames, credentials, etc).

During production these vars are injected automatically, during development it would be nice to have them read out from a local .env file (which is not commited to git)

**Comment by nikosgpet** [comment]
That would be a great feature :) I've been battling with setting up the environment for the past day, it would be nice if it was a file we could pass to benthos during it's startup.

**Comment by Jeffail** [comment]
Done https://github.com/Jeffail/benthos/commit/c58f76e313b6ec147bcc270323e87a25c261a655
