### ISSUE TITLE
NATS Jetstream Support 

### ISSUE THREAD

**Issue by mdfranz** [Jeffail/benthos#794]
NATS Streaming will be deprecated  in June 2023 per https://github.com/nats-io/nats-streaming-server

NATS 2.2 includes JetStream https://docs.nats.io/whats_new_22 as the NATS persistence implementation going forward 

https://docs.nats.io/jetstream/jetstream

**Comment by Jeffail** [comment]
Hey @mdfranz, there's an input (https://www.benthos.dev/docs/components/inputs/nats_jetstream) and output (https://www.benthos.dev/docs/components/outputs/nats_jetstream) ready to try in the current latest release. The docs are semi hidden as they're marked as experimental while I gain feedback. If you get a chance to try them out let me know, I'm especially interested in any missing features or configuration that people want.

**Comment by mdfranz** [comment]
Sweet I missed them, so will take a look! I'm working on messaging chapter for an upcoming OReillly book that includes Kafka, NATS, and RabbitMQ and plan to use benthos as one of the labs, so wanted to make sure JetStream was covered!

**Comment by Jeffail** [comment]
Awesome! Let me know if I can help at all.
