### ISSUE TITLE
Feature request: LZ4 support in compress/decompress

### ISSUE THREAD

**Issue by citrin** [Jeffail/benthos#799]
Please add LZ4 support in compress/decompress processors. It offers much higher decompression speed than snappy with slightly higher compression rate [1]. There is a pure-go LZ4 implementation available [2] - it should be easier to add it compare to C library bindings.

[1] https://www.percona.com/blog/2016/04/13/evaluating-database-compression-methods-update/
[2] https://github.com/pierrec/lz4

**Comment by mihaitodor** [comment]
@citrin Thank you for the feature request! I created a PR for it (#800) in case @Jeffail would like this addition.
