### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by joeblew99** [Jeffail/benthos#8]
This is a pretty cool lib. Kind of surprised there are not more issues.

I want to use NATS as my central control plan to talk to micro services but also to send messages to clients over websockets.

I can see that this lib can help me with decoupled pipelines and orchestration but am wondering if any thought using this with websockets has been attempted.

There is a similar but different project by IBM in golang and Js running inside a golang Js VM that has some relationship to this project too and do worth adding it here as maybe people are interested. It's more concerned with many database types and doing pipelines across them.
It's also decoupled at runtime because of the Js aspects.

https://github.com/compose/transporter

Anyway hope I can get some feedback on the websockets aspect :)

**Comment by Jeffail** [comment]
Hey @joeblew99, thanks! Websocket support is fairly easy to add, both as an input and as an output. I can likely do it in a about an hours work or so when I get a chance. I started winding down on developing available connectors until people started requesting them, but they are super easy to implement.

**Comment by joeblew99** [comment]
thanks @Jeffail 

Here is a basic test harness of the ideas to get the ball rolling.. Great work by github.com/orus-io.


````
# see readme as a combination of bits. See stack

# go get -u github.com/orus-io/nats-websocket-gw

ECHO_GO_PATH=github.com/labstack/echo
ECHO_FILE_PATH=${GOPATH}/src/${ECHO_GO_PATH}

PROXY_GO_PATH=github.com/orus-io/nats-websocket-gw
PROXY_FILE_PATH=${GOPATH}/src/${PROXY_GO_PATH}


check:

	@echo ${GOPATH}

	@echo "echo -- "
	@echo ${ECHO_GO_PATH}
	@echo ${ECHO_FILE_PATH}

	@echo "proxy -- "
	@echo ${PROXY_GO_PATH}
	@echo ${PROXY_FILE_PATH}


dep:

	go get -u ${ECHO_GO_PATH}/...

	go get -u ${PROXY_GO_PATH}


dep-clean:

	rm -rf ${FILE_PATH}

run:

	# fire up classic gnatsd
	gnatsd && go run main.go


````

**Comment by Jeffail** [comment]
Hey @joeblew99, it took me a while to get around to this but we now have websocket support both as clients and on the `http_server` inputs and outputs.
