### ISSUE TITLE
Clarification on branch documentation

### ISSUE THREAD

**Issue by nikosgpet** [Jeffail/benthos#808]
I think it would be great if the branch documentation contained a simple example with an http request to understand how it works, showcasing the input and the output produced. Without an example of input & output, it can take a while to understand how it works.

**Comment by Jeffail** [comment]
Hey @nikosgpet, thanks for raising this, the docs can definitely be improved.

**Comment by Jeffail** [comment]
Updated docs: https://github.com/Jeffail/benthos/commit/2b7e7eacf6296403875662a0665595b1bcd57f43
