### ISSUE TITLE
Better metrics for memory cache

### ISSUE THREAD

**Issue by nicktelford** [Jeffail/benthos#819]
When using a `memory` cache for the `dedupe` processor, there is currently only `keys` and `compactions` metrics.

It would be useful to have, at a minimum:
* `hits` and `misses` (that can be used together to calculate a hit-rate)
* `errors` to aid in determining when a problem occurs - I mostly expect this to be incremented when an error is encountered evaluating the `dedupe.key` expression and `dedupe.drop_on_err == false`.

**Comment by Jeffail** [comment]
I've swapped out the implementations of the `memory` and `file` caches for a wrapper that adds these metrics: https://github.com/Jeffail/benthos/blob/master/internal/component/cache/cache_v2.go#L70, which will eventually be the standard across all caches. The old `keys` gauge still exists in the memory cache.
