### ISSUE TITLE
Tracing issue in v2BatchedToV1Processor.ProcessMessage()

### ISSUE THREAD

**Issue by seanlaff** [Jeffail/benthos#820]
Hi there,

We're trying out the new plugin system and think there's a bug in the way spans are getting closed. We're getting missing parents and duplicate span id warnings. Additionally, our BatchProcessor doesn't show up in the traces at all.

Looking into it, it seems like this line here https://github.com/Jeffail/benthos/blob/1ce55c108b05f625bdfa020b7874882638f8036d/internal/component/processor/processor_v2.go#L200 should actually be `tracing.FinishSpans(newMsg)`?

This fix seemed to do the trick for us.

Sidenote: Each part gets the timing of the entire batch, not a per-part timing. I don't think benthos has a way it could do this magically for you since the BatchProcessor is entirely custom code. Previously we could instrument via something like `iteratePartsWithSpan()`, but now that the `part` is private in `service.Message`, I don't think we have a way of enriching the traces any more granularly. Unsure if this is an uncommon case, but wanted to mention it.

**Comment by Jeffail** [comment]
Hey @seanlaff, thanks for raising this, it looks like you're spot on. I'll get this fixed today and hopefully get a release out.

My intention is to eventually offer something like a `.Context()` method to the new `*Message` type which would allow you to extract and create your own spans. It'll be quick to add but I need to think about what implications exposing it would have for versioning.

**Comment by seanlaff** [comment]
Thanks @Jeffail , sounds great!

**Comment by Jeffail** [comment]
Released in https://github.com/Jeffail/benthos/releases/tag/v3.49.0
