### ISSUE TITLE
Add message batching to Redis PubSub for performance improvement

### ISSUE THREAD

**Issue by lorenz-qbees** [Jeffail/benthos#823]
For getting higher message rates with Redis PubSub (> 400 msgs/sec) a batching mechanism would be necessary.
Maybe also a good feature for other Redis outputs.

**Comment by Jeffail** [comment]
Hey @lorenz-qbees, implemented: https://github.com/Jeffail/benthos/commit/25c740bf1c1377962cdbe822029f7a4b5e6b54aa so it'll be in the next release. I've also added benchmarking capabilities to the integration test suite in order to check the difference (https://github.com/Jeffail/benthos/commit/fae357cf4550bea4ce85ba77c3a16f04889a1264), which is looking much higher as expected. If you get a chance to try it out before the next release it'd be good to know what your new throughput is.

**Comment by lorenz-qbees** [comment]
Hi @Jeffail, thanks for this lightning fast implementation!
We debugged the target redis cluster and there seems to be a problem. With a plain-vanilla redis installation we got > 40k msgs/sec throughput without batching.
With redis pubsub on batching mode we are currently unable to send messages. The first batch is sent, after that there is no traffic until killing benthos with CTRL-C which causes a last batch arriving in redis.

**Comment by Jeffail** [comment]
Interesting, are you able to share your output config?

**Comment by lorenz-qbees** [comment]
```
output:
  redis_pubsub:
    url: redis://my_redis_cluster:1234
    kind: cluster
    channel: my_channel
    batching:
      count: 20
```

**Comment by Jeffail** [comment]
Any interesting logs from either benthos or redis?

**Comment by Jeffail** [comment]
Hey @lorenz-qbees, I've tried with a few different set ups and I'm not seeing any issues, I'm wondering if this might be related to how the redis cluster is arranged. Any chance you can try and reproduce the issue with something I can run with docker-compose? 

Also worth double checking the input as the behaviour you're describing is exactly what I'd expect to see if the input provided only enough messages for one full batch and then nothing more, as the second batch would never complete and therefore wouldn't flush until you shut the service down.

**Comment by lorenz-qbees** [comment]
Hey @Jeffail,
redis cluster and PubSub batching are working like a charm, I just forgot to set a batching period (tooks ages to get a full batch).
Throughput is much better now for redis clusters with higher latencies.
I think this feature is ready for release 👍 
Thank you!

**Comment by Jeffail** [comment]
Awesome, thanks for testing it @lorenz-qbees!

**Comment by Jeffail** [comment]
Going to close for now, the next release will likely be early next week.
