### ISSUE TITLE
`format_json` in bloblang?

### ISSUE THREAD

**Issue by mohamed--abdel-maksoud** [Jeffail/benthos#825]
Is there a way to serialize a data structure to JSON in bloblang? (the same way format_yaml is used)

**Comment by Jeffail** [comment]
Hey @mohamed--abdel-maksoud, JSON is the default format for structured data throughout Benthos, so you can just call `.string()` on a value to get the JSON representation, e.g. `root.thing = this.document.string()`.

**Comment by mohamed--abdel-maksoud** [comment]
Thanks @Jeffail for the answer for Benthos!
