### ISSUE TITLE
input `subprocess` breaks really long lines?

### ISSUE THREAD

**Issue by mohamed--abdel-maksoud** [Jeffail/benthos#826]
I have a python script as an input generator (subprocess), it generates JSONL with very long lines.
Between input and processing, line breaks are introduced (no matter how large I set max_buffer) which results in JSON parsing errors (I checked by redirecting to dead-letter file). I verified the script by itself never produces line breaks in the same record.

Any idea how to work around this?

**Comment by Jeffail** [comment]
Hey @mohamed--abdel-maksoud, this will likely need a bit of digging into to find out what's happening internally. I'll try and reproduce it locally.

**Comment by mohamed--abdel-maksoud** [comment]
Thanks @Jeffail , I can also create a small example in the weekend.

**Comment by SergeyRolich** [comment]
Hi @Jeffail, I have the same problem, this is due to the fact that if the line size is greater than 65536 and bufio cannot be read it.

**Comment by Jeffail** [comment]
Ahhh okay, does that mean increasing https://www.benthos.dev/docs/components/inputs/subprocess#max_buffer to beyond the max size of a line fixes the problem? As otherwise there's a bug in there that'll need fixing.

**Comment by SergeyRolich** [comment]
@Jeffail max possible value for https://www.benthos.dev/docs/components/inputs/subprocess#max_buffer - 65536. If message is longer will be error.

**Comment by SergeyRolich** [comment]
@Jeffail i can't reproduce this bug, after this fix https://github.com/Jeffail/benthos/commit/a71f6cbe41b63476da0f59707eaddd8f761aafba

**Comment by Jeffail** [comment]
Awesome, thanks for the update @SergeyRolich
