### ISSUE TITLE
IIS content type response is making http client to fail

### ISSUE THREAD

**Issue by egimbernat** [Jeffail/benthos#829]
When the client is calling legacy API that returns Content-Type as for example: **application/json; charset=utf-8,application/json** MIME verification fails and hence all the operation, no matter if the response will be used or not.

The issue occurs on https://github.com/Jeffail/benthos/blob/master/lib/util/http/client/type.go#L430 but curiously MediaType is correctly returned, I think is some workaround in Golang library.

Anyway, as an enhancement, I think of the following  solutions:
1- Trim all after **;**, is normal that ASPNet service return ContentType + codification, and for Go is garbage
2- Special case for mediaType != nil and ignoring the error
3- Defaulting to application/json in case of error and try to read and parse body

**Comment by Jeffail** [comment]
Hey @egimbernat, thanks for raising this. I think it would be fine to ignore the error since the media type is mostly just used for expanding multipart requests, I'll try and get this into the next release.

**Comment by Jeffail** [comment]
Done: https://github.com/Jeffail/benthos/commit/700fbf2eb0bb9bb3755298aae905c27d040b4842
