### ISSUE TITLE
Support dynamic queries in sql processors

### ISSUE THREAD

**Issue by AdrianLsk** [Jeffail/benthos#830]
Hello, could you support dynamic queries also for SQL processors like [AWS dynamo db] (https://www.benthos.dev/docs/components/processors/aws_dynamodb_partiql/) does?

Otherwise, the user has to write multiple configs for different queries.

**Comment by Jeffail** [comment]
Hey @AdrianLsk finally got around to this: https://github.com/Jeffail/benthos/commit/4d8799a7b50c9b343c5052c6bcdb7b3a658dce3c

**Comment by AdrianLsk** [comment]
Thanks @Jeffail. Much appreciated. You're the best!
