### ISSUE TITLE
Add amqp_0_9 output amqp_priority support?

### ISSUE THREAD

**Issue by dz-at-tc** [Jeffail/benthos#832]
I see that the amqp_0_9 input automatically makes the amqp_priority available as a metadata field.

Alas, unless I'm missing something, the amqp_0_9 output does not appear to automatically relay or otherwise allow one to set the amqp_priority for outgoing messages...  Thus they all have the default 0/lowest priority in RMQ priority queues.

Would it be possible to make this configurable?

Thanks!

**Comment by Jeffail** [comment]
Released: https://github.com/Jeffail/benthos/releases/tag/v3.53.0

**Comment by dz-at-tc** [comment]
Thank you sir, very much appreciated!

And I thoroughly enjoyed the walk-through on blobstream 9.  ;-)
