### ISSUE TITLE
Feature Request: RSA authentication with SFTP input / output

### ISSUE THREAD

**Issue by lorenz-qbees** [Jeffail/benthos#838]
Would be great to have an RSA key authentication method.
I'll have a look at it by myself and keep this issue updated.

**Comment by Jeffail** [comment]
Hey @lorenz-qbees, yeah this would be a reasonable addition.

**Comment by mihaitodor** [comment]
I can take a stab at this. There's some prior art in rclone here: https://github.com/rclone/rclone/blob/654575575810fb01f76e8b4ffb363adfe7473afe/backend/sftp/sftp.go

**Comment by lorenz-qbees** [comment]
@mihaitodor looks great! I will try to implement RSA authentication today and keep this issue updated.
