### ISSUE TITLE
MessagePack processor support

### ISSUE THREAD

**Issue by isae** [Jeffail/benthos#847]
Hi! I am really excited about Benthos, thank you for this cool tool!

For my company's usecase it would be nice to have support for [MessagePack](https://msgpack.org/) format. This should be similar to [Avro](https://www.benthos.dev/docs/components/processors/avro) (even simpler, I think, because MsgPack has no schema). 

I'll try to contribute it in my spare time.

**Comment by Jeffail** [comment]
Hey @isae :smile: this seems like a good addition, it'd probably make sense as a processor, looks like https://github.com/vmihailenco/msgpack is a good candidate.

**Comment by Jeffail** [comment]
Implemented as a processor: https://github.com/Jeffail/benthos/commit/c517a65345fdd62a3af3e8cda3087ea9616db1ba, and some complementary bloblang methods: https://github.com/Jeffail/benthos/commit/2e4a4565cba344ef9343b7850f5258ad9867f24c
