### ISSUE TITLE
Authenticating with a credentials file in NATS resources

### ISSUE THREAD

**Issue by KairaMiu** [Jeffail/benthos#859]
In addition to authentication with user and password and authentication with token, which both can be passed within the URL there are some other methods to authenticate against a NATS server:
* [Authenticating with an NKey](https://docs.nats.io/developing-with-nats/security/nkey)
* [Authenticating with a Credentials File](https://docs.nats.io/developing-with-nats/security/creds)

Is it planned to support another authentication method in the future? I would be interested using one of these methods, preferring the credentials file.

**Comment by Jeffail** [comment]
Hey @KairaMiu, sure this seems like a reasonable addition.
