### ISSUE TITLE
Add CORS handling in stream API server

### ISSUE THREAD

**Issue by dhinojosac** [Jeffail/benthos#867]
I'm developing a web GUI in VUE to manage streams via API. And I've some problems with CORS. It would be interesting if we can configure CORS on the server-side.
Thanks

![image](https://user-images.githubusercontent.com/5265771/132403614-931d0f5c-101f-4610-9955-e4bd43de3949.png)

**Comment by Jeffail** [comment]
Hey @dhinojosac, I've added some CORS fields to the http spec, you can see the preliminary documentation here: https://github.com/Jeffail/benthos/blob/master/website/docs/components/http/about.md

I've taken a best guess at some of the config defaults, the underlying choice of allowed methods is `GET`, `POST`, `HEAD`, `DELETE` as those are the methods used in the streams API. I've left allowed origins as a required config field, if you need any changes or extra fields let me know and I'll aim to get them in before the next release.

**Comment by dhinojosac** [comment]
Thanks, @Jeffail . I will test this feature and let you know if we need other fields. It would work for us in advance.

**Comment by dhinojosac** [comment]
ahhh, currently, I'm using the PUT method to edit stream in a Textarea input in the Vue application. It would be helpful in the next release!

**Comment by dhinojosac** [comment]
Already test it, and it works fine! Thanks, @Jeffail
