### ISSUE TITLE
How to check if value is null in bloblang

### ISSUE THREAD

**Issue by WaDelma** [Jeffail/benthos#868]
I am trying to drop message if certain field is not provided.

Here is my first try: https://lab.benthos.dev/l/s_i-y8aJKKh
It "works", but logs the following:
```
Log: Failed to test case 0: failed assignment (line 1): cannot compare types string (from field `this.email`) and null (from null literal)
```
This behavior feels quite weird.

If I invert the condition: https://lab.benthos.dev/l/quJFB4lBO-C
there is no error, but the configuration is more verbose.

From this I can derive the following version: https://lab.benthos.dev/l/XcwQpSt14oQ
which works correctly, but feels bit convoluted.

This version also exposed hole in the documentation: Boolean operations aren't documented. First I didn't wrap the expression into string and got error because `!` is special in yaml. This led me to believe that bloblang doesn't support negation and to frantically search documentation which didn't give any information (I even tried to look into the parsers code but didn't find anything from there either). Then I randomly tried to wrap it into string and got it working.

**Comment by Jeffail** [comment]
Hey @WaDelma, thanks for raising this, that's a rather big hole in the docs. I think it should also be safe to expand `==` for strings to allow comparison against `null` so I'll look at that at the same time.

**Comment by WaDelma** [comment]
Thanks. It seems that those messages are retried even though I explicitly dropped them. Is that intentional?
```json
{"@timestamp":"2021-09-09T12:26:53Z","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to send messages: kafka: Failed to deliver 2 messages."}
{"@timestamp":"2021-09-09T12:26:53Z","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to send messages: kafka: Failed to deliver 2 messages."}
{"@timestamp":"2021-09-09T12:26:54Z","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to send messages: kafka: Failed to deliver 2 messages."}
{"@timestamp":"2021-09-09T12:26:55Z","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to send messages: kafka: Failed to deliver 2 messages."}
{"@timestamp":"2021-09-09T12:26:56Z","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to send messages: kafka: Failed to deliver 2 messages."}
{"@timestamp":"2021-09-09T12:26:59Z","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to send messages: kafka: Failed to deliver 2 messages."}
{"@timestamp":"2021-09-09T12:27:04Z","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to send messages: kafka: Failed to deliver 2 messages."}
{"@timestamp":"2021-09-09T12:27:12Z","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to send messages: kafka: Failed to deliver 2 messages."}
{"@timestamp":"2021-09-09T12:27:18Z","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to send messages: kafka: Failed to deliver 2 messages."}
{"@timestamp":"2021-09-09T12:27:18Z","@service":"benthos","component":"benthos.output","level":"ERROR","message":"Failed to send message to kafka: kafka: Failed to deliver 2 messages."}
{"@timestamp":"2021-09-09T12:27:19Z","@service":"benthos","code":"771-88-7679","component":"drop_if_no_email.0.0","reason":"Message was dropped because it didn't specify email","level":"WARN","message":""}
```

**Comment by WaDelma** [comment]
So deleting message is same as nacking it?

**Comment by Jeffail** [comment]
No the filtered messages are removed from the message batch during processing which is then routed to the output layer, if the output layer doesn't successfully send the batch and nacks it then the messages that weren't filtered are nacked and the messages that were removed by your filters are acked (as they were intentionally dropped).

However, in your case you're consuming from kafka, which doesn't have a concept of a nack, so instead of nacking or acking any messages the entire batch is processed again. Since the filters are the same the same messages are removed when the batch is processed again, so until the batch is successfully sent (and acked) by the output layer those filtered messages still "exist".

**Comment by WaDelma** [comment]
Okay. Got confused by the failure and thought it was retrying because of the filter, but after trying again it seemed to behave correctly.

**Comment by Jeffail** [comment]
Forgot to update this ticket, got an implementation that fixes string comparisons: https://github.com/Jeffail/benthos/commit/ef8939a748a872d8ba835b75e8ffc6eb68205c84, also adds docs specifically covering arithmetic.
