### ISSUE TITLE
Benthos interactive mode

### ISSUE THREAD

**Issue by klintan** [Jeffail/benthos#870]
Hello! 
This is just really an idea I thought of while debugging one of my pipelines: 
- It would be awesome to be able to run it in interactive mode, basically run each step at time, and also see the output object + metadata as one is running. Would also be able to "build" your pipeline as you run it instead of declaring it before. 

I fully understand that this might be a huge undertaking :D but yeah just wanted to float it :) 

Thanks for an awesome tool!

PS. if something like this already exists for benthos, I couldn't find anything in the docs related to it.

**Comment by Jeffail** [comment]
Hey @klintan, I like it, there's roughly similar ideas floating around that also coincide with the possibility of building a visual interface for Benthos (https://github.com/Jeffail/benthos/issues/581). I'm not ready to reveal any details yet but there will be a successor to https://lab.benthos.dev soon™.

**Comment by klintan** [comment]
Sounds very exciting, looking forward to any and all announcements :)
