### ISSUE TITLE
New SetYAML/Add*YAML do not perform interpolation

### ISSUE THREAD

**Issue by bkjones** [Jeffail/benthos#881]
Just tried to use SetYAML and AddResourceYAML for the first time today. For the input to these functions I passed in YAML that I had read straight from config files on disk. Based on the errors & debugging I've done, it appears that these functions do not perform interpolation of variables in the config files, so anywhere there's something like:

`redis_url: ${REDIS_URL:redis://localhost:6379/0}`

it needs to be changed to read: 
`redis_url: redis://localhost:6379/0`

It would be great if these functions performed the interpolation directly. I'm sure it would suffice to have a function I could pass the configs through first that performs the interpolation & returns the result, ready to be passed into SetYAML and friends.

**Comment by Jeffail** [comment]
Hey @bkjones, I'm thinking right now that environment variables should be substituted by these methods by default, as even though the documentation for the API doesn't mention it I think it's reasonable to expect as it's how general configuration loading works elsewhere.

**Comment by bkjones** [comment]
Hi @Jeffail - I agree -- without any specific use cases in support of exposing interpolation functionality independently, the service you probably want to expose at this point is just the Set/Add*YAML functions, which should perform interpolation themselves. 

For what it's worth, I researched using the benthos 'echo' command for this just as a temporary hack and to learn more about benthos. It seems that echo performs actual _validation_ however, and for some reason (probably my own fault) my custom processor types are "not recognised". For the purpose of certain tests, the interpolation is what I would personally want, not full-on validation. Was that intentional, and are the concepts of validation and interpolation generally intended to be tightly coupled in benthos?

**Comment by Jeffail** [comment]
Done: https://github.com/Jeffail/benthos/commit/da41289cdb7b8c6f32072650c6c589310e2aa915
