### ISSUE TITLE
Kafka Mutual TLS Support

### ISSUE THREAD

**Issue by eyad-kobatte** [Jeffail/benthos#884]
Hello,

I am trying to use Benthos to connect to Kafka brokers as a producer client (Kafka input)

There is a requirement of using Mutual TLS in the connection. Does Benthos support Mutual TLS for Kafka?

I could not find any documentation on Mutual TLS in the docs.

If Mutual TLS is not available, would it be possible to get this feature added into Benthos?

**Comment by Jeffail** [comment]
Hey @eyad-kobatte, pretty sure everything you need should be available with the TLS options: https://www.benthos.dev/docs/components/inputs/kafka#tls, you'll likely need to add a root CAS file that verifies the broker you're connecting with, and then also some client certificates that verify the client.

One caveat is that there's an issue still open for supporting password protected client certs https://github.com/Jeffail/benthos/issues/871 so for now you'll only be able to use certificates without password protection.

**Comment by eyad-kobatte** [comment]
Ah alright. Thanks for the quick response @Jeffail. I will go ahead and close this issue for now then.
