### ISSUE TITLE
Support arm64 for AWS lambda

### ISSUE THREAD

**Issue by razor-x** [Jeffail/benthos#895]
See https://aws.amazon.com/blogs/aws/aws-lambda-functions-powered-by-aws-graviton2-processor-run-your-functions-on-arm-and-get-up-to-34-better-price-performance/

**Comment by razor-x** [comment]
Not sure how I missed this: https://docs.aws.amazon.com/lambda/latest/dg/lambda-golang.html

> Runtimes that use the Amazon Linux operating system, such as Go 1.x, do not support the arm64 architecture. To use arm64 architecture, you can run Go with the provided.al2 runtime.

Will try to find out how complicated switching to using the `provided.al2 runtime` is.

**Comment by mihaitodor** [comment]
If [this](https://github.com/aws/aws-sam-build-images/blob/develop/build-image-src/Dockerfile-provided-al2) is what's in that `provided.al2` container, it seems like a lot of bloat for a lambda. Do they refuse to launch containers which are not based on it?

**Comment by razor-x** [comment]
Maybe? But looks like the previous image was not much lighter: 

Anyway, I seem to have it working. The key is [this tweet](https://twitter.com/__steele/status/1443550405816840196?s=20): I just had to rename `benthos-lambda` to `bootstrap` in the zip file.

![image](https://user-images.githubusercontent.com/721372/140006373-570ba150-7c39-4b97-8ad3-4d5517d28276.png)

![image](https://user-images.githubusercontent.com/721372/140006439-26845c2e-d5fd-4de3-b078-156fc4b9c82e.png)

**Comment by mihaitodor** [comment]
Looks like there's a field called `binary`: https://goreleaser.com/customization/build/

**Comment by razor-x** [comment]
Ok, I think we might need to do something like this: https://github.com/Jeffail/benthos/pull/937

**Comment by razor-x** [comment]
Updated docs WIP: https://github.com/Jeffail/benthos/pull/940
