### ISSUE TITLE
Include metadata with specific prefixes as headers to http_client output request

### ISSUE THREAD

**Issue by dmoeff** [Jeffail/benthos#899]
I would like to provide a list of prefixes and all metadata with these prefixes to be included as headers in the http_client request.

**Comment by cabrrtt** [comment]
On reading this ticket more carefully, I believe that the use case I was exploring in #901 would be satisfied by this feature request, except that in th cisase it is http_server input in which the behaviour would sit.

**Comment by cabrrtt** [comment]
Rather than prefix, could / should this be one or more RegExp pattern matches since it is important to be able to match the headers with precision (at least the use case I have)?

**Comment by dmoeff** [comment]
RegExp pattern also will work fine

**Comment by dmoeff** [comment]
Hi @Jeffail , I don't think this is what I asked as a feature. I wanted input message metadata with specific prefix to be included as headers to `http_client` output request.

**Comment by Jeffail** [comment]
@dmoeff haha whoops, looks like we updated all the http client components except specifically for the use case you asked for. Sorry 😅

I think adding metadata include filters should be straight forward as we can reuse the mechanism from other outputs, so hopefully this can be quick to add.

**Comment by mihaitodor** [comment]
Whoops, my bad! I somehow misunderstood the requirement.

**Comment by trevor-monk** [comment]
This is an excellent feature!  I need this as soon as possible to convert meta-data from pipeline messages into meta-data to be sent to an Azure IOT Hub using an HTTP request.

**Comment by Jeffail** [comment]
Done: https://github.com/Jeffail/benthos/commit/f3eac2c93ad6de6c386131a16993e65b51994f3f
