### ISSUE TITLE
Allow aws sqs input to respect visibilityTimeout on Nacks

### ISSUE THREAD

**Issue by ekeric13** [Jeffail/benthos#910]
via @Jeffail 
https://github.com/Jeffail/benthos/issues/697#issuecomment-793670035
> the Nack behaviour for the SQS inputs to set the visibility timeout to zero, which allows SQS to reroute the message according to your redrive policy

You may want to respect the current visibility timeout though. And instead of retrying the message immediately, dequeue the message in an hour or whatever the present visibility timeout is.

Currently I am running into this issue where I am using aws_sqs as an input, dequeueing the messages, sending them to an output of http_client, and if failing I do not want them to be retried immediately but to respect the visbility timeout. http_client does have some retry logic built in, but it isn't naturally fault tolerant the way sqs retries and visibility timeouts are.

It would be great if aws_sqs input could have a parameter of `respect_visibilty_timeout` that defaults to `false` in order to maintain backwards compatibility.

**Comment by Jeffail** [comment]
Sure, feel free to open a draft PR early if you have questions

**Comment by ekeric13** [comment]
So I still have had an issue with benthos seemingly reseting the visibilityTimeout to 0. Specifically in scenarios where I get a nack because of a timeout on it's output.
One place this the timeout being reset to 0 could be occurring is if a message is being processed but benthos shuts down unexpectedly, I believe we exit the `readLoop` fn:
https://github.com/benthosdev/benthos/blob/main/internal/old/input/aws_sqs.go#L265-L283

This has the side effect of calling `resetMessages` for any outstanding messages that are still being processed:
https://github.com/benthosdev/benthos/blob/main/internal/old/input/aws_sqs.go#L220-L238

If benthos were to be rebooted right back up, the message will then be re-tried much sooner than the visibilityTimeout.
An easy fix for this would just be to return early from `resetMessages` no matter where it is called:
https://github.com/ekeric13/benthos/commit/b13af800dfd43a20f6ef224f0decf05278fe3455
Planning on making a PR for this change.


Maybe I am reading the code wrong but if benthos is not shutting down unexpectedly, I am still confused about how an output timeout leads to a reset of the visibilityTimeout. Would a timeout on the output side of things lead to just a normal nack or would it call `WaitForClose`?:
https://github.com/benthosdev/benthos/blob/main/internal/old/input/aws_sqs.go#L437-L452

**Comment by bentcoder** [comment]
@Jeffail I need to upgrade from v3 to v4 for this feature but not able to find matching packages for the list below. How do I go about please?

```go
import (
	"github.com/Jeffail/benthos/v3/lib/log"
	"github.com/Jeffail/benthos/v3/lib/message"
	"github.com/Jeffail/benthos/v3/lib/metrics"
	"github.com/Jeffail/benthos/v3/lib/response"
	"github.com/Jeffail/benthos/v3/lib/types"
)
```

I run `go get github.com/benthosdev/benthos@v4.2.0` but I cannot import anything.

**Comment by bentcoder** [comment]
Thank you for the prompt answer @Jeffail. I am little lost with the migration. My aim has been merging this example into V4 but so far couldn't work out how.

```go
package main

import (
	"github.com/Jeffail/benthos/v3/lib/service"

	_ "my/benthos/processor"
)

func main() {
	service.Run()
}
```

```go
package processor

import (
	"github.com/Jeffail/benthos/v3/lib/log"
	"github.com/Jeffail/benthos/v3/lib/message"
	"github.com/Jeffail/benthos/v3/lib/metrics"
	"github.com/Jeffail/benthos/v3/lib/response"
	"github.com/Jeffail/benthos/v3/lib/types"
)

func init() {
	processor.RegisterPlugin("testing", NewConfig, NewConsumer)
}

type config struct {}

func NewConfig() interface{} {
	return webhook{}
}

type consumer struct {
	logger log.Modular
}

func NewConsumer(cfg interface{}, mng types.Manager, log log.Modular, met metrics.Type) (types.Processor, error) {
	return consumer{logger: log}, nil
}

func (c consumer) CloseAsync() {}

func (c consumer) WaitForClose(time.Duration) error {}

func (c consumer) ProcessMessage(msg types.Message) ([]types.Message, types.Response) {}
```

**Comment by Jeffail** [comment]
@bentcoder new APIs docs are here with examples: https://pkg.go.dev/github.com/benthosdev/benthos/v4@v4.2.0/public/service#example-package-ProcessorPlugin, and there's an example repo containing plugin definitions: https://github.com/benthosdev/benthos-plugin-example

**Comment by bentcoder** [comment]
Thank you, I'll have a read once I have more time.
