### ISSUE TITLE
parse_duration vs ISO 8601 durations

### ISSUE THREAD

**Issue by aldot** [Jeffail/benthos#913]
parse_duration is only able to parse custom durations since that's what the (currently) underlying libgo/go/time/format.go is capable of.

It would be nice to be able to parse normal ISO 8601 durations.
Note that 8601 durations do not support sub-seconds durations which is of course a pity (and probably the reason go went this different way).

**Comment by mihaitodor** [comment]
@aldot I took a stab at implementing this in https://github.com/Jeffail/benthos/pull/927. Please note that the library I imported (https://github.com/rickb777/date) only allows one decimal place for fractional fields: https://github.com/rickb777/date/blob/2e89fc3894a76d04fdf60d78a6141015a083f6f0/period/parse.go#L191
