### ISSUE TITLE
unable to infer output type, candidates were: [gcp_cloud_storage] with Benthos 3.57.0, on Beta feature

### ISSUE THREAD

**Issue by lent85** [Jeffail/benthos#926]
I'm making custom processors so create a project with dependencies like below:
```
module bitbucket.org/mapping-proxy

go 1.16

require (
	github.com/Jeffail/benthos/v3 v3.57.0
	github.com/Shopify/sarama v1.30.0
	github.com/gofrs/uuid v4.1.0+incompatible
	github.com/json-iterator/go v1.1.12
	github.com/opentracing/opentracing-go v1.2.0
	go.uber.org/automaxprocs v1.4.0
)
```

So, I'm using benthos version **3.57.0**, and create output like below

```
output:
  broker:
    pattern: fan_out
    outputs:
      - kafka:
          ...
      - aws_s3:
          ...
      - gcp_cloud_storage:
          ...
      - gcp_pubsub:
          ...

```

All the other output working, except for _gcp_cloud_storage_ (which is beta, available from Benthos 3.43.0) , which showing the error message _unable to infer output type, candidates were: [gcp_cloud_storage]_

My main.go 

```
func main() {
	go sendBrokerStartedEvent()
	go ballast()
	service.Run()
}
func ballast() {
	ballastSizeBytes, exists := os.LookupEnv("GOLANG_BALLAST")
	if exists {
		fmt.Println("Creating memory ballast.")
		if bytes, err := strconv.Atoi(ballastSizeBytes); err == nil {
			ballast := make([]byte, bytes)
			_ = ballast
		}
	}
}
func sendBrokerStartedEvent() {
	_, exists := os.LookupEnv("DISABLE_BROKER_START_EVENT")
	if !exists {
		processor.SendBrokerEvent("started")
	}
}

func sendBrokerShutdownEvent() {
	processor.SendBrokerEvent("shutdown")
}
```

**Comment by Jeffail** [comment]
Hey @lent85, plugin implementations are gradually being updated to allow for selective imports, so the newer stuff needs to be imported explicitly into your custom build like this: https://github.com/benthosdev/benthos-plugin-example/blob/master/main.go#L9

**Comment by lent85** [comment]
I already import the new processor. The issue here is the beta feature `gcp_cloud_storage` which suppose to be existed from version 3.43.0
https://ibb.co/KN0m1gF

**Comment by Jeffail** [comment]
@lent85 the specific line you need is `_ "github.com/Jeffail/benthos/v3/public/components/all"`, it's an import that basically expresses "give me all the benthos native plugins". Eventually there's going to be bundles but right now it's all or nothing (and old style benthos plugins are always available).

**Comment by lent85** [comment]
Ok, after rebuild and import as above, I got it working. Thanks @Jeffail

**Comment by lent85** [comment]
Ok, after rebuild and import as above, I got it working. Thanks @Jeffail
