### ISSUE TITLE
How can a custom processor Nack the input in v4?

### ISSUE THREAD

**Issue by serkrebs** [Jeffail/benthos#932]
In v4, inputs and outputs _may_ retry indefinitely (which is a very good thing).

I'm converting a custom processor from v3 to v4. My processor relies on a network resource which could be down or misconfigured. If my Process(msg) method returns nil for the error, the message proceeds normally down the pipeline to the output. If my Process(msg) method returns any error, the message proceeds (flagged) down the pipeline. Naturally, I can detect that error and either filter it or route it to a dead letter resource.

What is the proper way to Nack the input for the message so that the input source will retry the original message until the network resource becomes available?

The only option I can think of is to retry in my custom processor without returning. But that seems like an egregious anti-pattern. (For example, that could cause a trace span that is held open for a very long time.)

**Comment by Jeffail** [comment]
hey @serkrebs, if you want to nack (and therefore retry) the message then I'd recommend using a switch output with a reject child like this: https://www.benthos.dev/docs/configuration/error_handling#reject-messages, as that retains back pressure for general outages but also prevents a single message from blocking a processing thread for message-specific issues.

**Comment by serkrebs** [comment]
I will give it a go.
