### ISSUE TITLE
Support interpolation for NSQ topics

### ISSUE THREAD

**Issue by dudleycarr** [Jeffail/benthos#94]
Use case: I'm consuming notifications from PostgreSQL and sending them to Benthos via STDIN. Ideally, I'd be able to look at the table name in the payload to be able to send it to an NSQ topic based on the table name.

**Comment by Jeffail** [comment]
Released: https://github.com/Jeffail/benthos/releases/tag/v0.31.0

**Comment by dudleycarr** [comment]
Thank you!
