### ISSUE TITLE
Documentation and implementation contradiction

### ISSUE THREAD

**Issue by Tapuzi** [Jeffail/benthos#946]
Hello Jeff and maintainers!
I love you mellowly, mundanely and in an everyday manner only, for creating this project.

[In the map_each doc page,](https://www.benthos.dev/docs/guides/bloblang/methods/#map_each) the following example appears:
```
root.new_nums = this.nums.map_each(num -> if num < 10 {
  deleted()
} else {
  num - 10
})

# In:  {"nums":[3,11,4,17]}
# Out: {"new_nums":[1,7]}
```
However, Benthos doesn't like that specific example.
![image](https://user-images.githubusercontent.com/5293751/141340189-eadd03a2-5c05-403d-8cc4-0259a610b25c.png)

Looks like the parts within the `{}` brackets are not accepted. 
The following works:
```
root.new_nums = this.nums.map_each(num -> num - 10)

# In:  {"nums":[3,11,4,17]}
# Out:  {"new_nums":[-2,6,-1,12]}
```

(Benthos `Version: v3.54.0`)

**Comment by Jeffail** [comment]
Hey @Tapuzi, which operating system are you running on? I've just tried it locally and it seems to work but I'm wondering if between copy/pasting from the browser a carriage return is being added to the end of the line. I believe right now a carriage return actually fails to parse as we only expect lines to end with line feed, in which case I should probably expand the parser to allow it.

**Comment by Tapuzi** [comment]
I am running on docker. (under WSL in windows)

Here is my attempt to remove all carriage return:
![image](https://user-images.githubusercontent.com/5293751/141418372-65d5e806-e277-42a9-aad1-c9e282a898b7.png)

**Comment by Jeffail** [comment]
Okay fixed this, in the next version bloblang will allow CR+LF: https://github.com/Jeffail/benthos/commit/3e486da1bc03e6a241601a447217a7d53f3d57e0
