### ISSUE TITLE
Input `subprocess` corrupt messages 

### ISSUE THREAD

**Issue by SergeyRolich** [Jeffail/benthos#951]
I have a golang app as an input generator (subprocess), it generates JSON. 
For some unknown reason, data corrupted between input and processing. Input incorrectly handles the line break character **\n**

I created a simple example where can check this https://github.com/SergeyRolich/stdout-example

I also tried python script, result the same.

Example log:
`{"@timestamp":"2021-11-17T17:59:45Z","@service":"benthos","component":"resource.processor.log_invalid_json","content":"}\n{\"_id\":\"6194ef828cd3eb8868ae6098\",\"index\":9,\"guid\":\"90eedc70-e83a-44f0-9195-4500292e05d7\",\"isActive\":false,\"balance\":\"$2,437.65\",\"picture\":\"http://placehold.it/32x32\",\"age\":25,\"eyeColor\":\"blue\",\"name\":\"Lenora Shaffer\",\"gender\":\"female\",\"company\":\"ENOMEN\",\"email\":\"lenorashaffer@enomen.com\",\"phone\":\"+1 (959) 465-3737\",\"address\":\"348 Alton Place, Kerby, Kentucky, 4494\",\"registered\":\"2018-05-24T08:15:26 -06:00\",\"latitude\":26.648183,\"longitude\":-12.624392,\"tags\":[\"consectetur\",\"nulla\",\"labore\",\"nulla\",\"id\",\"aliquip\",\"ut\"],\"friends\":[{\"id\":0,\"name\":\"Sherri Poole\"},{\"id\":1,\"name\":\"Luella Kidd\"},{\"id\":2,\"name\":\"Huff Fletcher\"}],\"greeting\":\"Hello, Lenora Shaffer! You have 1 unread messages.\",\"favoriteFruit\":\"banana\"}\n{\"_id\":\"6","error_type":"NOT_VALID_JSON","level":"ERROR","message":"Not valid json, will be dropped"}
`

**Comment by Jeffail** [comment]
Hey @SergeyRolich, thanks for raising this (and the great example). This looks like a bug, will try and get a fix together ASAP.

**Comment by Jeffail** [comment]
Fixed: https://github.com/Jeffail/benthos/commit/a71f6cbe41b63476da0f59707eaddd8f761aafba, this is a pretty nasty issue so I'll try and get the ball rolling faster on the next release.

**Comment by SergeyRolich** [comment]
it works for me, thanks
