### ISSUE TITLE
A way to process/decode/encode protobufs? 

### ISSUE THREAD

**Issue by nwest1** [Jeffail/benthos#98]
The use case: input, decode protobuf, encode json, output.

I wrote my own processor (decode proto & encode json), included the necessary generated go files, and it works great. But I feel like there should be a more generic way to accomplish this. 

That might not be possible due to the need to include/compile the generated files but just wanted to discuss options.

Thanks!

**Comment by nwest1** [comment]
Further issue reading indicates this would be solved within some kind of plugin, so this issue is probably moot.

**Comment by Jeffail** [comment]
Hey @nwest1, yeah I'd recommend doing this with a plugin.
