### ISSUE TITLE
Annoying nats lots when acks are disabled

### ISSUE THREAD

**Issue by mariosant** [Jeffail/benthos#989]
When consuming a nats subject that doesn't support replies, I get an error:

```
{"@timestamp":"2021-12-05T18:35:57+02:00","@service":"benthos","component":"benthos.input","level":"ERROR","message":"Failed to acknowledge message: nats: message does not have a reply"}
```
Steps to reproduce:
* Create a nats producer as a benthos stream
* Create a nats consumer as a benthos stream

Run the above via benthos cli.

**Comment by mariosant** [comment]
As a side note, the folloying has been said by @Jeffail :+1: 
>that's a bug I think, it means we're consuming a subject that doesn't support replies but trying to ack, which fails 
we should maybe warn on that (as it means delivery isnt guaranteed) but we shouldn't log an error each time
however, those logs are also harmless, it should continue to consume data
relevant error: https://github.com/nats-io/nats.go/blob/main/nats.go#L130

**Comment by Jeffail** [comment]
Fixed in https://github.com/Jeffail/benthos/commit/48c1c5b222e80939dec92ff24ac3920c28f63986
