### ISSUE TITLE
Add immutability support to streams configs

### ISSUE THREAD

**Issue by difabion** [Jeffail/benthos#993]
At current, running a benthos in streams mode allows any changes to running configs without authentication via API.  This can be prevented by turning off the HTTP server, but that comes with a lot of disadvantages.  A CLI flag to set e.g. [static streams configs](https://www.benthos.dev/docs/guides/streams_mode/using_config_files) as immutable during runtime would allow the HTTP server to continue doing its mundane work. :)

My read through the streams API docs suggest disabling all verbs other than GET should be sufficient.

**Comment by Jeffail** [comment]
I've added a flag for it https://github.com/Jeffail/benthos/commit/d6f26ad83e4e437565aa1c93bc6133673a836fde to disable all the streams mode endpoints.
