### ISSUE TITLE
Streams mode does not support file wildcards when run in K8s

### ISSUE THREAD

**Issue by difabion** [Jeffail/benthos#994]
Given:
`benthos -c config.yaml streams /streams/*.yaml`

Expected behavior:
all files matching the wildcard are parsed and configured as individual streams

Actual behavior:
`Stream configuration file read error: stat /streams/*.yaml: no such file or directory`

As identified by @Jeffail:
```
benthos streams ./foo.yaml ./configs/*.yaml works because the shell expands the wildcards for you
however, benthos streams ./foo.yaml "./configs/*.yaml" won't work as it's passed as a literal string arg to benthos which doesnt expand
```

**Comment by Jeffail** [comment]
Done https://github.com/Jeffail/benthos/commit/507d89008061da38219f4a8ca8837721b72bb02e
